### ISSUE TITLE
Document Unicode emoji coverage

### ISSUE THREAD

**Issue by Crissov** [hfg-gmuend/openmoji#10]
Despite #6 I could not find a quick overview of glyphs missing for full Unicode Emoji 11.0 support, also known as an agenda or a to-do list.

Once you can claim full support of a certain Unicode version (and allow efforts to maintain annual updates), Iʼm confident Emojipedia.org will start documenting this set, boosting its popularity.

**Comment by b-g** [comment]
Hi @Crissov,

yes this is also on our list. The best overview gives [data/openmoji.csv](https://github.com/hfg-gmuend/openmoji/blob/master/data/openmoji.csv) which shows all emojis which we designed. I'm currently working auto-generating the skintones and a bigger update for around January which will be a big step forward with skintones, all flags, and ca. 200 other new ones. 

We will ping Emojipedia.org etc. once we have a full unicode version compatible set.

**Comment by b-g** [comment]
Fixed with https://github.com/hfg-gmuend/openmoji/commit/6b04dc12a6ffa34e00dc0bb106d5e519dbe77113. The unicode-range is documented in https://github.com/hfg-gmuend/openmoji/blob/master/font/openmoji.css. Subject to change for the  OpenMoji 2.0 release (very soon).
