### ISSUE TITLE
OpenMoji Jekyll Plugin

### ISSUE THREAD

**Issue by MahdiBaghbani** [hfg-gmuend/openmoji#103]
Hi,
I'm not a student at your university but I'm interested in your work since I saw it on the GitHub.

I was wondering how I can contribute to your project, I saw that you already have apps for iOS and other platforms, also a font (well your font is a bit weird).

But when it comes to using your emojis on websites, you only have npm package which is not enough and manually typing all the links for OpenMoji images is a  **pain**.

Many people are using Jekyll to create a static website and also GitHub pages are mainly powered by Jekyll, so is it GREAT to have OpenMoji out of the box in Jekyll?

I found default gem for producing easy emoji images is Jemoji, which is not customizable and only supports png extensions, I forked not only Jemoji but 2 other deeper layers of gem dependencies and created a new workflow that can easily serve OpenMoji emojis (and possibly any other emoji image source) with any format (SVG, png, jpg, BMP) into Jekyll.

This is as easy as adding `gem jekyll-openmoji` to your Jekyll website Gemfile and using `:emojicode:` inside your markdown files and BOOM you have emojis ready inside your webpage.

View the live overview of Jekyll website with OpenMoji emojis:
https://azadeh-afzar.gitlab.io/Web-Development/OpenMoji-Jekyll-Plugin

View source:
https://gitlab.com/Azadeh-Afzar/Web-Development/OpenMoji-Jekyll-Plugin

I work mainly on Gitlab but I also have a GitHub mirror if you want to star or fork it:
https://github.com/azadeh-afzar/OpenMoji-Jekyll-Plugin

Also, I want to ask you if you approve my attribution to your project inside the preview site and projects README file.

**Comment by b-g** [comment]
Hi @MahdiBaghbani, Nice! I am just not really into the gem and Jekyll world ... hence it is hard for me to evaluate it. Nevertheless here some feedback ...

Could you add in your readme:
- OpenMoji version number
- under 3. a few more examples like `I give this plugin two :+1:!` and also how it renders

Questions / Comments:
- Can people use `gem jekyll-openmoji` and then have OpenMojis with Github Pages?
- Where can I find the list to map :CODE: to emoji/hexcode?
- How could people then use our non-unicode emojis e.g. https://openmoji.org/library/#emoji=E09A?
- Please be aware that we would expect that you maintain it e.g. updating to the newest OpenMoji in a reasonable time ... ok?
- Would it not be better to have just a single repo? :) 
- Should I link to Github or Gitlab?

**Comment by MahdiBaghbani** [comment]
Hi @b-g 

1. The OpenMoji version already exists in readme badges (in the 4th row the first badge from left)

2. About examples you are absolutely right, I should provide more examples and also show how it would render. 
also, you can see the way it renders in this page https://azadeh-afzar.gitlab.io/Web-Developmen/OpenMoji-Jekyll-Plugin

3. YES, actually that's why I have decided to implement this first for Jekyll.
please this documentation from GitHub https://help.github.com/en/github/working-with-github-pages/about-github-pages-and-jekyll#plugins
It mentions Jemoji as 

> the Jemoji plugin lets you use GitHub-flavored emoji in any page on your site the same way you would on GitHub.

my plugin is simply a fork of Jemoji with better support for image extensions and custom emoji image sources, so it will work with GitHub pages like a charm.

4. the emojis inside :CODE: is determined by another package, this package uses a JSON file from Unicode (currently version 12.1).  this JSON has emoji and its aliases, when you type :alias:, it finds the corresponding hex code and turns that into filename so jekyll-openmoji can serve an image instead of :alias:, you can see the JSON file here
https://github.com/azadeh-afzar/Negareh-Emoji-Library/blob/master/db/negarmoji.json

the codes are mostly the same as you use in GitHub, there is a cheat sheet (which is outdated and some codes may not work for Unicode 12.1) 
https://gist.github.com/roachhd/1f029bd4b50b8a524f3c

BTW it is easy to write a script and extract all the aliases from the JSON file 😀 

5. well that's the fun part, I'm not aware of OpenMoji extras or technical parts, 
but if you want to have non-Unicode emojis you should try to edit that JSON file and register your emojis with unique alases and hex code.

6. I'm like a full-time open sourcerer (if my electrical engineering exams in university let me have some spare time), so I can maintain it easily.

7. having all them under one repo is problematic in my opinion, there are many static site generators like Jekyll, notably: Gatsby, Hexo, Pelican, etc. and I'm planning to port my plugin to all those platforms
, they have a different language, for example, Jekyll uses Ruby while Pelican is written in Python, having them in one repo make it hard for testing and maintaining.

8. about linking, well GitLab isn't social media like GitHub, so I prefer linking to GitHub 😃.

**Comment by b-g** [comment]
Thanks @MahdiBaghbani!

1. ✅ 
2. Yes ... please add more examples
3. ✅ 
4. ✅ 
5. Basically our (and the users) expectation would be that the **entire** of OpenMoji is supported. I think also the name you've chosen implies that :) Could you use `data/openmoji.json` to somehow make that sure? As currently your plugin does not support everything within [extras-openmoji](https://openmoji.org/library/#group=extras-openmoji) and [extras-unicode](https://openmoji.org/library/#group=extras-unicode)
6. ✅  + Great!
7.  ✅
8. Will do once the plugin supports all of OpenMoji. Hope this is fine for your too! (Let me know)

PS. OpenMoji 12.1 is coming next week

**Comment by MahdiBaghbani** [comment]
Yeah I'm ok with that 8.
Should I wait for next week to see updated `data/openmoji.json` ? or it is ready by now?

**Comment by b-g** [comment]
@MahdiBaghbani `data/openmoji.json` reflects what is currently in OpenMoji and is kind of always "ready". I would strongly suggest to automate the process on your end to add all the extras to your plugin. You can wait or use `data/openmoji.json` of OpenMoji 12.0 ... either way in fine. Thanks!

**Comment by b-g** [comment]
@MahdiBaghbani OpenMoji 12.1 is out! :)

**Comment by MahdiBaghbani** [comment]
@b-g that's great! I'll start working on fully supporting all of the openmoji emojis.

**Comment by MahdiBaghbani** [comment]
Hi @b_g.
I think now everything is fine, all openmoji emojis are supported (version 12.1).

2. An example in README has been updated to show how it works.

5. A cheat code is available at
https://azadeh-afzar.gitlab.io/Web-Developmen/OpenMoji-Jekyll-Plugin
wit corresponding emoji images.

if you think there are still some problems remaining, tell me about them.

**Comment by b-g** [comment]
@MahdiBaghbani Many thanks! + Great! 🙏 Added it to the readme ... check https://github.com/hfg-gmuend/openmoji/commit/7de6275860695049f0f907cd78ff09755cb1812f

But there is a small bug which needs a fix: `schwäbisch gmünd fünfknopfturm` is wrong. Correctly transposed to ascii safe is the following `schwaebisch_gmuend_fuenfknopfturm`. Please fix for all German Umlauts. OK?

**Comment by b-g** [comment]
Also does the install command really need the apostrophes? `gem 'jekyll-openmoji'` vs `gem jekyll-openmoji`

**Comment by MahdiBaghbani** [comment]
@b_g thank you for the link.

 Yes the apostrophes are necessary, according to official Gemfile guide at 
https://bundler.io/v1.5/gemfile.html

Also, I saw you have added gem 'jekyll-openmoji' for installing this plugin. technically this script should be added to a Gemfile and then it will be installed by running `bundle install`, for installing the gem straight from the terminal you should type `gem install jekyll-openmoji`. I forgot to write about this in my installation guide at README, I'll update it soon.

the cheat code is heavy and big I need to clean it up soon,
and seems my python script wasn't set to UTF-8 so all German Umlauts are converted back to ASCII, I'll fix these cheat code problems in the next patches this week.

**Comment by b-g** [comment]
@MahdiBaghbani Thanks + fixed the readme to `gem install jekyll-openmoji`. Will close this issue now. It seems all is resolved. Re-open if you think different :) Please fix the German Umlauts. Many thanks!
