### ISSUE TITLE
Improving consistency with other platforms 12.2

### ISSUE THREAD

**Issue by carlinmack** [hfg-gmuend/openmoji#105]
_A continuation of #72_ 

## Faces
- [x] [confused face](https://emojipedia.org/confused-face/) No eyebrows, slightly down turned mouth - 8603bf6
- [x] [confounded face](https://emojipedia.org/confounded-face/) Crossed eyes and wavy mouth - #114 
- [ ]     [shocked face with exploding head](https://emojipedia.org/shocked-face-with-exploding-head/) looks like some sort of crown but should have a cloud of smoke emanating (we use this emoji as an example of line art on the contributions page)
- [ ] [face with look of triumph](https://emojipedia.org/face-with-look-of-triumph/) - complete redesign - There should be some steam coming out of nose 
- [ ]  [serious face with symbols covering mouth](https://emojipedia.org/serious-face-with-symbols-covering-mouth/) - redesign - There are no symbols covering the mouth and the emoji should potentially be red
- [ ] [loudly crying face](https://emojipedia.org/loudly-crying-face/) - eyes should be closed

## Other
- [x] [horse racing](https://emojipedia.org/horse-racing/)  The current emoji is suitable for "Horse Riding" but not so much racing, read [this tweet chain](https://twitter.com/jelenawoehr/status/1192242149510676481) for reference. I suggest making the back of the jockey flat and the feet higher up the horse - #111 
- [x] [mate](https://emojipedia.org/mate-drink/) I think that the top of this should be grey and the straw should have a grey stroke beneath the straw - 60742e4
- [x] [menorah](https://emojipedia.org/🕎/)  - [tweet](https://twitter.com/clapifyoulikeme/status/1233890658626260992) - Poor, should be 9 candles - e28d774
- [x] [dotted six pointed star](https://emojipedia.org/dotted-six-pointed-star/) and [star of david](https://emojipedia.org/star-of-david/)- the star should be the star of david which is explicitly two connected triangles on top of each other - 414fe7d
- [x] [falafel](https://emojipedia.org/🧆/) - [tweet](https://twitter.com/VinnieTesla/status/1188903133230981120) - other platforms have a plate of falafel - 779a371 by @kraasch 
- [ ] [pinching fingers](https://emojipedia.org/pinching-hand/)  Pinching fingers should be closer
- [ ] [oyster](https://emojipedia.org/oyster/) - redesign - I don't think this should be purple at all
- [ ] [small aeroplane](https://emojipedia.org/🛩/) - [tweet](https://twitter.com/riscfuture/status/1195840791903522816) - no cabin, looks like a drone
- [ ] [waffle](https://emojipedia.org/🧇/) - [tweet](https://twitter.com/Enkaybee/status/1198451928080027648) - add butter and syrup
- [ ] [japanese dolls](https://emojipedia.org/japanese-dolls/) - [blog post](http://mandel59.hateblo.jp/entry/2016/03/04/041437) - need to add scepter and fan, change skin colour to white
- [ ] [ringed planet](https://emojipedia.org/🪐/) - [tweet](https://twitter.com/physicsJ/status/1232664158769795072) - should add planetary bands, maybe adjust rotation to 26.7°

**Comment by b-g** [comment]
Many thanks for this! Yes ... more OpenMojis which could need some TLC :)

- [shocked face with exploding head](https://emojipedia.org/shocked-face-with-exploding-head/) yes could be more "exploding"
- [face with look of triumph](https://emojipedia.org/face-with-look-of-triumph/) - yes. Would rather consider it a bug.
- [serious face with symbols covering mouth](https://emojipedia.org/serious-face-with-symbols-covering-mouth/) - yes. Redesign!

- [pinching fingers](https://emojipedia.org/pinching-hand/) - yes. Pinching fingers should be closer and remaining fingers more like  fist.
- [horse racing](https://emojipedia.org/horse-racing/) - yes. More racing less riding.

cc @dnlutz

**Comment by carlinmack** [comment]
Thoughts on this for horse racing? 
![image](https://user-images.githubusercontent.com/6676843/72130723-57af7580-3348-11ea-9a3a-c8986dca1f5e.png)

**Comment by dnlutz** [comment]
hello @carlinmack now it really looks like a horse race! i also like that the figure hast lost weight ; ) just a small detail: maybe you can make the leg a little narrower towards the foot?

**Comment by carlinmack** [comment]
I've made a PR with the changes if you'd like to review #111

**Comment by kraasch** [comment]
Here is an alternative falafel design: https://github.com/kraasch/openmoji/blob/master/src/food-drink/food-prepared/1F9C6_falafel.svg

**Comment by carlinmack** [comment]
great! could you add a white circle for the background of the plate? rename it 1F9C6.svg and you can make a PR :)

**Comment by carlinmack** [comment]
oh also could you take out the .png file before you PR? we have a script that generates all the production PNGs

**Comment by carlinmack** [comment]
Closing this to replace with issue #143 for the next iteration
