### ISSUE TITLE
Android support through Whatsapp Stickers

### ISSUE THREAD

**Issue by carlinmack** [hfg-gmuend/openmoji#112]
This is a huge task with small reward but I think it's the easiest way to accommodate Android users (like me!). For example [Zouzoukwa](https://play.google.com/store/apps/details?id=apps.oplerou.zouzoukwa). Most urgent would be openmoji-extra

**Comment by b-g** [comment]
Well yes ... supporting Android and Whatsapp Stickers in general would be great! However already our [OpenMoji iOS app](https://github.com/hfg-gmuend/openmoji-ios) is a lot of effort.

**Comment by RockyTV** [comment]
What about Telegram stickers as well? Also, there's the Telegram clients that support emoji packs, maybe you could get in touch with them and request OpenMoji to be included?

**Comment by carlinmack** [comment]
Yes that would be great! probably would be best to do that after we release V13, we're over 1/3 of the way there :) #124

**Comment by inferno986return** [comment]
Already asked Unigram (the Windows 10 client) if it could be included as there several packs available already: https://github.com/UnigramDev/Unigram/issues/1392

I think outreach is important

**Comment by carlinmack** [comment]
Outreach is very important, however I only really have time now for improving the emojis so that we can put our strongest foot forward. After the release of OpenMoji 13.0 I'll start conversations with developers.

Another platform that hasn't been mentioned but I'd like to see support in is Signal

**Comment by FrayxRulez** [comment]
Working on adding them to Unigram right now... 😃

**Comment by FrayxRulez** [comment]
So, OpenMoji set is now available in Unigram via cloud update (Settings > Chat Settings > Emoji Set). 
However the bitmaps I found in the release page of this repository don't seem to be optimized for direct usage: many of them have too much padding and they look quite out of place (and too small)

**Comment by carlinmack** [comment]
@FrayxRulez Wow great work! we're doing a release a week today which should hopefully fix some of these issues 😁

**Comment by carlinmack** [comment]
Could you fill us in on what file type/resolution is used and what improvements we could make?

**Comment by FrayxRulez** [comment]
I am scaling down the biggest resolution you have to 64 and 18px. The best thing would be to actually fill the bitmaps with the emojis, I might try to do this programmatically when I have some spare time.

**Comment by carlinmack** [comment]
gallery of what OpenMojis look like in Unigram for reference
|       |       |   
|  ---  |  ---  | 
|  ![image](https://user-images.githubusercontent.com/6676843/82107330-c5075480-96f4-11ea-8c6d-baa28797d4e0.png)      | ![image](https://user-images.githubusercontent.com/6676843/82107346-ea945e00-96f4-11ea-8fb2-7425688d5218.png) |

![image](https://user-images.githubusercontent.com/6676843/82107385-30512680-96f5-11ea-89bb-c5ef0f59df17.png)

**Comment by FrayxRulez** [comment]
Yes, that’s the problem, all that padding makes most of the emojis look really small, but of course this doesn’t apply to all of them (by example flags are pretty good) and in any case I would like to avoid to increase the app in the size itself.

**Comment by carlinmack** [comment]
OpenMoji is the smallest package, why are other emoji packages allowed to increase the app size?

**Comment by carlinmack** [comment]
![unigram](https://user-images.githubusercontent.com/6676843/82123879-cfb00100-9769-11ea-9766-8c816ba370d5.png)
@b-g I don't think this is trivial, but I think that exporting the emoji PNGs with 50% less border would make them more legible, thoughts?

**Comment by b-g** [comment]
@carlinmack  I guess this should be a crazy effort ... we could just create a new helper script based on `helpers/export-emojipedia.sh`this is the line:

https://github.com/hfg-gmuend/openmoji/blob/8199c9db792b4aea9fa7026b02c1012720ca45e8/helpers/export-emojipedia.sh#L17

I guess the `-z` might do the trick.

**Comment by carlinmack** [comment]
yes -z might just do the trick, I'll experiment tomorrow

**Comment by vavrecan** [comment]
> We already have the emoji available in 72x72, is that too large?
> Also making them all the full size sounds like a good idea but has weird side effects. The faces are all the same size:
> ![image](https://user-images.githubusercontent.com/6676843/82088728-442e6580-96c0-11ea-8b17-c31188c01501.png)
> but when scaled to have equal max height/width would look like this
> ![1F917](https://user-images.githubusercontent.com/6676843/82089428-9c199c00-96c1-11ea-96e9-f5aa1c1adda6.png)

what about custom overrides that allows this?  
https://github.com/vavrecan/openmoji-mod

**Comment by MEibenst** [comment]
Hi

Are you still following the plan to create sticker packs for WhatsApp, Telegram and/or Signal?
Is anyone working on it right now?

**Comment by b-g** [comment]
Hi @MEibenst, nope nobody is working on WhatsApp, Telegram and/or Signal ... feel free to tackle it :)

**Comment by MEibenst** [comment]
I will give it a try. :-) But it will take some time, because my time for doing this is limited.

If there is no prioritization from you regarding app or category of emojis, I will probably start with Telegram. While I look at how it works on WhatsApp with the sticker apps. 

It seems like Signal doesn't have an update mechanism for stickers, so I'd probably do those packs last.

I will create a new repository and additionally keep you guys updated here.

**Comment by b-g** [comment]
Great! But please be aware we (the maintainers) will just be able to support on the Openmoji side ... and it will be a community extension. We simply have too much on our plate to maintain the core projects, the website and the iOS app. I hope you understand.

**Comment by MEibenst** [comment]
Sure, that's perfectly fine with me. To be honest, I never expected anything else.

I just stumbled across the issue and thought I could help. :)

**Comment by MEibenst** [comment]
Hi,

Sshort update. The first sticker pack for Telegram is ready. You can find it and all the others that will follow here: https://github.com/MEibenst/openmoji-sticker-sets/

**Comment by b-g** [comment]
Closing. See also https://github.com/hfg-gmuend/openmoji/#downloads--distribution-channels for stickers for Telegram and WhatsApp.
