### ISSUE TITLE
Science fiction rocket ship

### ISSUE THREAD

**Issue by kriskowal** [hfg-gmuend/openmoji#113]
At time of writing, the rocket ship emoji is represented by the American space shuttle. Many other emoji fonts use a depiction of an iconic 60's era science fiction rocket ship.

https://emojipedia.org/rocket/

I propose a depiction more in keeping with the prevailing trend.

Since I'll be needing this regardless for a game I'm writing (a roguelike about and using emoji), I've begun drafting a prototype, attached.

![1F680](https://user-images.githubusercontent.com/60294/72709215-4ec55d80-3b19-11ea-813c-35dfd3fc4fb5.png)

**Comment by b-g** [comment]
@kriskowal Many thanks for this + looks nice! 

I would propose to move the Space Shuttle to private use area and replace rocket 1F680 with it. 

Personally I would add to the discussion that I find a vertical rocket better and a science fiction rocket ship would always have some functional marks on the outer shell e.g. see Tin Tin Rocket Cover.

![220px-The_Adventures_of_Tintin_-_16_-_Destination_Moon](https://user-images.githubusercontent.com/480224/72710453-6cb9af00-3b67-11ea-804c-cbd43b95c19b.jpg)
 
cc @carlinmack is the master of consistency with other vendors :) What do you think?

**Comment by carlinmack** [comment]
+1 for science fiction rocket ship and move NASA space ship to openmoji-extra, love the design! Think it would be fun to test a checkboard colouring like above

**Comment by kriskowal** [comment]
![1F680-drafts](https://user-images.githubusercontent.com/60294/72750491-d8a11500-3b71-11ea-9a50-88adbbc85620.png)

**Comment by kriskowal** [comment]
I believe I'll be needing to reserve a number in the private use area, or stack my PR over a separate change that moves the space shuttle into the openmoji-extras before me. Please advise. I still have a bit of an adventure ahead of me, figuring out how to tease Inkscape into exporting this with XML attributes instead of CSS styles.

**Comment by carlinmack** [comment]
I need to write a proper guide how to do it, but if you `File -> Save As -> Save as type: -> Optimised SVG -> Save` and use these settings, you get pretty close to clean XML

![image](https://user-images.githubusercontent.com/6676843/72760224-1324a500-3ba6-11ea-911e-6a6cc8a8daeb.png)

**Comment by carlinmack** [comment]
Reserving a number in the private use area isn't a big deal, just use the next sequential number in the correct subcategory (travel-places for rocket). Also perform the steps in the other files section here: https://github.com/hfg-gmuend/openmoji/blob/master/CONTRIBUTING.md#hexcodes-for-extras-openmoji

**Comment by kriskowal** [comment]
I got an SVG that passes tests now. Thank you.

**Comment by carlinmack** [comment]
btw before you PR can you run `npm pretty-src-svg'? thanks!

I have no opinion on the best rocket ship, I'll leave that to the others

**Comment by kriskowal** [comment]
I looked into running it on a file in isolation, but I just ran generate.sh on the whole library and added only the files I intentionally changed with git. Truth be told, I'm more the software engineer than the graphic designer, and this seemed the expedient route.

**Comment by carlinmack** [comment]
Ah you do this from the root:

`node_modules/.bin/svgo src/activities/arts-crafts/1F3A8.svg --config helpers/beautify-svg.yml`

glad you figured it out though

**Comment by b-g** [comment]
Hi @kriskowal and @carlinmack, Sorry for the slow response but a combination of a bad cold and traveling kept me away from my computer.

Yes: A1 is the best version. 

Will look into the PR and the probably introduced issue of #119 (no worries, should be a big thing) today/tomorrow.

**Comment by kriskowal** [comment]
> Hi @kriskowal and @carlinmack, Sorry for the slow response but a combination of a bad cold and traveling kept me away from my computer.

*Alles gute.*
