### ISSUE TITLE
Move away from wiki to CONTRIBUTING.md

### ISSUE THREAD

**Issue by carlinmack** [hfg-gmuend/openmoji#116]
In this issue [openmoji-website/issues/57](https://github.com/hfg-gmuend/openmoji-website/issues/57) we suggest directing people to CONTRIBUTING.md. 

However there is information in the [wiki](https://github.com/hfg-gmuend/openmoji/wiki) that is not in CONTRIBUTING.md, such as the running the formatting on a single file.

I think that we should merge into CONTRIBUTING.md and close the wiki, thoughts?

Or maybe just move the last three headings?

**Comment by b-g** [comment]
Yes and no :) Yes everything what is useful for a "contributor" e.g. run individual test should be moved to CONTRIBUTING.md ... the rest is really internal notes e.g. how to release a new openmoji version should IMO stay there.

OK?

**Comment by carlinmack** [comment]
that's what I meant! thanks

**Comment by carlinmack** [comment]
For reference

https://github.com/hfg-gmuend/openmoji/wiki/Home/_compare/f0fe0dfae139c06ccc0c05b1f0987c8c1f5a2937...a0e6c2b5f5f7946713b1720f3ec76a33c832b582

https://github.com/hfg-gmuend/openmoji/commit/76fa25210640fc6ecdae66d666876f3b9afd5f79
