### ISSUE TITLE
Missing entries in data/openmoji.json

### ISSUE THREAD

**Issue by cyberalien** [hfg-gmuend/openmoji#119]
After this commit:
https://github.com/hfg-gmuend/openmoji/commit/aaac9eb80096c5f1569fc59d0bf04a31165af56e#diff-507b1e5a4014a34e33ffb7c0f1d4f3d3

over 20 icons are missing in data/openmoji.json:
```
e184
1f9d1-200d-1f9af
1f9d1-200d-1f9bc
1f9d1-200d-1f9bd
1f9d1-200d-1f33e
1f9d1-200d-1f373
1f9d1-200d-1f393
1f9d1-200d-1f3a4
1f9d1-200d-1f3a8
1f9d1-200d-1f3eb
1f9d1-200d-1f3ed
1f9d1-200d-1f4bb
1f9d1-200d-1f4bc
1f9d1-200d-1f527
1f9d1-200d-1f52c
1f9d1-200d-1f680
1f9d1-200d-1f692
1f9d1-200d-2695-fe0f
1f9d1-200d-2696-fe0f
1f9d1-200d-2708-fe0f
1f9d1-200d-1f9b0
1f9d1-200d-1f9b1
1f9d1-200d-1f9b2
1f9d1-200d-1f9b3
```

**Comment by kriskowal** [comment]
It is possible that rerunning the table generator will address this issue. I ran them with a fresh checkout and a fresh install of all apt-get and npm dependencies in a somewhat unusual environment: Windows Subsystem for Linux.

**Comment by b-g** [comment]
@cyberalien Many thanks for report and spotting it! Should be resolved with the latest commit. I've introduced also additional tests to ensure that we don't run into this situation again. Sorry!
