### ISSUE TITLE
Glitch in U+1F40E Horse svg

### ISSUE THREAD

**Issue by salty-horse** [hfg-gmuend/openmoji#12]
The bottom of the horse's jaw has two strokes intersecting and one of them "erases" part of the other.

See image.
![horse](https://user-images.githubusercontent.com/28355/50659631-e8b97700-0fa5-11e9-9c8e-7a8ed126b4f5.png)

**Comment by b-g** [comment]
Hi @salty-horse, 

many thanks for spotting this! 

We currently working with full steam on a v1.5 with lots of new, improved and fixed things. It seems we already fixed this glitch, see svg source file in dev branch ... will go officially online once v1.5 has been published. (ETA Feb 2019)

https://github.com/hfg-gmuend/openmoji/blob/v1.5/src/animals-nature/animal-mammal/1F40E.svg
