### ISSUE TITLE
The export-svg-font.js builder requires a build itself

### ISSUE THREAD

**Issue by fgaz** [hfg-gmuend/openmoji#122]
`helpers/export-svg-font.js` has some dependencies and requires to be built with npm, which is a problem for packagers since that means packaging openmoji _and_ the builder.
Would it be fine to replace it with a bash implementation (or keep both)?

I have one [here](https://github.com/NixOS/nixpkgs/pull/70177) as part of a packaging effort.

**Comment by b-g** [comment]
Hi @fgaz Many thanks for the interest! However I struggle to understand the problem. The script can also be run with `node helpers/export-svg-font.js` and just copies the svg files in preparation to be build with the SVGinOT Color Font Builder, see https://github.com/hfg-gmuend/openmoji/tree/master/font#generate-fonts.

**Comment by fgaz** [comment]
> The script can also be run with node helpers/export-svg-font.js

Not really. If I try that with a clean environment I get:

```
Error: Cannot find module 'glob'
```

The script needs `glob` et al. to work. This means that those libraries need to be packaged too, as packages (in most distributions) need to exactly specify all their inputs.

Reimplementing it in bash would reduce the dependencies to only bash and some core utilities (basename, uniq, ...).

**Comment by b-g** [comment]
I can't confirm this. Script runs fine via `node helpers/export-svg-font.js`. Also `glob` is defined in https://github.com/hfg-gmuend/openmoji/blob/master/package.json#L41

Please check:
- correct node version?
- does `npm i` install all devDependencies?

No bash script planned from our side. Sorry!

**Comment by fgaz** [comment]
> does `npm i` install all devDependencies?

it does, but that's the point: I'm packaging openmoji for NixOS, so I cannot run that command because it has undeclared inputs. I'd have to properly package all 287 dependencies, and while there are tools for that, having a dependency-less script makes things much easier and distro-friendly.

> No bash script planned from our side. Sorry!

:+1:

I like to upstream patches but keeping the bash implementation in the package is no problem.

**Comment by b-g** [comment]
I have to say that I don't understand the problem and the context, especially "undeclared inputs" and why you simply package openmoji without any dependencies ... like what you get if you install openmoji via `npm i openmoji`.

**Comment by fgaz** [comment]
Sorry, I realize i was too vague so here's the background:

> like what you get if you install openmoji via `npm i openmoji`

That seems like a precompiled release. In NixOS, like in most distros, packaging from source is strongly preferred, so that's why I'd like to build the font from the SVGs.

> undeclared inputs

In most distros' packaging systems, and especially NixOS', all dependencies and other inputs (environment variables etc) must be exactly specified in the distro's package descriptions themselves. Exactly means that either inputs are embedded the package description (env variables, patches..) or they have a fixed checksum (when they come from "outside").

For example I sepcified a specific revision of this repo together with its sha256 checksum as an input for the openmoji package. `scfbuild` is another input.

Running `npm i` as part of the build would fetch additional dependencies from the internet, which is not allowed for reproducibility reasons. That's what I meant as "undeclared inputs": the files fetched by npm are not specified in the nix package description.

So, all dependencies of `export-svg-font.js` would have to be listed together with their checksums.
This is doable: thare are tools that can convert `package-lock.json` files to nix package descriptions and they are used when packaging node applications.

Still, this solution requires checking in to the nixpkgs repo a huge generated nix file, which is a maintainance burden (updating the font would require regenerating the files) and a lot of noise, so I'd like to avoid it if possible, hence my bash reimplementation.

Upstreaming it would just have been a bonus, espacially for any other distro wanting to package this.
I understand not wanting scripts written in other languages in the repo though.

**Comment by b-g** [comment]
Many thanks for the explanation! I begin to understand ...

However I think it is out of scope for our project to support all this. I'm sorry! 

Also I understand why one want to compile/build everything from scratch e.g. to have max performance on specific hardware environments ... but still we are talking here about fonts, png and svg files. They won't look any different if you build them again :)

Hence I would recommend to simply wrap what you get with `npm install openmoji`, basically:

- color/svg/*.svg
- black/svg/*.svg
- font/OpenMoji-Color.ttf
- font/OpenMoji-Black.ttf

I would consider these files the "production" part of OpenMoji. Hope this helps. Will close the issue have nothing to add, please re-open if you want to continue the conversation.

Good luck with the package!
