### ISSUE TITLE
Chrome extension emoji picker

### ISSUE THREAD

**Issue by maciekgrzybek** [hfg-gmuend/openmoji#123]
I'm not sure if you are interested in this at all, but I've created an emoji picker based on OpenMoji library. Before I'll push into the wilderness, I wanted to show you how it looks like and maybe you'll have any comments, opinions etc? I'm open to any feedback :) 

So I'm attaching the compressed build file. Also, some info how to run an extension from local files
- https://superuser.com/questions/247651/how-does-one-install-an-extension-for-chrome-browser-from-the-local-file-system
- [openmoji-picker-chrome-extension.zip](https://github.com/hfg-gmuend/openmoji/files/4122114/openmoji-picker-chrome-extension.zip)

**Comment by b-g** [comment]
Hi @maciekgrzybek! Nice! Glad that the OpenMojis are of use for this! Here is how it looks on my end:

<img width="579" alt="Screen Shot 2020-01-28 at 17 18 23" src="https://user-images.githubusercontent.com/480224/73282663-455f8380-41f2-11ea-92c8-0dd87d3725cf.png">

Comments/questions:
- On my retina screen the emojis are blurry ... consider using svgs
- Title "emoji picker" is a bit generic :) Is there any unique feature I should be aware of?
- The "Copy" feature copies only hexcode to clipboard ... so if you paste back the emoji you get the ones in your system font ... so very mean question: Why not then use the system font emojis? What is your intention with the project :)

Many thanks for it!

**Comment by maciekgrzybek** [comment]
Hey thanks for comments :)
- I've tried using svgs but there's quite a lot of them, and it loads really slow, I could try using high res sprite instead
- I didn't have a better name for that :) looking forward for any suggestions :) no unique features, just a generic emoji picker :)
- I can control how the emojis going to look like in a different software, but I really like your library and I just thought it would be nice to use it instead of the Chrome one (OpenMoji looks much better). But if you don't want to Your project being connected to that picker, I can remove it and just use the native one

**Comment by maciekgrzybek** [comment]
Also I'm not really a designer so layout and UI might not be perfect

**Comment by b-g** [comment]
@maciekgrzybek No worries! :) + No, please feel free to use OpenMojis for your projects!! Just wanted to be sure that I understand your context.

> I've tried using svgs but there's quite a lot of them, and it loads really slow, I could try using high res sprite instead

Yes ... or generate retina png files, see script https://github.com/hfg-gmuend/openmoji/blob/master/helpers/export-png.sh#L13

> I didn't have a better name for that :) looking forward for any suggestions :) no unique features, just a generic emoji picker :)
>
> I can control how the emojis going to look like in a different software, but I really like your library and I just thought it would be nice to use it instead of the Chrome one (OpenMoji looks much better). 

Got you! Fine as it is :)

> But if you don't want to Your project being connected to that picker, I can remove it and just use the native one

No please use it. Let us know once it is published ... we might have soon a section with projects using OpenMojis.

Will close the issue have nothing to add, please re-open if you want to continue the conversation.

Good luck with the chrome extension!

**Comment by MahdiBaghbani** [comment]
Hi @b-g !
> we might have soon a section with projects using OpenMojis.

that would be great, because I have several new projects going on with OpenMoji, like using its SVG via CSS in the frontend development like how the font awesome did it.
