### ISSUE TITLE
Annotation error and few annotation conflicts in recent updates

### ISSUE THREAD

**Issue by cyberalien** [hfg-gmuend/openmoji#127]
There are few issues with annotations added to custom icons:

1. e323: annotation is "stethoscope " (extra space at the end)

2. Several custom icons and default icons have identical annotations:
- e319 (in extras-openmoji/healthcare) and 1f9e0 (in people-body/body-parts) have annotation "brain"
- 1fa7a (in objects/medical) has annotation "stethoscope" that would conflict with e323 that I've mentioned above
- e0c3 (in extras-openmoji/food-drink) and 1f968 (in food-drink/food-prepared) have annotation "pretzel"
- e104 (in extras-openmoji/interaction) and 1f4dc (in objects/book-paper) have annotation "scroll"
- e1c5 (in extras-openmoji/technology) and 1f401 (in animals-nature/animal-mammal) have annotation "mouse"
- e1d1 (in extras-openmoji/technology) and 2328 (in objects/computer) have annotation "keyboard"
- e269 (in extras-openmoji/ui-element) and 1f517 (in objects/tool) have annotation "link"

First issue (extra space) is an error, I'm not sure if second issue (duplicate names) is an error, but thought I'd mention it anyway.

**Comment by b-g** [comment]
Hi @cyberalien, many thanks for reporting! 

1. Removed e323, existing one was better and new one redundant. https://github.com/hfg-gmuend/openmoji/tree/4b7373e1e1e1ea34a0d2b2df596d5a7de1efd32c
2. This is fine. These are "alternatives". Unique identifier is the hexcode and not the name. Hope that works for you too.

Please reopen the issue if you would like to continue the conversation or if I missed something. Many thanks!
