### ISSUE TITLE
OpenMoji / Flatbread

### ISSUE THREAD

**Issue by lizbravob** [hfg-gmuend/openmoji#129]
Hi, I'm interested to collaborated making Openmoji. This is my first time doing icons, I was trying to make flatbread, what do you think?
![src:food-prepared:flatbread:1FAD3](https://user-images.githubusercontent.com/60933333/74458833-0cb5e000-4e69-11ea-897a-f8926cca7ec3.jpg)

**Comment by dnlutz** [comment]
welcome to the club ; ) the flatbread looks good, but does it have the right size? the clock and the smileys have a diameter of 46 px – so i would apply that size here as well.

… and the new flat flatbread should match the existing stuffed flatbread and burrito, they should all have the same color:
https://openmoji.org/library/#search=flatbread
https://openmoji.org/library/#search=burrito

When the design is done you can check the file with https://openmoji-tester.glitch.me/
and apply the correct unicode value (1FAD3).

Thank you for contributing! If you are looking for new challenges feel free to check other missing emoji here: https://github.com/hfg-gmuend/openmoji/issues/124

**Comment by carlinmack** [comment]
Do you mean that the existing stuffed flatbread should be yellow or that the existing burrito should be brown?

**Comment by dnlutz** [comment]
i would suggest we use our normal bread as a guideline
> #fcea2b (yellow) plus #f1b31c for the shadows
https://openmoji.org/library/#search=bread

**Comment by lizbravob** [comment]
Great, I will fix and I'm working in other missing emoji like piñata and tamale. About the color of Flatbread, in Venezuela and Colombia, there is yellow cornmeal, that's the reason why I had chosen the color.

**Comment by carlinmack** [comment]
continued in #134
