### ISSUE TITLE
Contributions by Liz Bravo

### ISSUE THREAD

**Issue by lizbravob** [hfg-gmuend/openmoji#138]
Hi, again.
I drew others missing openmoji.
#pickup
#olive
#worm 
#fly 
#disguisedface
#smilingfacewithtear

I wait for your feedback
Greetings ✌🏻 
[Openmoji_lizbravob.zip](https://github.com/hfg-gmuend/openmoji/files/4302766/Openmoji_lizbravob.zip)

**Comment by carlinmack** [comment]
😮 amazing! We're still to add your others but thanks for the work!

**Comment by carlinmack** [comment]
![image](https://user-images.githubusercontent.com/6676843/76155866-4b356800-60c0-11ea-944e-bf70377b3917.png)
perfect

![image](https://user-images.githubusercontent.com/6676843/76155918-f3e3c780-60c0-11ea-8d38-096361d795af.png)
perfect

![image](https://user-images.githubusercontent.com/6676843/76155914-d151ae80-60c0-11ea-82f9-fa7e5ee477f2.png)
perfect

![image](https://user-images.githubusercontent.com/6676843/76155916-e2022480-60c0-11ea-8fe3-a873a646a679.png)
pinging @b-g 

![image](https://user-images.githubusercontent.com/6676843/76155905-a8c9b480-60c0-11ea-8d8f-d580937826f5.png)
I think the wings and body should be rounder, 

![image](https://user-images.githubusercontent.com/6676843/76155880-728c3500-60c0-11ea-9e19-6910a9d7f1c0.png)
so cool


![image](https://user-images.githubusercontent.com/6676843/76155876-5a1c1a80-60c0-11ea-915f-161941aca4f8.png)
pinging @b-g

**Comment by b-g** [comment]
Hi @lizbravob! Mega! Very nice! Looks great in general! Just two comments:

- The olive looks quite flat (thought first it is an avocado), could you try to give it a shadow to make it look more rounded/3d? See styleguide https://openmoji.org/styleguide/
<img width="966" alt="Screenshot 2020-03-09 at 15 46 37" src="https://user-images.githubusercontent.com/480224/76225778-44703780-621d-11ea-8a96-a6b18c86fc4e.png">
- Fly is fine for me ... it might have a bit more details than the other OpenMoji insects (https://openmoji.org/library/#search=insect), so a bit less details might be better ... but up to you
- I think the worm should not be shaped like the letter S e.g. see the shape of the work of https://emojipedia.org/worm/. I personally like the one without the full outline better ... but up to you.

Could you look once more into it?

Would then add all you great contributions mid/end of the week ...

🙏👍

**Comment by carlinmack** [comment]
@b-gjust to let you know I'm going to add Bravo's emojis on the Emoji13 branch tonight :) I think it's best to keep them separated until emojibase updates

**Comment by carlinmack** [comment]
if there's going to be a release then sure :)

**Comment by carlinmack** [comment]
added Pickup, Disguised Face and Smiling with Tear here d348d2a71, will keep open for further work on the other emojis

**Comment by lizbravob** [comment]
Hola!!

Thank you for the feedback. I'll fix the others🤘🏻
Have a nice day!

**Comment by lizbravob** [comment]
I fix it! :)
[Openmoji_lizbravob.zip](https://github.com/hfg-gmuend/openmoji/files/4320807/Openmoji_lizbravob.zip)

**Comment by carlinmack** [comment]
![image](https://user-images.githubusercontent.com/6676843/76476560-bf318200-63d8-11ea-83d6-0f6c9dcd56d3.png)
great 

![image](https://user-images.githubusercontent.com/6676843/76476584-d40e1580-63d8-11ea-9a43-1de68ebd5fdb.png)
great

![image](https://user-images.githubusercontent.com/6676843/76476589-dbcdba00-63d8-11ea-9d7b-27f3aace9686.png)
I think this is now too round, go for this sort of silhouette: https://commons.wikimedia.org/wiki/File:Close-up_of_Chrysomya_(Old_World_blow_fly)_on_a_green_leaf.jpg? thanks :)

**Comment by carlinmack** [comment]
![image](https://user-images.githubusercontent.com/6676843/76477056-8d211f80-63da-11ea-8c6a-e0a899bae232.png)
nice, maybe shading on the wheels, pinging @b-g 

![image](https://user-images.githubusercontent.com/6676843/76477130-c5c0f900-63da-11ea-996e-263fa9641ea9.png)
perfect!

![image](https://user-images.githubusercontent.com/6676843/76477161-d2455180-63da-11ea-82c7-5f41338bf52c.png)
hmm... needs some work - doesn't look like the pieces connect, @b-g 

![image](https://user-images.githubusercontent.com/6676843/76477276-3405bb80-63db-11ea-9c26-6f25ba63af32.png)
good

![image](https://user-images.githubusercontent.com/6676843/76477286-42ec6e00-63db-11ea-8ee6-ab1917900f12.png)
great! please add white shape for the fill of the bristles

**Comment by b-g** [comment]
Hi @lizbravob, Wow!! Many thanks for the fixes and the new ones! 🙏

No much to add to @carlinmack feedback! To summarize:
- Olive ✅
- Worm ✅
- Fly, something in between the last two version in terms of roundness
- Roller Skaters ✅, fine for me ... would prefer as it is without any shading on the wheels
- Magic Wand, see https://openmoji.org/library/#emoji=1F387 for how to deal with the layers
- Nesting Dolls, does come through that is nested and a doll. Maybe try to add a face and make the upper part smaller in width to convey "nested". See also https://emojipedia.org/nesting-dolls/
- Toothbrush, please add white fill

Also this is dialog ... please feel free to disagree with us, we are happy to discuss things! :)

**Comment by b-g** [comment]
Hi @lizbravob! Hope you are staying healthy and sane in these wild times! This is just a quick heads up ... we are going to release OpenMoji v12.2 tomorrow. Hence if you want to have all your latest emojis shipped, then it would be good to have the revised ones soon :) If you have no time, no problem ... then it will go in the next release after. Both is fine.

**Comment by lizbravob** [comment]
Hi @b-g! Sorry for the delay, thank u for your comments, I hope I've improved the openmoji. If it needs more work I'm happy to correct.
Greetings, be safe!

[Openmoji_lizbravo.zip](https://github.com/hfg-gmuend/openmoji/files/4340993/Openmoji_lizbravo.zip)

**Comment by carlinmack** [comment]
![image](https://user-images.githubusercontent.com/6676843/76812844-950f0400-67cc-11ea-8cb5-6dbb5fb8031a.png)
looks great!

![image](https://user-images.githubusercontent.com/6676843/76812862-a22bf300-67cc-11ea-8e17-aea56931e2f5.png)
great!

![image](https://user-images.githubusercontent.com/6676843/76812879-ae17b500-67cc-11ea-83e1-7dc37f952f5f.png)
good!

![image](https://user-images.githubusercontent.com/6676843/76812941-d1426480-67cc-11ea-93db-8d687e72cbdd.png)
(deconstructed to show the line-supplement layer) great!

I'll add these all for the release tomorrow :)

**Comment by carlinmack** [comment]
magic wand doesn't render correctly in the new font :(
![image](https://user-images.githubusercontent.com/6676843/76860801-fcab6a80-6831-11ea-8d59-f91024dcc22e.png)

**Comment by b-g** [comment]
@lizbravob Many thanks + great! 🙏 I've just released everything (give the website 1h to update)

@carlinmack Yes the black font part is tricky ... and we are on it. But the magic wand should work in the colorfonts

**Comment by carlinmack** [comment]
yeah not that big of a deal, just wanted to let you know, congrats on the release, it's been a long time coming haha

**Comment by carlinmack** [comment]
https://openmoji.org/library/#author=Liz%20Bravo 😁

**Comment by lizbravob** [comment]
Awesome!!! 🥰 Thank u!!

**Comment by lizbravob** [comment]
Hi, I'm working in more openmoji because I'm in quarantine to covid-19 :(  a day, an openmoji jaja.

I submit all in 14 days or do you prefer to see one by one?

Greetings, BE SAFE!

**Comment by carlinmack** [comment]
you can submit every day, I'm also quarantined with not a lot to do, happy to review them :)

**Comment by lizbravob** [comment]
Great! :)
[Openmoji_LizBravo.zip](https://github.com/hfg-gmuend/openmoji/files/4366442/Openmoji_LizBravo.zip)

**Comment by carlinmack** [comment]
![image](https://user-images.githubusercontent.com/6676843/77262189-ad6a9d00-6c6a-11ea-830a-6869c3bc0d21.png)
* the trap should be a consistent brown colour
* the bar should be silver
* change the vertical bar that goes from the top to the cheese
![image](https://user-images.githubusercontent.com/6676843/77264801-85cb0300-6c71-11ea-830f-c6da871ae760.png)

more incoming...

**Comment by carlinmack** [comment]
btw could you make sure that the emojis are at least the size of the circle, we don't want the emojis to be too small!

**Comment by b-g** [comment]
Hi @lizbravob, many thanks for the nice new ones! Sorry for the slow feedback ... but busy dealing and juggling corona related issues on all ends. Anyway here's some additional feedback (after a meeting with @dnlutz):

- mouse trap, we think a flat one will be really difficult. Hence we would suggest to go rather in a 3d direction. It's fine to do exceptions if it really makes the emojis way better in terms of readability, see https://openmoji.org/styleguide/#perspective e.g. https://openmoji.org/library/#search=books, https://openmoji.org/library/#search=dice ... here is also a quick sketch 
![IMG_3649](https://user-images.githubusercontent.com/480224/77637826-8bb53280-6f56-11ea-9cbb-0c78f4f63375.jpeg)
- plunge: great!
- bucket: great, but yes it would be interesting to see a version with the handle above the bucket
- headstone: to be honest I first thought this is a proposal for a (knight) military helmet. Could you "ground" it better and hint e.g. ground, vegetation, soil ...? See https://emojipedia.org/headstone/
- placard: nice! But I think the two lines representing text could be improved to something a bit more regular, and both lines should be different. Now one could also read it as (water) "waves".

Very nice work!

**Comment by lizbravob** [comment]
Hi @b-g & @carlinmack I'm thankful for your feedback :) trying to improve openmoji during coronavirus! 
[Openmoji_lizbravob.zip](https://github.com/hfg-gmuend/openmoji/files/4390867/Openmoji_lizbravob.zip)

**Comment by carlinmack** [comment]
![bitmap](https://user-images.githubusercontent.com/6676843/77714451-6accfb80-6faf-11ea-81c2-7599e97008bc.png)
Can't believe I never thought of just making an SVG and exporting it lol!



1. I think I prefer this bucket
2. I like the boomarang
3. very pretty
4. I'd make the bottom end of the thread a bit longer 
5. much better!
6. I think the trap mechanism is too difficult to see, maybe all grey or switch to black?
7. I think both these mirrors 
8. are very funky
9.  alright
10. I prefer this one because I like how looks like the handwritten signs you see at protests

**Comment by b-g** [comment]
@lizbravob Wow!!

In addition to @carlinmack feedback let me add a few thoughts too:

- bucket: great! Much nicer with the handle on top! 
- boomarang: super!
- feather: super!
- sewing needle: super! (but yes why not make the string a bit longer)
- headstone: much better! But at a first glance there is still a bit of an helmet inside ... would try to remove the big dark rect ... and maybe then move the text up
![2020-03-27 at 13 49](https://user-images.githubusercontent.com/480224/77757702-fedfa700-7031-11ea-885f-640ad6ec28bf.jpg)
- mouse trap: this is a hard one. Feels more readable in pseudo 3d now. Could you try once more e.g.: Change the mechanism to black lines only ... as you will have a lot of lines then ... you could try to consolidate the parallel lines of the box to a single one e.g. just the ones which define the very outside of the shape ... like you did with the outlines of the Worm OpenMoji
- mirror: nice! yellow one! Right blue one resembles a turtle :)
- placard: nice! Right one ... but still the handwritten lines are very "italic" ... a bit more "regular" might be even better.

Note to self: We should also add the new and complete ones to Github soon!

**Comment by lizbravob** [comment]
Hi! I'm not good 3d sketching jaja but one more chance :)
[Openmoji_lizbravob.zip](https://github.com/hfg-gmuend/openmoji/files/4397666/Openmoji_lizbravob.zip)

nice weekend 🤘🏻🚀

**Comment by carlinmack** [comment]
![bitmap](https://user-images.githubusercontent.com/6676843/77836872-62e89500-7130-11ea-84a0-1a4a44325729.png)
I think all are good and I prefer the right plant and screwdriver

I would say that I'd prefer a line below the headstone like this to imply a date or quote (note I also made it a bit larger)
![image](https://user-images.githubusercontent.com/6676843/77836968-a55ea180-7131-11ea-97c7-d8dd9f3ba9ab.png)

**Comment by b-g** [comment]
Hi @lizbravob cc @carlinmack, Many thanks for this!! Comments:

- plant: I would prefer left
- screwdriver: I would prefer right
- headstone: Yes even better with Carlin's edits
- everything else looks good for me! :) 

@lizbravob If you agree we could add it to OpenMoji ... OK? 

(If so @carlinmack can you provide or add your headstone edit?)

**Comment by carlinmack** [comment]
I would say I strongly prefer the plant on the right. If you look up house plants you see that plants have more and denser leaves than the design on the left.
![image](https://user-images.githubusercontent.com/6676843/78323182-1097e180-753f-11ea-8ffb-d0b84ccfa922.png)

The plant on the left is more like a scaled up version of a plant sprout, which doesn't really make sense to represent a house plant 
![image](https://user-images.githubusercontent.com/6676843/78323234-36bd8180-753f-11ea-8c7b-b3407006a720.png)

**Comment by b-g** [comment]
Hi @lizbravob cc @carlinmack!

> I would say I strongly prefer the plant on the right.

Fair enough. Please decide on your own. Maybe we can keep both and move the non-official one (on the left) to extras-openmoji?

Also if you go for the "right" plant ... please beautify the lines ... currently there are too much black lines coming together.

![2020-04-03 at 09 16](https://user-images.githubusercontent.com/480224/78334567-444d2880-758c-11ea-8f88-929bdc0f299b.png)

**Comment by lizbravob** [comment]
Hi @carlinmack & @b-g 

Sorry to be late.
I improved the house plant emoji based on the referents, what you think?
and I added one more

Nice weekend :)
[openmoji_lizbravob.zip](https://github.com/hfg-gmuend/openmoji/files/4464913/openmoji_lizbravob.zip)

**Comment by carlinmack** [comment]
![three](https://user-images.githubusercontent.com/6676843/79050138-08ead380-7bf6-11ea-8aaa-23ee189fe4c6.png)
I prefer right hook and think that the plant is good

**Comment by b-g** [comment]
+1! Nice plant and I also liken the grey hook better! Great!

**Comment by lizbravob** [comment]
Hi 👋 
I have been worked in more openmoji.

[openmoji_lizbravob.zip](https://github.com/hfg-gmuend/openmoji/files/4699005/openmoji_lizbravob.zip)


Nice weekend :)

**Comment by dnlutz** [comment]
1F9CB Bubble Tea
O.k. … I first had to google what the black dots actually are ; ) What about reducing the number of pearls and placing them in a more "organic / random" ways?
The cup looks quite edgy, maybe you could round off the bottom a little bit? The straw with a bend?

1FA9F Window
I got it wrong, it seemed to be a glass door (sorry ; )
I would try a more simple design, maybe like the one from twitter: https://emojipedia.org/window/
I like the two white lines as reflection, but i think it will be better if it is more extensive. There is a good example in our styleguide (which is not online yet) > check out the smartphone at the botton. Would that be an option?
[guideline_shadow.pdf](https://github.com/hfg-gmuend/openmoji/files/4705363/guideline_shadow.pdf)

1FA97 Accordion
Beautiful! The only thing I would change around here to simplify it a little bit: two or three segments less in the middle?

1FAD1 Bell pepper
Here I would pull the shadow all the way up to cover the whole right third (like the skull in the guideline example above.

1FAD5 Fondue
The pot maybe a bit higher? … and you could take a skewer out and let some cheese run down to make it clearer ; )

1FAD6 Teapot
Nice! Maybe a bit less traditional and [more geometric](https://images.app.goo.gl/JonYHuxRCp1FzWMb6)?

Overall: great work, thank you very much!
Have a nice weekend (I hope you also have a bank holiday on Monday ; )

**Comment by carlinmack** [comment]
I much prefer this as a more geometric teapot design https://commons.wikimedia.org/wiki/File:Tea_pot,_Downpatrick,_September_2010.JPG however I do like the traditional version you originally used

**Comment by carlinmack** [comment]
![image](https://user-images.githubusercontent.com/6676843/83467345-a7055800-a447-11ea-936c-574ef2ac5e7a.png)
I think this is an improvement

**Comment by b-g** [comment]
Hi @lizbravob, Hope this message finds you all well! We have the next OpenMoji release coming up (before we go into a long summer break)! Any chance to get your open ones in the enxt days/weeks? Sorry to bother :)

**Comment by lizbravob** [comment]
Hi @b-g sorry, I forgot to submit the openmoji, but they are here with the corrections :) thanks for the feedback @dnlutz  🚀
If there any correction, I'll be pending. 

[Openmoji_lizbravob.zip](https://github.com/hfg-gmuend/openmoji/files/4951170/Openmoji_lizbravob.zip)

**Comment by b-g** [comment]
Hi @lizbravob, great + many thanks! Will add them all asap!

Only comment: I don't fully get the sign on the coin 1FA99? Would a "1" or/and a silhouette of a person not be more universal? See https://emojipedia.org/coin/

![2020-07-21 at 08 42](https://user-images.githubusercontent.com/480224/88021631-28b36100-cb2e-11ea-8ac7-5c4e31f6048e.png)

**Comment by lizbravob** [comment]
Sure, like this?

[1FA99.zip](https://github.com/hfg-gmuend/openmoji/files/4953403/1FA99.zip)

**Comment by b-g** [comment]
Great + 🙏! Added all of them to the library with the latest commit.

**Comment by lizbravob** [comment]
Hi, I was working on the latest openmoji v13 while you were off, hope it works fine, enjoy doing.

I have a doubt respect the person color if I have to make a different openmoji with each skin tone & I don't know which code corresponds. Well, I'll wait for your comments.

Have a good weekend.
Greetings
[openmoji_lizbravob.zip](https://github.com/hfg-gmuend/openmoji/files/5286109/openmoji_lizbravob.zip)

**Comment by carlinmack** [comment]
Wow these are all great, thanks!

![image](https://user-images.githubusercontent.com/6676843/94338294-171f8700-ffbf-11ea-9fc4-a215a5e0a704.png)

We'll add them in October :)

**Comment by dnlutz** [comment]
very nice work, thank you!
i especially like the mammoth, the bison and the seal!

here are my suggestions:
1f9a4: what about simplifying the wings?
1f9ab: the beaver looks a bit anxious. what about making it a bit more upright? … and it should be well distinguishable from an ordinary squirrel.
1F977: i would rather design the ninja like a person and not like a smiley (like the [others](https://emojipedia.org/ninja/))
1faa2: very nice knotted ; )
1faa8: maybe it is a little bit too big? and could yo u please try to simplify it a little bit? (all our mountains are a bit tool complicated by the way)

**Comment by lizbravob** [comment]
Hi, @dnlutz Thanks for your feedback.

I'll give them another spin regarding your suggestions 👍

**Comment by lizbravob** [comment]
Holaa 👋
I remade some openmoji :) 

[openmojii_lizbravob.zip](https://github.com/hfg-gmuend/openmoji/files/5343947/openmojii_lizbravob.zip)

Grettings

**Comment by carlinmack** [comment]
![image](https://user-images.githubusercontent.com/6676843/95390376-47bac700-08c3-11eb-96b6-0dcc5191ab26.png)

all great! you are a star 🌟

**Comment by dnlutz** [comment]
yes, looks great!

**Comment by b-g** [comment]
Hi @lizbravob Wow! Mega nice! Thank you so much!

**Comment by carlinmack** [comment]
alright, I'm adding them all today 💪

**Comment by lizbravob** [comment]
Awesome!! You Rock 🤘🏻🔥

**Comment by carlinmack** [comment]
I think we're missing two actually that I didn't realise and list previously, man with veil and woman in tuxedo

**Comment by b-g** [comment]
@lizbravob could you also design the remaining last two ones (man with veil and woman in tuxedo)?

**Comment by lizbravob** [comment]
Hi, @b-g sure!

What do you think about this? can it work?
[missing_openmoji.zip](https://github.com/hfg-gmuend/openmoji/files/5465107/missing_openmoji.zip)

I don't know the hexcode :(

Greetings

**Comment by carlinmack** [comment]
![image](https://user-images.githubusercontent.com/6676843/97706604-56446a80-1a8c-11eb-9af4-a9a829abfc89.png)
looks great! I'll add it
