### ISSUE TITLE
using rsvg-convert

### ISSUE THREAD

**Issue by carlinmack** [hfg-gmuend/openmoji#139]
I tried to use `npm run generate` but upon getting to the `generate-png.sh` stuff it tried to run `rsvg-convert` on every file which created thousands of errors. Can you add these lines to the start of `export-png.sh`?

```Shell
if ! command -v rsvg-convert; then
    echo "You should install rsvg-convert with:"
    echo ""
    echo "<INSERT HOW TO INSTALL rsvg-convert>"
    echo ""
    exit 1
fi
```

I tried to install it but the documentation is limited

**Comment by carlinmack** [comment]
(tried to export any files to help fix `master` but was very unsuccessful, did this for all of the exported svgs 🤷‍♂️)
![image](https://user-images.githubusercontent.com/6676843/76483962-cfecf280-63ee-11ea-82b2-0034bffe5ea1.png)
this

**Comment by b-g** [comment]
Hi @carlinmack, Thanks will have a look and generate the files ... and I've updated the documentation.

However I'm not sure whether I want to have these check if installed lines in **every** bash script. Could we simply agree to enhance the docs?

see https://github.com/hfg-gmuend/openmoji/wiki and https://github.com/hfg-gmuend/openmoji/blob/master/CONTRIBUTING.md#developer-setup

**Comment by b-g** [comment]
... And `<g id="skin"/>` is IMO fine and valid SVG. No need to change there anything :)

**Comment by carlinmack** [comment]
I'm not saying in every file, this is the only one I've had a problem with and it's being called in a loop against thousands of files. I'll check later if I missed something in the documentation.

and I know that's valid XML, however the red in that picture means that it's being removed and the closing tag is being added. This means all of the files were being rewritten in more verbose syntax :( not sure how or why

**Comment by b-g** [comment]
OK. Exported `npm run generate` and tested `npm test` without problems this morning. Can't replicate the issue on my end.

**Comment by carlinmack** [comment]
thanks for adding the information!
