### ISSUE TITLE
Improving design of emoji

### ISSUE THREAD

**Issue by carlinmack** [hfg-gmuend/openmoji#142]
_Continuation from #106_ 

## Face emojis with hands 
We have 5 fingers in these emoji [Face With Finger Covering Closed Lips](https://emojipedia.org/face-with-finger-covering-closed-lips/) and [Thinking Face](https://emojipedia.org/thinking-face/) and I think we should have 5 fingers in these emoji too
- [x]     4 fingers - [smiling face with smiling eyes and hand covering mouth](https://emojipedia.org/smiling-face-with-smiling-eyes-and-hand-covering-mouth/)
- [x]     4 fingers - [Yawning Face](https://emojipedia.org/yawning-face/)
- [x]     4 fingers - [Hugging Face]( https://emojipedia.org/hugging-face/) Also hands are too low
- b2cbf2ccc3097b7a67a7482eb469dcc855405694 by @nicdiac

## Animals
- [x] [llama](https://emojipedia.org/🦙/) - neck should be thicker - 7b825807
- [x] [raccoon](https://emojipedia.org/🦝/) - [tweet](https://twitter.com/formidabelle/status/1218732752637325317) - change tail to be bushier and add white to the face
- [x] [bee](https://emojipedia.org/🐝/) - [tweet 1](https://twitter.com/molleindustria/status/1204785455666991105) [tweet 2](https://twitter.com/TyrantOverlord/status/1180168261067067393) - looks like an angel, not anatomically similar to a bee
- [x] [sloth](https://emojipedia.org/🦥/) - Poor
- [x] [monkey](https://emojipedia.org/🐒) - back left leg should be defined in shape
- [x] [hippopatamus](https://emojipedia.org/hippopotamus/) - too simple, mouth should be bigger
- [x] [kangaroo](https://emojipedia.org/kangaroo/) - Kangaroo legs don't look like that 
- [x] [skunk](https://emojipedia.org/skunk/) - the body is so short! this is an angry sloth

## Food
- [x] [tomato](https://emojipedia.org/🍅/) - uses the darker green for the leaves instead of the lighter green
- [x] [grapes](https://emojipedia.org/🍇/) - uses the dark variation of purple instead of the light version and uses the light version for shading instead of the other way around
- [x] [strawberry](https://emojipedia.org/strawberry/) - the leaves should be flat, looks like a radish
- [x] [red apple](https://emojipedia.org/🍎/) - The borders close all the way (no open contour, see green apple for a better model) and in addition they use light gray to add shine to the apple. This is an added detail that none of the other fruit have and I think goes away from the goals. In addition, the placing of the stem hole makes it so the apple has a 3d perspective instead of being flat like the style guide says (And like the green apple does well)
- [x] [tangerine](https://emojipedia.org/🍊/) - uses a 3d perspective for the stem instead of a flat one
- [x] [cucumber](https://emojipedia.org/🥒/) - could be better. It's much too curvy and round for a cucumber and it looks more like a germ

new food issues
- [x] [mushroom](https://emojipedia.org/🍄/) - while our design is iconic and consistent, it would be nice to have an edible mushroom design (maybe button mushroom?)
- [x] [oyster](https://emojipedia.org/oyster/) - redesign - I don't think this should be purple at all
- [x] [waffle](https://emojipedia.org/🧇/) - [tweet](https://twitter.com/Enkaybee/status/1198451928080027648) - add butter and syrup
- [x] [custard](https://emojipedia.org/custard/) - looks like a cake, not a creme caramel

## Others
- [x] [classical building](https://emojipedia.org/🏛/) - [tweet](https://twitter.com/GettyMuseum/status/1233569422947733504) - Very Poor, should have 4 columns, should be more structural (?) - 250a3d6
- [x] [hot face](https://emojipedia.org/🥵/) - tongue is too high - 8febf94
- [x] [drooling face](https://emojipedia.org/🤤/) - extra stroke on drool - ae3215216
- [x] [cross mark](https://emojipedia.org/cross-mark/) - should be very symmetrical - d09ffe2c9
- [x] [infinity](https://emojipedia.org/infinity/) - do the intersecting lines contour
- [x] [lab coat](https://emojipedia.org/🥼) - should be symmetrical
- [x] [mens room](https://emojipedia.org/🚹/)  and [womens room](https://emojipedia.org/🚺/) - should be symmetrical- [x] [teddy bear](https://emojipedia.org/🧸/) - [tweet](https://twitter.com/watery_day/status/1194369208244523008) - Poor - not cute enough :(
- [x] [kimono](https://emojipedia.org/👘/) - [tweet](https://twitter.com/hellogeri/status/1233782147095420929) - Very Poor
- [x] [dagger](https://emojipedia.org/🗡/) - [tweet](https://twitter.com/caturnsrings/status/1229643177105199104) - change way handle connects to hilt
- [x] [cactus](https://emojipedia.org/🌵/) - [tweet](https://twitter.com/kammysayshi/status/1226070918922936326) -  arms should be the same colour, have some spines
- [x] [train car](https://emojipedia.org/🚃/) - [tweet](https://twitter.com/MaartjeME/status/1234076348999766016) - Poor - hide the wheels
- [x] [amphora](https://emojipedia.org/🏺/) - [tweet](https://twitter.com/GettyMuseum/status/1233224723246379008) - Very Poor, thicker handles, design should be geometric, not block shapes
- [x] [bowl with spoon](https://emojipedia.org/🍜/) - [tweet](https://twitter.com/jonrohan/status/1233893776222875650) - Very Poor - Bowl should at least have a flat base, curved spoon would be a plus 
- [x] [guardsman](https://emojipedia.org/💂‍♀️/) - [tweet](https://twitter.com/NAM_London/status/1233818665398788096) - Very Poor - hat should be domed among a lot of other adjustments
- [x] [book pile](https://emojipedia.org/📚/) - [tweet](https://twitter.com/book_historia/status/1233511440561999872) - Very Poor - too simple, don't look like real books, should show edge of pages
- [x] [moyai - easter island head](https://emojipedia.org/🗿/) - [tweet](https://twitter.com/RapanuiPioneers/status/1233084124161826817) - Very Poor, see source for criticism
- [x] [microscope](https://emojipedia.org/🔬/) - [tweet](https://twitter.com/samezrael/status/1236563049676288000) - [tweet](https://twitter.com/samezrael/status/1236563049676288000) - Poor, see tweet
- [x] [mosque](https://emojipedia.org/🕌/) - [tweet](https://twitter.com/japhettaula/status/1236588976321908737) - should be one structure
- [x] [lady beetle](https://emojipedia.org/lady-beetle/) - fix head colour
- [x] [mosquito](https://emojipedia.org/mosquito/) - make larger
- [x] [bug](https://emojipedia.org/bug/) - base off of an actual caterpillar
- [x] [old man](https://emojipedia.org/👴/) - hair should be improved, maybe have male pattern baldness
- [ ] [ok hand sign](https://emojipedia.org/ok-hand-sign/) This and Pinching Hand above look like they have webbed fingers when displayed on a dark background. This will require a lot of thought and discussion to fix - #86

**Comment by nicdiac** [comment]
Hi! I leave here the corrections on the 4 finger ones. I also do some sutil corrections on the ones with already 5 fingers, like a hand to low and excessively big on 1F914  or a little unnatural pose on 1F92B (Although I'm not sure about this one changes, I leave it up to you)

[Uploading #142.zip…]()

Leave me your thougts!

**Comment by nicdiac** [comment]
Hi! I leave here the corrections on the 4 finger ones. I also do some sutil corrections on the ones with already 5 fingers, like a hand to low and excessively big on 1F914 or a little unnatural pose on 1F92B (Although I'm not sure about this last one changes, I leave it up to you)

[Hi here!](https://github.com/hfg-gmuend/openmoji/files/4672363/142.zip)

Leave me your thougts!

**Comment by carlinmack** [comment]
yes great stuff! I much prefer v2, we don't like unnecessary anchor points :) I also like what you've done with the unnatural poses. 

for reference:

![image](https://user-images.githubusercontent.com/6676843/82741280-9bff4900-9d1e-11ea-94c3-2676577f616d.png)


watch out for little imperfections like this though, 
![image](https://user-images.githubusercontent.com/6676843/82741151-40808b80-9d1d-11ea-81b3-2c7f51d71f2e.png)
![image](https://user-images.githubusercontent.com/6676843/82741152-41b1b880-9d1d-11ea-8897-f785663d881c.png)
it should be snapped to the smooth node on the left finger
![image](https://user-images.githubusercontent.com/6676843/82741153-42e2e580-9d1d-11ea-8de7-44e834652608.png)

**Comment by carlinmack** [comment]
@nicdiac can you make sure you export your files following these instructions? https://openmoji.org/styleguide/#file_export it seems there's CSS attributes in your SVGs

**Comment by b-g** [comment]
@dnlutz Do you want to add anything in terms of curve quality or OpenMoji hands and fingers?

**Comment by dnlutz** [comment]
Sorry for being late to the party AND it's just a sketch … but I would be strongly in favor of going in the opposite direction. The more fingers, the more tiny fragmented elements we get. The interior spaces become too thin and don't look good. 

I don't think we need the fingers here at all – the main thing is to recognize the hands. What do you think? Would that be a direction you could go?

**Comment by dnlutz** [comment]
sorry, i did not want to close this issue but add an image … github 
<img width="970" alt="hands_faces_01" src="https://user-images.githubusercontent.com/38292227/82821441-6c7a4900-9ea4-11ea-8609-a179c4ea5894.png">
😭😭😭

**Comment by nicdiac** [comment]
I dont know if it is an oversimplification. But in the other hand I think thant otherwise there are a lot of useless lines. In any case I would leave it with five fingers, the difference is subtle but it looks, an it would differs much of the other emoji lines.

![Mesa de trabajo 1](https://user-images.githubusercontent.com/65752952/82827384-4f824d80-9e85-11ea-9858-03d64149eb07.jpg)
![2](https://user-images.githubusercontent.com/65752952/82827387-501ae400-9e85-11ea-84f8-34f372b242f7.jpg)

**Comment by carlinmack** [comment]
If we're representing fingers at all it should be five, however I think we should hint at them like 
![image](https://user-images.githubusercontent.com/6676843/82850833-d9eda000-9ecb-11ea-87bc-d0cde76114d5.png)

**Comment by nicdiac** [comment]
I leave those here with that modifications
![1F92B@150x-100](https://user-images.githubusercontent.com/65752952/82927543-3fd33980-9f57-11ea-9239-c2e4483c2b23.jpg) ![1F92D@150x-100](https://user-images.githubusercontent.com/65752952/82927555-42359380-9f57-11ea-8517-b6602f09eb79.jpg) ![1F914@150x-100](https://user-images.githubusercontent.com/65752952/82927557-42ce2a00-9f57-11ea-85ba-5a42fcb424f9.jpg) ![1F917@150x-100](https://user-images.githubusercontent.com/65752952/82927558-42ce2a00-9f57-11ea-82b5-8d67bbe915c9.jpg) ![1F971@150x-100](https://user-images.githubusercontent.com/65752952/82927560-4366c080-9f57-11ea-8a86-1db41aa86cef.jpg)

I have to polish the anchor points, but to give you an impression

**Comment by nicdiac** [comment]
Here i leave the ones with those modifications.

[2. less lines.zip](https://github.com/hfg-gmuend/openmoji/files/4690774/2.less.lines.zip)

I also been working on the racoon one with the modifications. I still hardly see a racoon there, the shape of the body seems a lot like a lemur, so I do a reversion of it. What you think?

Original / Modified / Reversion

![1F99D ORG](https://user-images.githubusercontent.com/65752952/83055117-c9533c00-a029-11ea-8dc6-ac0c7437da2b.jpg) ![1F99D MOD](https://user-images.githubusercontent.com/65752952/83055126-ceb08680-a029-11ea-8d52-e1211be5bfb6.jpg) ![1F99D REV](https://user-images.githubusercontent.com/65752952/83055133-d1ab7700-a029-11ea-8321-05a9dc300607.jpg)

**Comment by carlinmack** [comment]
The arch of the back is very different to what raccoons actually look like, but it's a lot better! See some of these from wikimedia commons for reference

![Untitled](https://user-images.githubusercontent.com/6676843/83057821-6eb7e100-a025-11ea-8f68-8c3176434049.jpg)

**Comment by dnlutz** [comment]
I prefer the modified version in the middle. The reversion on the right is beautiful but it has too many details IMO. That's a problem we have with some other animals – they should be recognizable but not too realistic / detailed.

**Comment by nicdiac** [comment]
I leave the animals here with the modifications made. 

From the raccoon I lifted his back a little more arched at the end without getting lost in the realism.
![racoon](https://user-images.githubusercontent.com/65752952/83275220-42c36980-a1a5-11ea-92ad-e59f6a0d470e.jpg)

Of the bee and the sloth I leave several options, although of the sloth I opt for the last one, I believe that the problem was in the colors and in the form of the face, and of the bee those that involve the black color, the wings I would leave them equal, they are quite original. 

![beesloth](https://user-images.githubusercontent.com/65752952/83275260-4f47c200-a1a5-11ea-8de7-1c40d6722206.png)

The hippopotamus, the kangaroo and the monkey are well solved with the subtle modifications made. I focus on get clear the idea of the animal in all.

![kanghippo](https://user-images.githubusercontent.com/65752952/83275407-7d2d0680-a1a5-11ea-8963-1a4f3c4adfb8.jpg)

The skunk I modified completely without trying to get lost in so many lines.

![shunk](https://user-images.githubusercontent.com/65752952/83275446-874f0500-a1a5-11ea-96a0-88b3e3ac9b19.jpg)

I am waiting for your thoughts to send the final deliverables :) I also leave the svg if you want to try any mod. 

[sketch.zip](https://github.com/hfg-gmuend/openmoji/files/4702612/sketch.zip)

**Comment by carlinmack** [comment]
### raccoon

I think both options suffer from the large dip at the neck, have a look at the cat emoji for how you can do a continuous line and keep the ear

### bee

I'd prefer sometihng like this (including legs)
https://commons.wikimedia.org/wiki/File:Bombus_impatiens_queen.jpg

### sloth

I'd say third but I think the head shouldn't be a circle and should be more accurate

### monkey

great

### hippo

better but I dislike all of the leg options. have a look at what they look like, maybe look at our llama emoji for reference.

### kangaroo

I still really dislike this. I think it would be easier to redesign from scratch hahah like kangaroos have knees - how could that ever jump

### "shunk" :P

yes this is great!!I'd go with the last one, with a white fill in the `<g  id='color'>` layer

**Comment by dnlutz** [comment]
I agree with @carlinmack 
The only way to improve Hippo and Kangaroo is to rework them from scratch ; )
But the others got really much better, I especially like the new skunk!

**Comment by carlinmack** [comment]
going back to the hands for a second, I think this is preferable to your design could either of you send me the change?
![image](https://user-images.githubusercontent.com/6676843/83466909-7ec92980-a446-11ea-8691-a0af72e77d91.png)

**Comment by nicdiac** [comment]
Me too, but dont follow the line of the 'no finger guys' 😂, thats why i rejected. I leave it here.

[1F92B.zip](https://github.com/hfg-gmuend/openmoji/files/4714883/1F92B.zip)

In other news, i remade the raccoon. With this option the dip in the neck disappear. What you think?

![Mesa de trabajo 4PNG](https://user-images.githubusercontent.com/65752952/83482428-a6d08100-a476-11ea-9154-e2b9066d158d.jpg)

**Comment by nicdiac** [comment]
Here i add the bee based on the one you said with some little variations, Im between 2 and 4

![Mesa de trabajo 2PNG](https://user-images.githubusercontent.com/65752952/83835303-cf4eba00-a6c6-11ea-8488-54f77c55cd61.jpg)

**Comment by carlinmack** [comment]
all of our insects are from a top down or side view so 4 and 5 are disqualified

as for the others:

* the back wing should be partially hidden by the body - right now it looks like both wings are stuck on to one side of the body
* it would nice to hint at the segmentation of the body a bit more
* bees have 6 legs but that may clutter the design too much

**Comment by carlinmack** [comment]
I'd just like to reiterate how important it is to follow the correct exporting rules
> can you make sure you export your files following these instructions? https://openmoji.org/styleguide/#file_export it seems there's CSS attributes in your SVGs

makes it a lot easier on my end 😀

**Comment by nicdiac** [comment]
Here are the two. 

On **the bee** I made the modification on the wing to be backward, the legs and the segmentation I dont thinks is the best to do, it makes it a lot more realistic, and more legs I tried before and does not work. 

Let your thoughs on **the raccoon** one, I remade it with a side view, like all the animal line but with a more raccoon like profile and curves on the back.

![Mesa de trabajo 3](https://user-images.githubusercontent.com/65752952/84547971-f9ae0200-acda-11ea-8761-742f5005f3d1.jpg)

**Comment by carlinmack** [comment]
I really like that racoon!! perfect

and fair enought with the bee, it's a huge improvement already!

**Comment by nicdiac** [comment]
I've seen it dificult to modify the head of de sloth, and also hardly recognizible besides the originality of the concept when I focus on a real sloth pic. Again seems like a monkey like animal. I've tried a diferent aproach, with more realistic on the curves.

![Mesa de trabajo 4](https://user-images.githubusercontent.com/65752952/85212740-14602680-b32c-11ea-80e7-3088366adb1a.jpg)

**Comment by carlinmack** [comment]
great!

**Comment by carlinmack** [comment]
Could you make the adjustment to the fill like shown in the image? thanks

![image](https://user-images.githubusercontent.com/6676843/85213315-b3841e80-b32a-11ea-8671-9b055f01aae3.png)

**Comment by nicdiac** [comment]
perfect! I'll check all the animals for that gaps and refine the sloth lines a little. thanks :)

**Comment by nicdiac** [comment]
Sorry the delay, some issues comes up. Here are the hippo and the kangaroo reformulated. I have to do some refinements, but to give you the main concept. 
![Mesa de trabajo 5@300x-100](https://user-images.githubusercontent.com/65752952/88221684-373b6e80-cc3b-11ea-8454-066830b478ad.jpg)

**Comment by carlinmack** [comment]
Wow good work!

Can you upload the monkey, skunk, raccoon, bee, sloth, hippo and kangaroo! thanks 😀

**Comment by b-g** [comment]
Hi @nicdiac, Many thanks for this! Nice! But I think this could be still improved a bit ... I don't like that the black lines cluster that much. Could you try once more to further simplify the curves while avoiding clustering of the black lines? 

![2020-07-23 at 15 43](https://user-images.githubusercontent.com/480224/88293617-877a0580-ccfb-11ea-823f-4fa771a89338.png)

**Comment by nicdiac** [comment]
Sorry again the impass 🙈 I don't enter to much on GitHub and the mail with the notification got buried on my inbox. 

Thanks @b-g and @carlinmack, I'll be doing the corrections to those last ones. It were just concept about the kangaroo and the hippo, just to see if you liked the twist from the already ones. Those things you said, the cluster of the black lines, were actually the ones I had to correct. In the next days I'll do the corrections and I'll upload the definitive ones!  💪

**Comment by nicdiac** [comment]
Hi there! I got the final ones over [here](https://github.com/hfg-gmuend/openmoji/files/5264004/Animals.zip), let me know I you want some modification, even if its minor. I corrected the clustering in the kangaroo and the hippo mainteining the essence of both.

Also check If I exported well the svg's. I'd problems in the past with that and I want to solve it at once. 😅

Cheers and I hear you guys! 🙌

**Comment by nicdiac** [comment]
Hey! Someone is doing the improvements for the food ones? Just to take it and advance on it

**Comment by carlinmack** [comment]
nope, feel free! I didn't catch that you linked the SVGs above, so I'll get to them and add them soon :) sorry about the delay

**Comment by carlinmack** [comment]
![image](https://user-images.githubusercontent.com/6676843/98179131-1a663680-1ecc-11eb-8e50-ea6941e94ad2.png)
all look great!

**Comment by lizbravob** [comment]
hi, 😁 can I help here improving emoji?

**Comment by carlinmack** [comment]
of course!

**Comment by b-g** [comment]
@lizbravob Please! :) YAY!

**Comment by lizbravob** [comment]
I started bottom-up :) hope it works well, and welcome any feedback.
[improving_openmoji.zip](https://github.com/hfg-gmuend/openmoji/files/5717246/improving_openmoji.zip)

Greetings :)

**Comment by carlinmack** [comment]
![image](https://user-images.githubusercontent.com/6676843/102654609-d0b17280-413e-11eb-985a-5f550b6eb5c3.png)
all look great, two nitpicks:

- could you make the lady bird a bit bigger, so that it touches the circle
- can you adjust this part a little bit? I think it looks good but it could be a bit cleaner
![image](https://user-images.githubusercontent.com/6676843/102654796-2f76ec00-413f-11eb-8209-268673fdcd22.png)

**Comment by carlinmack** [comment]
Oh also can you make the caterpillar body a bit bumpier? thanks!

![Uploading image.png…]()

**Comment by lizbravob** [comment]
Holaa! 👋

I fixed the bug, lady beetle & old man. And I redesigned the others :)

Greetings. 
[redesign_openmoji.zip](https://github.com/hfg-gmuend/openmoji/files/5727087/redesign_openmoji.zip)

**Comment by carlinmack** [comment]
![image](https://user-images.githubusercontent.com/6676843/102838261-bcce7080-43cb-11eb-86b0-a55c4b640ec2.png)
Ah so cute!

maybe with slightly shorter arms?

![image](https://user-images.githubusercontent.com/6676843/102838373-03bc6600-43cc-11eb-9f69-63681aaa1ebb.png)

I'll upload the other ones tomorrow :)

**Comment by lizbravob** [comment]
Sure :) 
[redesign_openmoji.zip](https://github.com/hfg-gmuend/openmoji/files/5727327/redesign_openmoji.zip)

**Comment by carlinmack** [comment]
added in c6ed7af :)

**Comment by tif-calin** [comment]
Really minor thing, but it bothers me a lot. The carrot emoji is messed up. 
![image](https://user-images.githubusercontent.com/76538249/105613981-d07a4780-5d7a-11eb-8ab3-231a0a2f471a.png)

It's a really easy fix. I just opened the svg with Inkscape and moved the lighter orange of the carrot to the bottommost layer and the regrouped things. Here's the new svg file

[carrot.zip](https://github.com/hfg-gmuend/openmoji/files/5861043/carrot.zip)

**Comment by b-g** [comment]
@tif-calin Many thanks for spotting! Fixed with https://github.com/hfg-gmuend/openmoji/commit/f6af300a94a29ab6ae1014d8e56fffb8b006d368 ... please fix in the future the files of the `src` folder and not exported ones (they don't have the full accuracy). Cheers.

**Comment by lizbravob** [comment]
..and also from this list :) 

Some openmoji are repeated in #143. I'll be pending for your feedback 😬

[openmoji.zip](https://github.com/hfg-gmuend/openmoji/files/6410790/openmoji.zip)

**Comment by b-g** [comment]
Wow! Nice! @dnlutz @carlinmack Comments before I merge it?

<img width="1054" alt="Screen Shot 2021-05-03 at 12 01 47" src="https://user-images.githubusercontent.com/480224/116863985-6ab61b00-ac07-11eb-87eb-3c8a71fc0193.png">

**Comment by carlinmack** [comment]
all great! would be good to preserve the old mushroom design and maybe some others

**Comment by b-g** [comment]
Yay! I think we are done with this one. Closed. Many thanks @lizbravob and @carlinmack  🙏❤️!!

**Comment by yayatichavhan54-cyber** [comment]
Title:Proposal: New Emoji Design Submission for OpenMoji

Message:

Hello OpenMoji Team,

I would like to submit my original emoji design for your consideration. I have created this emoji with the intention of contributing a new and creative addition to the OpenMoji collection.

Emoji Name: [Write your emoji name here]Creator: Yayati Dhanlal Chavhan

I have attached the emoji sample files/images for review. Please let me know if any changes are required to match the OpenMoji style guidelines.

I would appreciate your feedback and consideration for including this design in the OpenMoji project.

Thank you for your time and for maintaining this amazing open-source emoji library.

Best regards,Yayati Dhanlal Chavhan 

[Yayati_Dhanlal_Chavhan_Emoji_Portfolio.pdf](https://github.com/user-attachments/files/29887766/Yayati_Dhanlal_Chavhan_Emoji_Portfolio.pdf)

**Comment by yayatichavhan54-cyber** [comment]
My phone number is 9552005107 
If this number is busy then call 9370521617 try on this number
