### ISSUE TITLE
Improving consistency with other platforms

### ISSUE THREAD

**Issue by carlinmack** [hfg-gmuend/openmoji#143]
_Continuation of #105_ 

## Faces
- [x]     [shocked face with exploding head](https://emojipedia.org/shocked-face-with-exploding-head/) looks like some sort of crown but should have a cloud of smoke emanating (we use this emoji as an example of line art on the contributions page) - ce5a27d by @taralynnconnelly
- [x] [loudly crying face](https://emojipedia.org/loudly-crying-face/) - eyes should be closed - 4aa37cd19f2552cceab7a7fbd7c8f7911ec62984
- [x] [face with look of triumph](https://emojipedia.org/face-with-look-of-triumph/) - complete redesign - There should be some steam coming out of nose - 8e6e613373d0ab150bc49e8c5ae1ca40f2c4ce47
- [x]  [serious face with symbols covering mouth](https://emojipedia.org/serious-face-with-symbols-covering-mouth/) - redesign - There are no symbols covering the mouth and the emoji should potentially be red
- [x] [sad but relieved face](https://emojipedia.org/sad-but-relieved-face/) - the tear drop should be pointed up and eyes should be open
- [x] [fearful face](https://emojipedia.org/fearful-face/) - should have same mouth as [frowning face with open mouth](https://emojipedia.org/frowning-face-with-open-mouth/] and the eyes/brows should be centered 
- [x] [yawning face ](https://emojipedia.org/🥱) - we should be able to see inside of mouth
- [x] [exploding head](https://emojipedia.org/🤯/) - should be dark inside the mouth
- [x] [Hot face](https://emojipedia.org/🥵) - it is reddish-orange in all other platforms. Openmoji is the only one to show it as yellow. It only needs to change the colour

## Other
- [ ] [pinching fingers](https://emojipedia.org/pinching-hand/)  Pinching fingers should be closer
- [x] [oyster](https://emojipedia.org/oyster/) - redesign - I don't think this should be purple at all
- [x] [small aeroplane](https://emojipedia.org/🛩/) - [tweet](https://twitter.com/riscfuture/status/1195840791903522816) - no cabin, looks like a drone
- [x] [waffle](https://emojipedia.org/🧇/) - [tweet](https://twitter.com/Enkaybee/status/1198451928080027648) - add butter and syrup
- [x] [japanese dolls](https://emojipedia.org/japanese-dolls/) - [blog post](http://mandel59.hateblo.jp/entry/2016/03/04/041437) - need to add scepter and fan, change skin colour to white
- [x] [ringed planet](https://emojipedia.org/🪐/) - [tweet](https://twitter.com/physicsJ/status/1232664158769795072) - should add planetary bands, maybe adjust rotation to 26.7°
- [x] [bouquet](https://emojipedia.org/bouquet/) - not a bouquet!
- [x] [custard](https://emojipedia.org/custard/) - looks like a cake, not a creme caramel
- [x] [mail box](https://emojipedia.org/📦) - should be isometric
- [x] [spaghetti](https://emojipedia.org/spaghetti/) - all other platforms show a dish with a fork
- [x] [atm sign](https://emojipedia.org/atm-sign/) - should say ATM and look like a sign (current design is really nice and should be moved to OpenMoji extras afterwards
- [x] [christmas tree](https://emojipedia.org/christmas-tree/) - needs to be a bit more decorative with a star on top
- [x] [Black nib:](https://emojipedia.org/✒) - majority of platforms shows it as only the nib of a fountain pen. Some platforms (including openmoji) show it as a entire or almost entire fountain pen. It is very confusing as it is just the same as fountain pen!
- [x] [Cinema](https://emojipedia.org/🎦) - almost all platforms show as a symbol inside a square. Maybe to add a square around
- [x] [crab](https://emojipedia.org/🦀) - openmoji is only platform that shows crab facing downward. Design of claws could be improved

**Comment by Michele0512** [comment]
spaghetti dish: looks like a salad bowl more than a plate. (in all other platform is a dish; the curry rice is openmoji is a plate)
exploding head
exploding head (new design): I don't think should be white inside the mouth (it is not white in none of other platforms)
atm: wonderful design but only one without "ATM" and only one (except Mirosoft) with visible banknote

**Comment by carlinmack** [comment]
* yes!
* agree
* we'll move the current design to OpenMoji extras :)

**Comment by Michele0512** [comment]
christmas tree: in all other platform there is a star on top of tree, consider adding a star on top

**Comment by Michele0512** [comment]
Hot face: it is reddish-orange in all other platforms. Openmoji is the only one to show it as yellow. It only needs to change the colour
Black nib: majority of platforms shows it as only the nib of a fountain pen. Some platforms (including openmoji) show it as a entire or almost entire fountain pen. It is very confusing as it is just the same as fountain pen!
Cinema: almost all platforms show as a symbol inside a square. Maybe to add a square around

**Comment by Michele0512** [comment]
Construction: it is red and white only in openmoji. In all other platforms is yellow and black

**Comment by carlinmack** [comment]
Fixed Construction :) https://github.com/hfg-gmuend/openmoji/commit/2622f796d2f5bb1ed65cb47ea68c23a5100850d6

**Comment by Michele0512** [comment]
crab: openmoji is only platform that shows crab facing downward. Design of claws could be improved

**Comment by lizbravob** [comment]
Hi :)

I redesigned the faces 👀 Welcome any feedback 😬
[faces_redesign.zip](https://github.com/hfg-gmuend/openmoji/files/5745670/faces_redesign.zip)

Saludos 👋

**Comment by carlinmack** [comment]
![image](https://user-images.githubusercontent.com/6676843/103215655-fe867c00-48e1-11eb-96da-3c132280d1f5.png)
all great! no fixes :)

**Comment by mvolz** [comment]
I had a quick go at the pinching fingers... 

![1F90F oldsvg](https://user-images.githubusercontent.com/351040/105217104-5b74fb00-5b4b-11eb-8bd6-2f723dfb10ab.png) old version
![1F90F_new svg](https://user-images.githubusercontent.com/351040/105217108-5c0d9180-5b4b-11eb-86ac-58939acb6e82.png) closer pinch
![1F90F v2](https://user-images.githubusercontent.com/351040/105217109-5ca62800-5b4b-11eb-9daf-383e3111118e.png) even closer pinch

Super preliminary- I'll try to work on it a bit more later. I think the closer pinch is looking more pinch-like now, but now the other fingers are out of proportion so I think they need a little re-working too. 

[pinching.zip](https://github.com/hfg-gmuend/openmoji/files/5844474/pinching.zip)

**Comment by b-g** [comment]
Hi @mvolz, many thanks for this! I would vote for the "even closer pinch" :) And yes the index finger looks a bit out of proportion now.

**Comment by mvolz** [comment]
[pinching.zip](https://github.com/hfg-gmuend/openmoji/files/5854951/pinching.zip)
![1F90F_new2_2](https://user-images.githubusercontent.com/351040/105475457-4dcc8c00-5c97-11eb-9632-53cf978393a9.png)

How is this?

**Comment by dnlutz** [comment]
i would leave out the knuckles, apart from that it's almost perfect!
… and it will be absolutely perfect if you could please correct these little dents ; )

maybe i would thicken the base of the forefinger a little bit (arrow)?

<img width="590" alt="grafik" src="https://user-images.githubusercontent.com/38292227/105480331-e2d68180-5ca5-11eb-82e6-735a3747d99a.png">

<img width="590" alt="grafik" src="https://user-images.githubusercontent.com/38292227/105480098-98550500-5ca5-11eb-844c-c54a7df8370e.png">

**Comment by tif-calin** [comment]
Really minor thing, but it bothers me a lot. The carrot emoji is messed up. 
![image](https://user-images.githubusercontent.com/76538249/105613981-d07a4780-5d7a-11eb-8ab3-231a0a2f471a.png)

It's a really easy fix. I just opened the svg with Inkscape and moved the lighter orange of the carrot to the bottommost layer. Here's the new svg file

[carrot.zip](https://github.com/hfg-gmuend/openmoji/files/5861039/carrot.zip)

**Comment by mvolz** [comment]
Corrected bumps but - if you look at the other emojis none of them have the fingers out- we're the only ones. So I think we need to close the fist as well both for consistency's sake and also realism :). Most people pinch with the fist closed. 

[pinching.zip](https://github.com/hfg-gmuend/openmoji/files/5862099/pinching.zip)
![1F90F](https://user-images.githubusercontent.com/351040/105628909-ae92ca80-5e37-11eb-92de-5ac5b965c045.png)

**Comment by dnlutz** [comment]
yes i think you are right, it's too differrent gestures.
we could keep this one as a special version and put it in extras-openmoji.

hands are quite challenging to draw … would you give the closed pinching hand a try? ; )

**Comment by lizbravob** [comment]
Hola 🙃

I was improving some openmoji. Welcome any feedback 😬
 
[openmoji_improving.zip](https://github.com/hfg-gmuend/openmoji/files/5901661/openmoji_improving.zip)

Greetings

**Comment by mvolz** [comment]
> Hola 
> 
> I was improving some openmoji. Welcome any feedback 
> 
> [openmoji_improving.zip](https://github.com/hfg-gmuend/openmoji/files/5901661/openmoji_improving.zip)
> 
> Greetings

Just one comment on 1F9AA - the emoji is called oyster, but this is unfortunately... a clam. Getting rid of the purple (as it says in the description above so obviously not on you!) is in my opinion not enough because it's the wrong animal :/.

I probably should have mentioned this earlier in the thread before you did the work >.<

Personally I think this emoji needs a total redesign so it actually looks like an oyster and not a clam (as per other emojis -> https://emojipedia.org/oyster/)

**Comment by carlinmack** [comment]
![image](https://user-images.githubusercontent.com/6676843/106440892-5bc49e80-6447-11eb-8361-7e47b40a142b.png)

**Comment by b-g** [comment]
@lizbravob Very nice! Many thanks! Some comments:

- 1F4E6, I would mirror it so that the grey tape runs from left to right and hint a address or label of some kind
- 1F9AA, I agree this should be oyster ... but I would preserve your version in openmoji-extras as an alternative
- 1F9C7, I didn't recognize it being waffles. Sorry :) I would either try a round one like the Apple emoji or a stack of square waffles (like the [stack of books](https://openmoji.org/library/#search=book&emoji=1F4DA))

**Comment by b-g** [comment]
@mvolz RE pinching hand: Let us know once your have a version with the fist more closed :)

**Comment by Ryuno-Ki** [comment]
Since I discovered the pinching emoji on Emojipedia right now, here's a fun fact: It looks like the sign (in sign language) for toilet.
Thumb and pointing finger form a c, the other fingers a w => wc.

**Comment by dnlutz** [comment]
… that means it is double useful ; )

**Comment by lizbravob** [comment]
Hola! :)

I made the suggestions :) sorry for the delay. 
What do you think? 
[Openmoji_.zip](https://github.com/hfg-gmuend/openmoji/files/6321783/Openmoji_.zip)

**Comment by dnlutz** [comment]
thank you!
1F9AA oyster: very nice!
1F4E6 package: what about moving the dark grey thing a bit downwards so that it sits in the middle of the two light grey stripes?
1F9C7 waffle: already a huge step forward ; ) i would recommend lighter fillings. maybe the left and the right side a bit rounder (sketch attached)? with a small gap in between one can see better that it is two waffles on top of each other.
<img width="281" alt="Bildschirmfoto 2021-04-16 um 11 43 56" src="https://user-images.githubusercontent.com/38292227/115006841-9f0ca600-9ea9-11eb-83eb-e39e7b372c69.png">

**Comment by carlinmack** [comment]
![image](https://user-images.githubusercontent.com/6676843/115008263-e9c1fa00-9e78-11eb-9711-58e96e87b8dd.png)

**Comment by b-g** [comment]
Added with https://github.com/hfg-gmuend/openmoji/commit/889fc9a667ad8e09f3229b70dade82f8a95b3136 5 new 13.1 ones and 2 improvements. Contribution by Nelly Nieter. Thanks!

Moved old Fog to Foggy Mountain in extras.

<img width="1054" alt="Screen Shot 2021-04-19 at 09 22 34" src="https://user-images.githubusercontent.com/480224/115873160-e9aa9700-a442-11eb-9904-b9c2922c6a44.png">

**Comment by lizbravob** [comment]
Holaa :) how about these waffles?

Perspective is hard for me, haha 👎 I'm trying.
[Openmoji.zip](https://github.com/hfg-gmuend/openmoji/files/6381552/Openmoji.zip)

**Comment by b-g** [comment]
Nice! Plz check @dnlutz 

<img width="999" alt="Screen Shot 2021-04-27 at 08 22 33" src="https://user-images.githubusercontent.com/480224/116195058-fc1e1c80-a731-11eb-99f5-438ac070ac95.png">

**Comment by dnlutz** [comment]
i like it, thank you … the waffles look much fluffier now ; )

**Comment by b-g** [comment]
@lizbravob quick double check: Will use these improvements to update the existing OpenMojis. OK? (Or did I loose anything over course of the winding thread above?)
<img width="1054" alt="Screen Shot 2021-04-28 at 13 23 16" src="https://user-images.githubusercontent.com/480224/116396184-59df6100-a825-11eb-85ee-a4e222601091.png">

**Comment by lizbravob** [comment]
YAY it's ok :)

**Comment by lizbravob** [comment]
I had time to do the missing ones from this list 🙂ji
[openmoji.zip](https://github.com/hfg-gmuend/openmoji/files/6410776/openmoji.zip)

**Comment by b-g** [comment]
Wow nice II! @dnlutz @carlinmack anything to add before I merged it?

<img width="1054" alt="Screen Shot 2021-05-03 at 12 03 14" src="https://user-images.githubusercontent.com/480224/116864077-920ce800-ac07-11eb-97c9-b096fd56b1c9.png">

**Comment by carlinmack** [comment]
wow great!!

**Comment by b-g** [comment]
Yay! I think we are done with this one. Closed. Many thanks @lizbravob 🙏❤️!!

**Comment by Alignitems** [comment]
[Auto Rickshaw](https://emojipedia.org/auto-rickshaw/): It's yellow/green in all other platforms.

**Comment by laloussul** [comment]
Hi,I was exploring some open-source repositories and came across your website: https://openmoji.org/. 
I want to congratulate you on your excellent work and thank you for making it open source. However, I noticed that the search box on the website is vulnerable to XSS (cross-site scripting). Addressing this vulnerability is better to prevent potential cyber attacks.
@b-g
