### ISSUE TITLE
Change the flags!

### ISSUE THREAD

**Issue by OMGShay** [hfg-gmuend/openmoji#150]
### If you want to know what flag emoji characters you need to change, please see below:

- [x] Laos: The middle stripe must be blue whule the two thin ones need to be red.
- [x] Turkey: The star must be flipped sideways.
- [x] Kazakhstan: Add a yellow line near the sleeve of the flag and add a bird underneath the sun.
- [x] Maldives: Make the border thicker.
- [x] Jersey: Add the emblem.
- [x] New Caledonia: Red stripe should be in the middle and the green stripe should be at the bottom.
- [x] Niger: The circle should be a bit smaller and lines need to be thicker.
- [x] Antarctica: The blue background needs to be lighter.
- [x] Mayotte: Add the word "MAYOTTE" in red above the coat of arms.
- [x] Hong Kong SAR China: Add spots in the petals of the flower.
- [x] Aruba: The 4 pointed star requires a white outline.
- [x] Iraq: The stars should be dropped and replaced by the Arabic writing.
- [x] Mozambique: Add a yellow star.
- [x] Namibia: The circle should be a sun to look like the actual Namibia flag.
- [x] New Zealand: Stars need white outlines.
- [x] Antigua and Barbuda: The sun needs to be bigger.
- [ ] Albania: Redesign central element completely
- [ ] British Indian Ocean Territory and Diego Garcia: Add the emblem, and position it near the other vertical side of the flag.

**Comment by carlinmack** [comment]
Wow!!! thanks so much, I'll get on this!

**Comment by carlinmack** [comment]
https://github.com/hfg-gmuend/openmoji/compare/3d28cf3377bfc8f7c8b9bc5a810d69dc14498273...7b1578527e3751ec4fa6abf72d3a752a1a589568

**Comment by b-g** [comment]
Hi @OMGShay, many thanks for spotting! This is great and actionable feedback! Keep in mind that our color palette and the level of detail is limited e.g. text on the flag is not really possible.

**Comment by carlinmack** [comment]
I think the text actually works even at 72x72
![image](https://user-images.githubusercontent.com/6676843/77931000-94b94300-7279-11ea-8d75-5f6cb03a44cb.png)

**Comment by carlinmack** [comment]
One restriction however is the white outline around the aruba star, can't find a way to make it look good so I've improved the background colour instead

**Comment by b-g** [comment]
Please no text. This also a question of "fairness" between different countries. Why does Mayotte get normal readable text but Saudi Arabia an abstraction. We spent weeks on the flags ... changing a basic assumption e.g. text y/n would be crazy hard in terms of effort. Please :)

**Comment by b-g** [comment]
May I reverse Mayotte https://github.com/hfg-gmuend/openmoji/commit/df0f1b3aa462f6e1eb1f38c6a872f2d1ac4244da ?

**Comment by carlinmack** [comment]
I feel like that implies Mayotte should also be an abstraction, rather than being removed (i.e. red line where the text is)

**Comment by b-g** [comment]
Yes abstracting this into a red line seems to be a "fair" compromise. 👍 ! Good call!

**Comment by mikiqex** [comment]
I tried to fix the Czech flag, because my eyes bled from the narrow triangle :-) It should be halfway along the rectangle and to me it looks still better squished, than narrow. I also fixed colors.

I'm adding second SVG with correct proportions (3:2), but I understand if you prefer the 62 pt width to unify all flags. I tried to keep it's height, so I made the whole flag narrower (57 pt).

[1F1E8-1F1FF.svg.txt](https://github.com/hfg-gmuend/openmoji/files/4614939/1F1E8-1F1FF.svg.txt)
[1F1E8-1F1FF_3x2.svg.txt](https://github.com/hfg-gmuend/openmoji/files/4614940/1F1E8-1F1FF_3x2.svg.txt)

(Sorry for the .txt, It doesn't let me upload .svg. Also I'm n00b in pull requests and stuff... :-)

**Comment by OMGShay** [comment]
Come on, you are not a n00b. You are a genius. Why not add the Brecqhou flag?
Best regards, Shay Ebanks McDonald
    On Tuesday, 12 May 2020, 11:38:35 BST, Michal Novák <notifications@github.com> wrote:  
 
 


I tried to fix the Czech flag, because my eyes bled from the narrow triangle :-) It should be halfway along the rectangle and to me it looks still better squished, than narrow. I also fixed colors.

I'm adding second SVG with correct proportions (3:2), but I understand if you prefer the 62 pt width to unify all flags. I tried to keep it's height, so I made the whole flag narrower (57 pt).

1F1E8-1F1FF.svg.txt
1F1E8-1F1FF_3x2.svg.txt

(Sorry for the .txt, It doesn't let me upload .svg. Also I'm n00b in pull requests and stuff... :-)

**Comment by carlinmack** [comment]
@mikiqex are you familiar with GitHub, would you like to do a PR? If not I can do it for you and credit you :)

**Comment by carlinmack** [comment]
Maybe I misread the first time but I'll do the PR for you :+1:

**Comment by carlinmack** [comment]
@mikiqex https://emojipedia.org/openmoji/12.3/flag-czechia/ :D

**Comment by Michele0512** [comment]
Albania: please redraw completely if possible. I think it is currently by far the most problematic flag. The double-headed eagle is simplified to the point that looks like a chinese character. It is the only unrecognizable flag in the set. Some minor problems are being corrected for flags that are otherwise recognizable

**Comment by carlinmack** [comment]
totally agree and thanks for spotting! we can do something similar to https://openmoji.org/library/#search=1F1F2-1F1E9&emoji=1F1F2-1F1E9

**Comment by wayne-shih** [comment]
Re the list of flags to be changed...

Mind if I also add in [Taiwan](https://emojipedia.org/flag-taiwan/) 🇹🇼 `1F1F9-1F1FC` ?

Changes needed 
— make the sun bigger
— _(potentially)_ separating out the rays from the core; might mean making the core smaller than official to allow for the rays to split out and align with the OpenMoji style... will have to play around with that

| OpenMoji (as at v12.3.0) | Apple Color Emoji | Official |
| ------ | ------ | ------ |
| <img width="150" alt="1F1F9-1F1FC.svg" src="https://raw.githubusercontent.com/hfg-gmuend/openmoji/9ea5516a1847ed82529edbeb0202b2afef78f00b/color/svg/1F1F9-1F1FC.svg"> | <img width="150" alt="flag-for-taiwan_1f1f9-1f1fc" src="https://user-images.githubusercontent.com/51947763/85661716-21ee2580-b70b-11ea-8307-44def3246ecf.png"> | <img width="150" alt="Flag_of_the_Republic_of_China.svg" src="https://upload.wikimedia.org/wikipedia/commons/7/72/Flag_of_the_Republic_of_China.svg"> |

Happy to give it a crack and a PR if that's fine with y’all :)

**Comment by wayne-shih** [comment]
for Mozambique 🇲🇿

>  Mozambique: Add a yellow star.

Reckon would also be worth to add in a white rectangle to symbolise the book

| OpenMoji (as at v12.3.0) | Apple Color Emoji | Official | Flaticon rendition |
| ------ | ------ | ------ | ------ |
| <img width="150" alt="1F1F2-1F1FF.svg" src="https://raw.githubusercontent.com/hfg-gmuend/openmoji/9ea5516a1847ed82529edbeb0202b2afef78f00b/color/svg/1F1F2-1F1FF.svg"> | <img width="150" alt="flag-for-mozambique_1f1f2-1f1ff" src="https://user-images.githubusercontent.com/51947763/85665816-d9853680-b70f-11ea-8f4a-42ea21324989.png"> | <img width="150" alt="Flag_of_Mozambique.svg" src="https://upload.wikimedia.org/wikipedia/commons/d/d0/Flag_of_Mozambique.svg"> | <img width="150" alt="flaticon" src="https://image.flaticon.com/icons/svg/555/555673.svg"> |

See the flaticon abstracted version as ref https://www.flaticon.com/free-icon/mozambique_555673

**Comment by b-g** [comment]
Hi @wayne-shih Many thanks for reporting and spotting!

> Happy to give it a crack and a PR if that's fine with y’all :)

Please! :)

**Comment by carlinmack** [comment]
when you're designing, please don't copy another provider and instead use the official flag as a reference, thanks!

**Comment by SecularSteve** [comment]
I made my own "Pre-Alpha" version of the last 2 just for a bit of fun.
It's pretty hard to work with Inkscape when you can't properly mirror objects.

But anyways, if any of you can make them better, knock yourselves out. All that's really needed is the quare feathers, claws and better heads for the Albanian flag:

![1F1EE-1F1F4](https://user-images.githubusercontent.com/33793273/100384663-f2787780-3020-11eb-870b-201f3e37bb73.png)

![1F1E6-1F1F1](https://user-images.githubusercontent.com/33793273/100384670-f60bfe80-3020-11eb-892e-dbd7f917ba31.png)

I can't continue them myself at this moment, as I have other things to worry about...

[new_flags_0.1_WIP.zip](https://github.com/hfg-gmuend/openmoji/files/5604620/new_flags_0.1_WIP.zip)

**Comment by shaurya1709** [comment]
Also the Indian flag appears broken in the font versions.
