### ISSUE TITLE
Does content using OpenMoji have to be licensed under CC-BY-SA?

### ISSUE THREAD

**Issue by wait-what** [hfg-gmuend/openmoji#155]
I've been trying really hard to understand whether using content licensed under CC-BY-SA in an app count as adapting the content. Is it ok to use OpenMoji in non open source software, provided OpenMoji is credited? The -SA part is really confusing me

**Comment by b-g** [comment]
Hi @wait-what, many thanks for the interest!

> I've been trying really hard to understand whether using content licensed under CC-BY-SA in an app count as adapting the content. Is it ok to use OpenMoji in non open source software, provided OpenMoji is credited?

Yes. Common places for attribution are for example: to mention us in your project README, the 'About' section or the footer on a website/in mobile apps.

Attribution suggestion:
All emojis designed by OpenMoji – the open-source emoji and icon project. License: CC BY-SA 4.0

> The -SA part is really confusing me

If you were to edit our emojis ... we would kindly ask you to open-source those edits as well. This tries to avoid that a fork of OpenMoji would stay closed source.

Good luck with the app! We are keen to see OpenMojis in the wild ... if you want you can post a link to your app afterwards in #125 :)
