### ISSUE TITLE
Some emojis to add 

### ISSUE THREAD

**Issue by OMGShay** [hfg-gmuend/openmoji#160]
Here you'll find all these flags. Look out for the ones that you haven't added as an emoji, then translate them into English and add them as emojis. http://caccioppoli.com/Animated%20gifs%20flags%20the%20Nations%20of%20the%20world.html

**Comment by carlinmack** [comment]
At the moment we're only really supporting the flags listed here https://emojipedia.org/flags/ However we could support more like the ones that you linked. However, this would be a labour of love for [openmoji extras](https://openmoji.org/library/#group=extras-openmoji). If someone were interested we would love them to do this :)

**Comment by b-g** [comment]
Hi OMGSHay, we don't have the men-power for this. Sorry! But you are welcome to contribute via PR and propose new flags. Thanks.
