### ISSUE TITLE
Cetacean Proposal

### ISSUE THREAD

**Issue by kriskowal** [hfg-gmuend/openmoji#161]
I have a proposal for additional cetaceans.

I propose the existing whale emoji be moved to the supplemental set as "orca", "black fish" or "killer whale".

To be more consistent #143 with other platforms, I propose a new blue whale. The basis is a 180 degree turn of the orca.

I've added variants for "narwhal" and "beluga" for sake of completeness (the narwhal is for my emoji quest game project).

![cetacean-plate](https://user-images.githubusercontent.com/60294/78317524-593ba480-7517-11ea-927a-b8f24ddfb5c0.png)

**Comment by kriskowal** [comment]
Added cuts for 2.5D effect on whale flippers. I'm recommending whale and spouting whale variants.

https://emojis.wiki/whale/
https://emojis.wiki/spouting-whale/

![whales](https://user-images.githubusercontent.com/60294/78319379-e7198e80-751b-11ea-83ef-bc1b86968d56.png)

**Comment by carlinmack** [comment]
wow! I love that we have a complete underwater mammal set

~~I don't really get rotating the orca, it's hard for me to read from the silhouette due to the fin being on the bottom, meaning it's upside-down. ~~ I pass to @b-g about whether orca or blue whale is our Whale design

I would be happy to merge this when the following design issues are resolved:
* adjust the shape of the narwhals head to be more accurate to the shape of actual narwhal heads https://commons.wikimedia.org/wiki/Category:Monodon_monoceros_(illustrations) 
* i didn't read properly and thought it was meant to be a dolphin, here's a lovely photo I was going to ask you to use lol https://commons.wikimedia.org/wiki/File:2017-05-16_Show_in_Kyiv_Dolphinarium_11.jpg
* your beluga seems to have broken it's back :( You can exaggerate from this within reason, but the main takeaway is more bending in the tail than the head https://commons.wikimedia.org/wiki/File:Delphinapterus_leucas_in_shallows.jpg

**Comment by kriskowal** [comment]
The rotated orca is not a proposal. I used the shape as a base reference to
maximize consistency of the vocabulary. I think I will try the same flipped
along the vertical axis to produce a consistent porpoise 🐬

**Comment by kriskowal** [comment]
I cut the converging proximal lines. I found precedents for both having the color edges flush with the implied stroke edges and alternately also flush with the middle of the stroke. I found that the right lateral fin looked better colored only to the middle of the elided stroke, and the proximal stroke flush with the outer edge, but I defer to your opinions.

![whale-spouting](https://user-images.githubusercontent.com/60294/78329570-e8a48000-7536-11ea-868f-12f1f77c633d.png)

**Comment by kriskowal** [comment]
Iterating on narwhal body shape. Early draft for feedback.

![narwhal](https://user-images.githubusercontent.com/60294/78331209-6ddd6400-753a-11ea-9f95-2cd2b075f381.png)

**Comment by kriskowal** [comment]
Full set, drafts.
![cetaceans-draft](https://user-images.githubusercontent.com/60294/78333747-463cca80-753f-11ea-9e20-36d8a463113c.png)

**Comment by b-g** [comment]
Hi @kriskowal! Super! Very nice to have a new set of underwater mammals! Also happy to move the existing whale to extras-openmoji and replace with blue ones.

Comments:
- whale flippers: Already very nice! But could you try a version which has more closed outline shape? My bet would be like this ... Also it is important to discuss the alternatives visually side by side (think of a tableau) otherwise nearly impossible to judge.
![2020-04-03 at 08 40](https://user-images.githubusercontent.com/480224/78331764-01d51d00-7587-11ea-8101-3550dbc32432.png)
- narwhal: yes the head and shape of body should be bit more natural. I would also bend the back of the narwhal to have more space for the "horn". Maybe like this but flipped so that the horn faces to the left
![2020-04-03 at 09 06](https://user-images.githubusercontent.com/480224/78333766-be7cad80-758a-11ea-96ce-b6b565448a39.png)

**Comment by b-g** [comment]
@kriskowal 
![2020-04-03 at 09 12](https://user-images.githubusercontent.com/480224/78334236-b6713d80-758b-11ea-9d1b-0ce955dd3c0b.png)

**Comment by kriskowal** [comment]
Some whale line clipping variations.

![whale-tableau](https://user-images.githubusercontent.com/60294/78335166-f4497400-7541-11ea-80a9-e3a79b898397.png)

**Comment by kriskowal** [comment]
These two vary by clip amount behind the left fin. The new one reduces parallel lines.

![hand-off](https://user-images.githubusercontent.com/60294/78335478-894c6d00-7542-11ea-9911-1103f36486bc.png)

**Comment by b-g** [comment]
Very nice! Definitely bottom row for me. Hard to say left / right or the clip amount behind the left fin. Other opinions please @dnlutz @carlinmack @bohnacker?

**Comment by kriskowal** [comment]
Fiddling with the horn and head angle on the narwhal prototype.

![narwhal-angles](https://user-images.githubusercontent.com/60294/78335708-fb24b680-7542-11ea-81f6-d0988c8f2499.png)

**Comment by b-g** [comment]
> Fiddling with the horn and head angle on the narwhal prototype.

I would rather try the back blended like a arc in "n" (flipped to the left) and not as a "u"
![78333766-be7cad80-758a-11ea-96ce-b6b565448a39](https://user-images.githubusercontent.com/480224/78336080-13222780-758f-11ea-8ea3-69d6deae0f93.png)

**Comment by dnlutz** [comment]
for the whale i prefer the version on the right. maybe it would be better to not clip the lines of fin in the background. 

the narwhale also looks very good, but please make the horn black and use the default line width (it's the most important feature of this animal (which is not encoded in unicode yet?))

very nice work!

**Comment by kriskowal** [comment]
> I would rather try the back blended like a arc in "n" (flipped to the left) and not as a "u"
> ![78333766-be7cad80-758a-11ea-96ce-b6b565448a39](https://user-images.githubusercontent.com/480224/78336080-13222780-758f-11ea-8ea3-69d6deae0f93.png)

@b-g I'm not sure what you're suggesting, but here's a snapshot of stages of the narwhal design we can use as a reference. In the last, I rounded out the neck in case that's what you're looking for.

![narwhal-arc](https://user-images.githubusercontent.com/60294/78373109-fed62e80-757e-11ea-8019-2632a7c18596.png)

**Comment by kriskowal** [comment]
Porpoise color and embellishment options

![porpoise-embellishments](https://user-images.githubusercontent.com/60294/78375323-82911a80-7581-11ea-96e0-2b716ae5967d.png)

**Comment by kriskowal** [comment]
Beluga options

![beluga-options](https://user-images.githubusercontent.com/60294/78377530-92f6c480-7584-11ea-8c55-59330f4ab23f.png)

**Comment by kriskowal** [comment]
Spouting whale iterations. I believe we so far have consensus on the last entry, number 7.

![spouting-whale-options](https://user-images.githubusercontent.com/60294/78377704-cc2f3480-7584-11ea-8604-c8a58c8c9c91.png)

**Comment by kriskowal** [comment]
This is the proposed orca change, to keep the tail fin motiv consistent.

![orca-change](https://user-images.githubusercontent.com/60294/78378462-d69dfe00-7585-11ea-89c1-5478f724ef16.png)

**Comment by carlinmack** [comment]
sorry no full black emojis! see https://openmoji.org/library/#search=black heart&emoji=1F5A4

**Comment by carlinmack** [comment]
Also only animal faces have eyes https://openmoji.org/library/#group=animals-nature

**Comment by kriskowal** [comment]
> Also only animal faces have eyes https://openmoji.org/library/#group=animals-nature

Cool, that narrows things down!

**Comment by kriskowal** [comment]
> sorry no full black emojis! see https://openmoji.org/library/#search=black%20heart&emoji=1F5A4

No apology necessary. The existing one is full black. This is a good opportunity to fix. Here's the revised plate. I also went back to reference images and I do think there's enough of an anatomical difference to warrant a different tail fin than the other cetaceans. I made a third option that's somewhere between the original by Selina Bauder and mine borrowing the shape from the other whales.

![orca-change](https://user-images.githubusercontent.com/60294/78379773-bff8a680-7587-11ea-965b-94f40fe2ce4a.png)

**Comment by carlinmack** [comment]
I should've been clearer about what I mean by full black, 1 is dark grey and good, 2 is full black and bad 
![orca-change](https://user-images.githubusercontent.com/60294/78378462-d69dfe00-7585-11ea-89c1-5478f724ef16.png)

**Comment by kriskowal** [comment]
> I should've been clearer about what I mean by full black, 1 is dark grey and good, 2 is full black and bad
> ![orca-change](https://user-images.githubusercontent.com/60294/78378462-d69dfe00-7585-11ea-89c1-5478f724ef16.png)

Ah, sorry. The distinction is lost on the screen I'm developing on, but I know what you mean. Thank you for pointing it out. I'll edit in place above.

**Comment by carlinmack** [comment]
I think if you turn your screen brightness up it should be more apparent :)

**Comment by kriskowal** [comment]
This is the set of most likely contenders, I believe.

![cetaceans-most-likely](https://user-images.githubusercontent.com/60294/78382029-0996c080-758b-11ea-8e75-6c69b32c6cfb.png)

**Comment by carlinmack** [comment]
so interesting situation, I think your Porpoise emoji is a better dolphin emoji than our current [Dolphin emoji](https://openmoji.org/library/#search=dolphin&emoji=1F42C) and our Dolphin emoji is a better porpoise emoji than your Porpoise emoji. Have a look at the head shapes, however I think the fins should be swapped
![image](https://user-images.githubusercontent.com/6676843/78386816-42935d00-75ac-11ea-9fd3-e2a39d925f54.png)
thoughts?

**Comment by kriskowal** [comment]
> so interesting situation, I think your Porpoise emoji is a better dolphin emoji than our current [Dolphin emoji](https://openmoji.org/library/#search=dolphin&emoji=1F42C) and our Dolphin emoji is a better porpoise emoji than your Porpoise emoji. Have a look at the head shapes, however I think the fins should be swapped
> ![image](https://user-images.githubusercontent.com/6676843/78386816-42935d00-75ac-11ea-9fd3-e2a39d925f54.png)
> thoughts?

I must confess I was using porpoise and dolphin as if they were interchangeable words. Your observation is absolutely correct and I may as well fork that into separate pieces.

**Comment by carlinmack** [comment]
I actually wasn't sure what a porpoise was, which is why I looked it up haha

**Comment by kriskowal** [comment]
Porpoise vs Dolphin

![porpoise-dolphin](https://user-images.githubusercontent.com/60294/78390125-e541e080-7598-11ea-9e86-94c778f8142d.png)

**Comment by carlinmack** [comment]
yes much better! maybe porpoise can also be grey? I think you can make a master post of all the finals for review :)

**Comment by kriskowal** [comment]
Another tableau for comparison of orca / killer whale fin options. Still trying to strike a compromise between using the same tail fin as the other cetaceans (upper), and the abstract fins of the original (lower). These are all the most likely contenders at present.

![comparison](https://user-images.githubusercontent.com/60294/78390861-238bcf80-759a-11ea-9b6b-cc8f0cf0372f.png)

**Comment by kriskowal** [comment]
Addendum, I'm thinking there might be more variation between whale spouting (breaching) and whale (just swimming). I don't know whether there's precedent, but it might be handy to hint that the spout lines are water with a colored drop shadow. If consistency is an issue but you like the change, I would leave it out and revisit it generally in a follow-up.

![whale-spouting-color-rim](https://user-images.githubusercontent.com/60294/78460322-b13bed80-7674-11ea-8725-ae694a351afe.png)

**Comment by kriskowal** [comment]
> ![finals-orca-fins](https://user-images.githubusercontent.com/60294/78391222-ce03f280-759a-11ea-8449-cc3a4bede275.png)

Thank you for merging #165 and #167.

The only remaining decision remaining to close this issue out is whether to revise the tail fin on the orca to use the same motiv as on the other cetaceans. The bottom left is the original. The bottom right is consistent with the other whales. The top middle is the original.

**Comment by b-g** [comment]
@kriskowal Nice detail! Now that we have a new standard for whale tail fins ... I would vote to make it consistent and to go with the bottom right one.

**Comment by kriskowal** [comment]
Posted #171 with revised orca fins.

**Comment by kriskowal** [comment]
:tada:
