### ISSUE TITLE
Rerun generate after 93c0eba5c

### ISSUE THREAD

**Issue by kriskowal** [hfg-gmuend/openmoji#163]
At least as of commit 93c0eba5cf254c3976a7fdaf44bfb6945def6269 on master, running generate causes many changes to checked-in artifacts. When this kind of divergence occurs, would it be helpful to submit a PR to bring master back up to date? Is it possible that generate is producing different output on my machine than it would on others?

**Comment by carlinmack** [comment]
generate also causes huge changes on my end too, I entrust b-g to run it and maintain it. The build only breaks if images do not exist, which is why I only export files individually (#153) when I add new emojis.

On a side note, why are you referencing a commit that's three months old?

**Comment by kriskowal** [comment]
Thanks for pointing out my how ancient that commit was! I had indeed checked out the wrong one.

I'm verifying whether the build is indeed consistent across systems. I'm hoping its consistent enough that others can run incremental builds as part of the PR workflow and arrive at consistent results. Notes:

```
Linux DESKTOP-RA6J2R3 4.4.0-18362-Microsoft #476-Microsoft Fri Nov 01 16:53:00 PST 2019 x86_64 x86_64 x86_64 GNU/Linux
rsvg-convert version 2.40.2
pngquant, 2.0.1 (September 2013), by Greg Roelofs, Kornel Lesinski.
43 minute build
93c0eba5cf254c3976a7fdaf44bfb6945def6269 -> e34f144a283df454dcbdc859ae313fc0d4b45a41
```

**Comment by carlinmack** [comment]
You could test this by checking out 9c481bc5c769841daf98e4d3b4a36bed96d912e3 and running `./generate` then `git status`.

**Comment by kriskowal** [comment]
I obtained different hashes on different workstations. I'm betting there are significant differences based on system dependency versions. This is insightful for #154. I had hoped, but not really expected, that generating assets would be consistent. I’ll follow up with conclusions on #154.
