### ISSUE TITLE
Clarifying exporting files in contributing.md

### ISSUE THREAD

**Issue by loominade** [hfg-gmuend/openmoji#176]
According to [_6. Submission_](https://github.com/hfg-gmuend/openmoji/blob/master/CONTRIBUTING.md#6-submission) I should not commit any changes in the `black` & `color` folders. Does it mean, i can ignore the errors below?

```
 64792 passing (3m)
  6 failing

  1) File integrity black/color production files
       Production svg files exist?
         ⯃ should have black/svg/2BC3.svg:

      AssertionError: expected false to be true
      + expected - actual

      -false
      +true
      
      at Context.<anonymous> (test/file-exists-production.js:20:48)

  2) File integrity black/color production files
       Production svg files exist?
         ⯃ should have color/svg/2BC3.svg:

      AssertionError: expected false to be true
      + expected - actual

      -false
      +true
      
      at Context.<anonymous> (test/file-exists-production.js:24:48)

  3) File integrity black/color production files
       Production png files exist?
         ⯃ should have black/72x72/2BC3.png:

      AssertionError: expected false to be true
      + expected - actual

      -false
      +true
      
      at Context.<anonymous> (test/file-exists-production.js:33:48)

  4) File integrity black/color production files
       Production png files exist?
         ⯃ should have black/618x618/2BC3.png:

      AssertionError: expected false to be true
      + expected - actual

      -false
      +true
      
      at Context.<anonymous> (test/file-exists-production.js:37:48)

  5) File integrity black/color production files
       Production png files exist?
         ⯃ should have color/72x72/2BC3.png:

      AssertionError: expected false to be true
      + expected - actual

      -false
      +true
      
      at Context.<anonymous> (test/file-exists-production.js:41:48)

  6) File integrity black/color production files
       Production png files exist?
         ⯃ should have color/618x618/2BC3.png:

      AssertionError: expected false to be true
      + expected - actual

      -false
      +true
      
      at Context.<anonymous> (test/file-exists-production.js:45:48)
```

**Comment by carlinmack** [comment]
so this is just that you haven't exported the files, which we don't have a friendly way to do yet. Don't worry about it :)

**Comment by carlinmack** [comment]
@b-g we ask people to generate the data tables but not to export files as we will do it. How about we remove the requirement to generate the data tables? 

Also should there be a step zero to install node/npm?

**Comment by b-g** [comment]
@carlinmack Hmm ... I would leave it as it is. As people who can do a PR are also experts enough to install node on their own, or? And if we don't have the new emoji added to the data tables then we don't get the unit test (`npm run test-dev`) on every PR. But yes ... this is all not 100% ideal. Sorry!

**Comment by b-g** [comment]
A quick thing to improve the PR experience a bit ... could be do experiments with reporter bots e.g. https://github.com/hfg-gmuend/openmoji/blob/b0a00d22bcb0bde5a83ab7674470d080c7b946e3/.github/workflows/test-pull-request.yml#L24 also for `npm run test-dev`

**Comment by carlinmack** [comment]
I'm not sure what you mean in your last comment?

I think if we have to do intervention to generate the files before merging their PR, we can also generate the tables — however I get that it delays the testing until we intervene.

And yeah I don't think installing npm/node is difficult, but I don't want great designers being turned away because they haven't used a command line before. I'm not sure what the solution would be, but I think there's space to improve here

**Comment by b-g** [comment]
@carlinmack 
First let me come back to the very beginning of this issue, see https://github.com/hfg-gmuend/openmoji/issues/176#issue-602008786 ... yes this is misleading! We should clarify to something like this.

Please:
- don't generate the assets /black /color
- do generate the data tables
- it should pass npm run test-dev 
- (it doesn't matter if it fails on npm test)

The quoted errors are result of a run of `npm test` which we run only on anything on which was pushed to master. So loominade should have not get bothered with it in the first place.

Second I think it would be great to add a PR reporter bot for the output of npm run test-dev. Like this:

<img width="767" alt="Screenshot 2020-04-21 at 14 17 20" src="https://user-images.githubusercontent.com/480224/79866009-66dc9f80-83dc-11ea-840d-f26c6ec60ffb.png">

See my broken PR test https://github.com/hfg-gmuend/openmoji/pull/188

That way a contributor would get immediately feedback if a PR is broken.

**Comment by b-g** [comment]
Closing this. I think it is clear enough / no fast way to improve this. Please re-open if anyone wants to continue discussion :)
