### ISSUE TITLE
Add brand emoji: LinkedIn

### ISSUE THREAD

**Issue by dayvista** [hfg-gmuend/openmoji#180]
I am using OpenMoji for a project that involves the use of social media icons. Every icon I need in that regard is covered in the "brand" section except for the LinkedIn logo. I have an icon from an alternative source that will suffice in the meantime, but it subtly breaks the continuity of the design. I am requesting the creation of a LinkedIn logo OpenMoji. I've attached some reference photos. 

I understand that this is a bit of a selfish request. As such, I want to express my gratitude for this project even existing, as well as for anyone that considers my proposal.

![888065_logo_512x512](https://user-images.githubusercontent.com/58375683/79643083-304e1d00-816f-11ea-8eff-b42c118cae29.png)

![linkedin](https://user-images.githubusercontent.com/58375683/79643085-3512d100-816f-11ea-9605-d5114ff14aa3.png)

**Comment by carlinmack** [comment]
would you like to have a shot at making it yourself? I can give you a hand if you'd like :)

**Comment by carlinmack** [comment]
it was way harder than I realised and I've opened a PR #181 I need to see what my team mate thinks before I can merge

**Comment by dayvista** [comment]
I'm not much of a designer but I'm open to trying if you'd point me in the right direction. Although, from your last response @carlinmack I'm assuming that you already went ahead and attempted to make it

**Comment by carlinmack** [comment]
We have an alphabet, and it would've been simple enough to put the characters in a box, unfortunately it's only uppercase :( 

You can preview my design by clicking the link above and going to "files changed"

**Comment by dayvista** [comment]
It looks v. good to me thus far. We'll wait and see what your team member thinks

**Comment by carlinmack** [comment]
Added in 248f281c702dca0ddbc483c2a4d92da58047ffd9 :D Feel free to use any of the assets there in your project before they are officially released :)
