### ISSUE TITLE
web feed icon

### ISSUE THREAD

**Issue by fuddl** [hfg-gmuend/openmoji#183]
A symbol that i always felt was [missing in unicode](https://github.com/vhf/unicode-syndication-proposal). A symbol that represents a [web feed](https://en.wikipedia.org/wiki/Web_feed)

![FEED](https://user-images.githubusercontent.com/842548/79685325-3c51e180-8238-11ea-9fe7-271ee235858e.png)
[Figma Link](https://www.figma.com/file/sZZLEmdnMTOAxq0mTgO4WN/tardis-emoji?node-id=9%3A0)

What do you think?

**Comment by carlinmack** [comment]
from looking at this in more detail online, it seems that the two arcs are actually quarter circles. Yours seem to be more than a quarter as they hug the inner circle. Could you change them? thanks

**Comment by fuddl** [comment]
you mean like this?

![FEED](https://user-images.githubusercontent.com/842548/79690751-59001080-825c-11ea-876a-3603721afbba.png)

**Comment by carlinmack** [comment]
![image](https://user-images.githubusercontent.com/6676843/79691197-1d4d5280-822c-11ea-91fd-4e2d7db31996.png)
could this gap be the same? after that it should be good for a PR 👍

**Comment by fuddl** [comment]
![FEED](https://user-images.githubusercontent.com/842548/79692708-e9dbe980-8266-11ea-9357-680f50c8412b.png)

**Comment by carlinmack** [comment]
😍

**Comment by fuddl** [comment]
thanks 🎉
