### ISSUE TITLE
OS logos

### ISSUE THREAD

**Issue by fuddl** [hfg-gmuend/openmoji#192]
## Draft

![Logos Android, Apple, Ubuntu, Windows](https://user-images.githubusercontent.com/842548/80275052-1ff1f100-86df-11ea-94dd-f1b66bd3b4c2.png)

## Mapping

I propose to map those to the following codepoints within the PUA because they are already used by the respective vendors.

Char | Code | Description
-----|-------|-----------
   | `F000` | Windows
   | `E0FF`  | Ubuntu 
    | `F8FF` | Apple

**Comment by carlinmack** [comment]
looks great! please adjust the 'leaf' of the apple logo as shown in the image
![image](https://user-images.githubusercontent.com/6676843/80282243-6c88fc80-86de-11ea-8823-e4ab7a1c8e9d.png)

also could you move the leaf up by a pixel or so to make more space

**Comment by fuddl** [comment]
Looks weirdly close. Any idea how to solve this?

![](https://user-images.githubusercontent.com/842548/80284208-5babab80-871d-11ea-878b-2eead5ef8c45.png)

**Comment by carlinmack** [comment]
from my previous message:
> also could you move the leaf up by a pixel or so to make more space

👍

**Comment by fuddl** [comment]
![](https://user-images.githubusercontent.com/842548/80284560-a3cbcd80-871f-11ea-85c0-33b98ba4e0ee.png)

**Comment by carlinmack** [comment]
great! yeah it's a pain :(

**Comment by fuddl** [comment]
@carlinmack may I add my own figma cleanup script?

**Comment by b-g** [comment]
Looks super! Really nice!

**Comment by b-g** [comment]
@fuddl Offtopic: We ask all the contributors to add a portrait / social media links to https://openmoji.org/about/#team (not a must, just a nice tradition ... a "no" is fine too). If you want you could do this via PR on https://github.com/hfg-gmuend/openmoji-website (see about/index.html)

**Comment by fuddl** [comment]
> Looks super! Really nice!

@b-g thank you. feed free to review #197 😁

I'll gladly add myself once I have the time

**Comment by carlinmack** [comment]
closing this issue as it's been added in a6c1cddfdcd305442c4ec0ca76f8e92365280b1f, but @fuddl remember about your portrait :)
