### ISSUE TITLE
⏺ vs. ☉

### ISSUE THREAD

**Issue by fuddl** [hfg-gmuend/openmoji#193]
Currently the `⏺`-Character looks very similar the [astronomical symbol for sun: `☉`](https://en.wikipedia.org/wiki/Astronomical_symbols#Symbols_for_the_Sun_and_Moon)

There is also overlap with various other shapes `⦿`, `⦾`, `⊙`, `⊚`, `◉` but with `⏺` the solution might be easy:
[why don't we make the inner dot red?](https://www.google.com/search?q=record+button&client=firefox-b-d&source=lnms&tbm=isch&sa=X&ved=2ahUKEwigmKOemYPpAhUBzaYKHeeHBpAQ_AUoAXoECA8QAw&biw=1280&bih=726)

![record-red](https://user-images.githubusercontent.com/842548/80275794-e2dc2d80-86e3-11ea-9c49-b19823b0189b.png)

**Comment by carlinmack** [comment]
sure! please keep the black inner dot and add the red dot in the `color-foreground` group
