### ISSUE TITLE
cleaning up figma files

### ISSUE THREAD

**Issue by fuddl** [hfg-gmuend/openmoji#196]
![figma-export](https://user-images.githubusercontent.com/842548/80307052-12179b00-87c7-11ea-9393-9b21ed80c000.png)

When using these settings in the current version of [Figma](https://www.figma.com/) (_Figma Desktop App release 85_) the following updates need to be performed:

```js
const prettyfyFigmaSVG = (srcFilePath, destFilePath,) => {
  const dom = new JSDOM(fs.readFileSync(srcFilePath, 'utf8'));
  const doc = dom.window.document;
  let modified = false;

  // Problem: figma will add a `height` attribute to the `<svg>` element

  const svgWithHeight = doc.querySelector('svg[height]');
  if (svgWithHeight) {
    svgWithHeight.removeAttribute('height');
    modified = true;
  }

  // Problem: figma will add a `width` attribute to the `<svg>` element.

  const svgWithWidth = doc.querySelector('svg[width]');
  if (svgWithWidth) {
    svgWithWidth.removeAttribute('width');
    modified = true;
  }

  // Problem: figma will add a `fill="none"` attribute to the svg element. all child 
  // elements will implicitly be set to `fill="none"`. we instead want svg's default
  // behavior.

  const svgWithFillNone = doc.querySelector('svg[fill="none"]');
  if (svgWithFillNone) {
    svgWithFillNone.removeAttribute('fill');
    const elementsWithoutFill = svgWithFillNone.querySelectorAll('circle:not([fill]), ellipse:not([fill]), path:not([fill]), polygon:not([fill]), polyline:not([fill]), rect:not([fill])')
    elementsWithoutFill.forEach(el => {
      el.setAttribute('fill', 'none');
    });

    modified = true;
  }

  // Problem: figma will automatically add ids based on the type of element. These ids 
  // might end with a number.

  const figmaDefaultIds = ['Rectangle', 'Vector', 'Line', 'Arrow', 'Ellipse', 'Star', 'Polygon', 'Union', 'Subtract', 'Intersect', 'Exclude', 'Group'];
  const elementsWithId = doc.querySelectorAll('[id^="' + figmaDefaultIds.join('"], [id^="') + '"]');
  elementsWithId.forEach(el => {
    el.removeAttribute('id');
    modified = true;
  });

  // Problem: figma will create a root element `<g>` with an id that is equal to the art 
  // board name

  const rootGroup = doc.querySelector('svg > g[id]:only-child');
  if (rootGroup) {
    let parent = rootGroup.parentNode;
    while (rootGroup.firstChild) parent.insertBefore(rootGroup.firstChild, rootGroup);
    parent.removeChild(rootGroup);
    modified = true;
  }


  if (modified) {
    console.log('cleaning up -> ', srcFilePath);
    writeSvg(destFilePath, doc.querySelector('svg').outerHTML);
  }
}
```

after that `<svg>` needs the `emoji` id and the standard svgo treatment. Can we integrate something like this into the helper scripts? How can we design the workflow?

I'd propose exporting svgs from figma with a `.figma` suffix. This setting remains permanent in figma. The exported file will be named `[artboard-name].figma.svg` (e.g. `F8FF.figma.svg`). The cleanup script could search the `src` folder for that extension, apply the above changes and rename the file to `[artboard-name].svg`.

What do you think?

**Comment by carlinmack** [comment]
wow this sounds and looks great! I'll defer to @b-g for this :)

**Comment by b-g** [comment]
Hi @fuddl, Sorry for the slow response ... very busy here. Yes, it would be great to be more inclusive and have Figma as editor documented too! Many thanks for this!

Comments:

- svg attribute x, y, width, height is cover with svgo now too https://github.com/hfg-gmuend/openmoji/commit/06fd2c51542ce0a1e8c8904964b1ee9f94b263e2
- happy to include something like prettyfy-figma-svg.js in `helpers` folder, please propose something

> I'd propose exporting svgs from figma with a .figma suffix. This setting remains permanent in figma. The exported file will be named [artboard-name].figma.svg (e.g. F8FF.figma.svg). The cleanup script could search the src folder for that extension, apply the above changes and rename the file to [artboard-name].svg.

Yes this would be a nice convention. But we should ask the people to run the prettyfy-figma-svg.js script **before** the commit anything. Would be great not to deal with any figma legacy files in the src folder.

OK?

**Comment by b-g** [comment]
Seems to be done. Closed. Thanks everyone!
