### ISSUE TITLE
Licensing - how to (correctly) attribute the authors?

### ISSUE THREAD

**Issue by ccoenen** [hfg-gmuend/openmoji#2]
I'm currently looking into various emoji libraries, and this one is certainly very interesting. So first of all: **thanks for creating it**!

I am contributing to another open source project, which is a web-based collaborative text editor. I am thinking about adding the emoji as an option for users to add to their documents. We're debating right now, what the correct course of action is, regarding the `-BY-SA` part of your license.

Basically two groups have formed:

* one is arguing, that mentioning the credits once would be sufficient (think: imprint of a website or footer of a created document).
* the other is arguing, that each single occurence of an emoji would have to also contain a credit link. (basically the way a figure or photo in a blog post would get its credit).

So my question is basically: do you know, which one it is? Do you know somebody who could say with certainty?

To stress this: We are not trying to avoid giving credit. You deserve all the credit! We're just trying to "do it right" while also keeping the documents usable for our users. Here's a document (and more specifically a section of a document) containing our current emoji set:

https://hackmd-ce.herokuapp.com/features#Emoji

**Comment by b-g** [comment]
Hi @ccoenen, 

Many thanks for the interest and encouraging words!

Yes, we had the same feeling that crediting every emoji would be way too much. Hence we added an [attribution requirements hint](https://github.com/hfg-gmuend/openmoji#) to the readme. I think it quite down to earth and pragmatic:

> As an open source project, attribution is critical from a legal, practical and motivational perspective. Please give us credits! Common places for attribution are for example: to mention us in your project README, the 'About' section or the footer on a website/in mobile apps.

The `-BY-SA` bit to simply to "protect" the OpenMoji of an commercial fork without us being involved.

Best, 
Benedikt

PS. HackMD looks interesting! Good luck with it!

cc @dnlutz

**Comment by b-g** [comment]
@ccoenen plz close if you are happy with my answer.

**Comment by ccoenen** [comment]
Yes, thank you :-)
