### ISSUE TITLE
Women wearing turban should not show hair

### ISSUE THREAD

**Issue by gurmukhp** [hfg-gmuend/openmoji#20]
The Emoji for 'Woman wearing turban' show's her hair but the purpose of a turban is to not show hair.

Apple / Google follow this approach, so OpenMoji should too.

Thanks!

**Comment by dnlutz** [comment]
Hello Gurmukh,
of course we can fix that (although it's harder to distinguish man and woman without hair). Is it just a question of aesthetics or does it have religious reasons?
Many Greetings
Daniel

**Comment by gurmukhp** [comment]
It might be difficult to distinguish a female vs male wearing a turban but all Sikhs who wear turbans do it to cover their hair. It has religious significance. Some could be offended that hair is shown at all. Maybe show the same emoji for Turban wearing man/woman/gender neutral?

**Comment by dnlutz** [comment]
thanks for the explanation. i think we'll try to make the female turban look like a turban with more hair underneath ; )

**Comment by dnlutz** [comment]
in the right version i tried to stuff more hair under the turban … but i don't think it looks more female than the person on the left ; ) so we will just follow your suggestion and show the same emoji for turban wearing man/woman/gender neutral.
<img width="998" alt="Bildschirmfoto 2019-09-13 um 15 50 16" src="https://user-images.githubusercontent.com/38292227/64867812-660daf00-d63e-11e9-9e5c-68736537319e.png">

**Comment by gurmukhp** [comment]
Awesome, thanks for the update. Sikhism is all about equality, so having the same emoji for both genders works well

**Comment by b-g** [comment]
Hi @dnlutz, many thanks for the nice fix! But ... I'm actually more fond of the idea to use the version on the right (more hair under the turban), it is just a really nice detail which shows how much love and detail we put into the project :) I really would find the right one more charming. OK? If so, where can I find the file?

**Comment by gurmukhp** [comment]
Hey @b-g, Sikh men and women who wear turbans do not cut their hair. So to say that a woman would have longer hair just isn't true. Both men and women have long hair.

**Comment by b-g** [comment]
Hi @gurmukhp! I see! :) Many thanks for pointing this out. I guess then to have 3 identical ones is most accurate. Lets do it that way. Thanks for sharing and explaining!

**Comment by Sam0711er** [comment]
Just checking in… Have these changes been made in the library? Can this issue be closed? :) @b-g
