### ISSUE TITLE
duplicate emojis

### ISSUE THREAD

**Issue by carlinmack** [hfg-gmuend/openmoji#205]
In creating ZWJ sequences, I've realised we have some duplicates. Listing them here for record

![image](https://user-images.githubusercontent.com/6676843/80853674-8d7eaf80-8c00-11ea-90ca-bf3dc1c382ac.png)
![image](https://user-images.githubusercontent.com/6676843/80855029-6da0b900-8c0b-11ea-827d-20743d386e1d.png)
![image](https://user-images.githubusercontent.com/6676843/80853680-953e5400-8c00-11ea-9e7c-dac490c483e5.png)
![image](https://user-images.githubusercontent.com/6676843/80853694-c3239880-8c00-11ea-907d-e0fed576171c.png)
![image](https://user-images.githubusercontent.com/6676843/80853704-d898c280-8c00-11ea-9920-7a1655db3443.png)
![image](https://user-images.githubusercontent.com/6676843/80853715-ee0dec80-8c00-11ea-95f5-709a5c427657.png)
![image](https://user-images.githubusercontent.com/6676843/80853739-1e558b00-8c01-11ea-89d8-479385716c43.png)
![image](https://user-images.githubusercontent.com/6676843/80854916-ef8fe280-8c09-11ea-9620-81d1c9bb14eb.png)
![image](https://user-images.githubusercontent.com/6676843/80868542-5c869500-8c69-11ea-9d87-bc94e788e1e4.png)
![image](https://user-images.githubusercontent.com/6676843/80893769-47c6f300-8ca3-11ea-8c70-6c84e719684c.png)

Keep in mind the extras section is for alternate designs, so we can keep some duplicates if both designs are worthy

**Comment by fuddl** [comment]
![mice](https://user-images.githubusercontent.com/842548/80857441-83859c80-8c52-11ea-8ecd-c012bf6965df.png)

**Comment by b-g** [comment]
@dnlutz Might there be a way to use Unicode modifiers to express alternatives (like it is done in OpenType fonts)?

**Comment by fuddl** [comment]
There are fonts with _alternative forms_ for certain letters. But I have no idea how this works.

**Comment by dnlutz** [comment]
For the fonts it could work with OpenType Stylistic Sets:
https://glyphsapp.com/tutorials/stylistic-sets
https://ilovetypography.com/OpenType/opentype-features.html
But the question remains how / wether we should keep the duplicates as different svgs in the library.

**Comment by carlinmack** [comment]
I agree the question remains, to put myself out there I would suggest the following:

* I would make Shot the Syringe emoji, but make it the size of the current Syringe
* I like both the Plaster and Adhesive Bandage designs, but the size of Adhesive Bandage is better.
* I'd like to know why we have the Stencils before making a call here
* I think the hats are cute, not sure which design I perfer.
* I vastly prefer 1F517 Link to E269 Link. At small sizes the lack of white space in E269 makes it difficult to see.
* Solar Energy is instantly recognisable where Solar Cell is weaker, however I think we can keep both and maybe improve Solar Cell
* I think we should keep both designs, however I think Manual Wheelchair could use a more detailed Wheelchair
* I think we should sort out the four different check marks by seeing what other platforms are doing. Like I think that one of them should be geometric to match ❌.
* I prefer the E319 Brain to 1F9E0 Brain. (Someone on Twitter agrees)[https://twitter.com/carlinmack/status/1236445436279435264]
* I think we can keep both, but should check if other platforms have polluting factories or not.
* I can't tell if there are identicle or not. I think we should lose E1C5 for consistency. We can have more mouse variations though :)

**Comment by b-g** [comment]
ok for me.

> I'd like to know why we have the Stencils before making a call here

This is coming from the guemil project and we just took it. Would leave it to stay compatible with them.

> I think the hats are cute, not sure which design I perfer.

Would leave it as well, as useful in intercultural terms. Countries have different "visual clues" to represent nurse vs. doctor.

> check marks

Yes ... but keep in mind that 2611 refers to a check box used in an interface which IMO different than ✅. 

For the ✅: I would find it better to contain the check mark inside a box.

> brain

would keep both as useful for different views: top vs. side. But the more readable should become the standard one

> polluting factories

please both

> computer mice

consolidate to a single one. Their a visual identical.

**Comment by carlinmack** [comment]
are you saying the first two bullet points are okay? unclear if you missed them out or not

![image](https://user-images.githubusercontent.com/6676843/81204194-e9498f80-8f96-11ea-9545-351a25e48854.png)
I thought that other platforms had consistent cross/tick icons but it appears not 
![image](https://user-images.githubusercontent.com/6676843/81204203-eb135300-8f96-11ea-8d80-0f17c09ce4b4.png)

**Comment by b-g** [comment]
@carlinmack 

> I would replace Syringe with the Shot emoji, but make it the size of the current Syringe

OK

> I like both the Plaster and Adhesive Bandage designs, but the size of Adhesive Bandage is better.

OK

> I would like to propose we go the microsoft route, even if it's not consistent with other platforms. It seems weird to me that we have 4 handdrawn ticks and no geometric ones when there is a geometric and handdrawn cross

Many thanks for the overview! Yes totally agree! Good call!

**Comment by carlinmack** [comment]
speaking of guemil, would be nice to have some of these

![image](https://user-images.githubusercontent.com/6676843/81732885-21e9dd00-945f-11ea-9137-ebdef33221a8.png)

**Comment by b-g** [comment]
Yes ... but we would have to hallucinate the "colors" :) I believe they are in black & white. Also the style doesn't fit 100%. Would be some effort on top of all the other stuff.

**Comment by carlinmack** [comment]
oh of course we would have to redraw and colour them, but some of them are clear and suited to our project

Maybe not for this release  :)

**Comment by carlinmack** [comment]
![image](https://user-images.githubusercontent.com/6676843/81981068-c30e9a00-95fd-11ea-8eef-b2cc8bd08a45.png)

**Comment by dnlutz** [comment]
Hello carlin, i will reach out to rodrigo from https://www.guemil.info/
They prepared the first batch themselves, hopefully they are willing to do an update as well ; )

For the keyboard: it might become better when you add a little vertical line on the right side of the keys (so they become something like "half squares"). And i would also reduce the amount of keys: only two or three rows?

**Comment by carlinmack** [comment]
thanks! 

good idea with the half keys :)

**Comment by carlinmack** [comment]
![image](https://user-images.githubusercontent.com/6676843/82380802-136b6a80-99f7-11ea-905e-728a9810938f.png)

**Comment by b-g** [comment]
@carlinmack The two pretzel are on purpose like this :) There is the pretzel on the left (how the world think a pretzel should look like) and the "correct traditional" pretzel as you can find everywhere in South Germany (note the thick bit on the bottom with the white patch). We should keep both. Makes a "huge" difference :)

**Comment by carlinmack** [comment]
are they both called 'pretzel'?

**Comment by b-g** [comment]
Yes, both are translated in EN to pretzel.

**Comment by carlinmack** [comment]
@dnlutz I tried half squares and I'm not sure if I'm going in the right direction
![image](https://user-images.githubusercontent.com/6676843/82597397-e47c0280-9b76-11ea-8f73-7dd37883c822.png)

without the darker grey fills it looked really messy

**Comment by dnlutz** [comment]
My favorite is the one in the middle, but I would also use fills for the bigger keys (as you did it in the version on the right). I also believe that fewer keys would be enough: what about one row less? And -1 or -2 keys per row? The keyoard will look less crowded this way.

**Comment by carlinmack** [comment]
![image](https://user-images.githubusercontent.com/6676843/82714401-6003af80-9c5c-11ea-88fd-b2e1d24d4ad9.png)
anything else?

**Comment by dnlutz** [comment]
👍 … i like it ; )

**Comment by b-g** [comment]
Closing, seems to be discussed and all related actionable tasks done.
