### ISSUE TITLE
silence successful tests

### ISSUE THREAD

**Issue by carlinmack** [hfg-gmuend/openmoji#207]
I was wondering if it would be possible to have it so that only negative tests are logged?

It's currently a pain to scroll down the tests in github to find what failed, and I reckon that it slows our testing down to have a print for every test

**Comment by b-g** [comment]
Good call! Yes I quickly had a look at https://mochajs.org/#reporters:

**progress**
<img width="711" alt="Screenshot 2020-05-04 at 14 01 31" src="https://user-images.githubusercontent.com/480224/80964171-aeb5ea80-8e10-11ea-8646-ff1bfd3d85ab.png">

**min**
<img width="711" alt="Screenshot 2020-05-04 at 14 04 58" src="https://user-images.githubusercontent.com/480224/80964186-b37a9e80-8e10-11ea-97ff-7a4942ddc7aa.png">

I sticked with progress as it is a bit more verbose running locally (big progress bar).

Also it seems the test run faster with the minimal reporters. Yay!

**Comment by b-g** [comment]
And for npm run test-dev to the "min" reporter.

**Comment by carlinmack** [comment]
wow great news! thanks
