### ISSUE TITLE
swapping 72x72 to SVG after load

### ISSUE THREAD

**Issue by carlinmack** [hfg-gmuend/openmoji#209]
Currently on https://hfg-gmuend.github.io/openmoji/ we load 72x72 sprites for performance reasons, @felixhaeberle could you advise if we could have progressive enhancement to load SVGs after the 72x72 have been loaded?

**Comment by felixhaeberle** [comment]
Yes that would be cool. Looking into it! 🤟

**Comment by carlinmack** [comment]
nevermind, the site has been redesigned to let people choose which version to use
