### ISSUE TITLE
Openmoji Awesome: which source for svg file?

### ISSUE THREAD

**Issue by gromain** [hfg-gmuend/openmoji#21]
Hello,

I'm going to use Openmoji on my website, and ran across usability issues.
I am adapting [twemoji-amazing](https://github.com/SebastianAigner/twemoji-amazing) to use OpenMoji. However, Twemoji uses Maxcdn as direct link for the svg images in the generated CSS.

I wanted to know if I could do the same for my project and use a direct link to `https://openmoji.org/data/color/svg/$unicode.svg` .
Or would you rather that the users host themselves the used emojis? As I'm using a static website generator, this is not a problem for me.

Thanks!

**Comment by b-g** [comment]
Hi @gromain,

Many thanks for the interest!

We don't have a dedicated CDN. Sorry! However with the help of jsDeliver you can [turn any Github repo into a CDN](https://gomakethings.com/how-to-turn-any-github-repo-into-a-cdn/) e.g.:

`https://cdn.jsdelivr.net/gh/hfg-gmuend/openmoji@12.0.0/color/svg/1F63A.svg`

Should do the trick :)

**Comment by gromain** [comment]
Nice! That's very good to know! I'll use this then! Thanks a lot!
