### ISSUE TITLE
Generic shapes + colors

### ISSUE THREAD

**Issue by loominade** [hfg-gmuend/openmoji#211]
Could these combinations be generated automatically? Like it's done with skin tones?

Color →<br/>Shape ↓ |🟥 | 🟦 | 🟧 | 🟨 | 🟩 | 🟪 | 🟫  | ⬛
------:|:-:|:--:|:--:|:--:|:--:|:--:|:--:|:--:
⭐️       | Red Star | Blue Star | Orange Star | ? | Green Star | Purple Star | Brown Star | ★?
🏳️        | Red Flag | Blue Flag | Orange Flag | Yellow Flag | Green Flag | Purple Flag | Brown Flag | 🏴?
🏴        | Dark Red Flag | Dark Blue Flag | Dark Orange Flag | Dark Yellow? Flag | Dark Green Flag | Deep Purple Flag | Dark Brown Flag | cthulhu flag?
⬡          | Red Hexagon | Blue Hexagon | Orange Hexagon | Yellow Hexagon | Green Hexagon | Purle Hexagon | Brown Hexagon | ⬢?
⬢          | Dark Red Hexagon | Dark Blue Hexagon | Dark Orange Hexagon | Dark Yellow? Hexagon | Dark Green Hexagon | Deep Purple Hexagon | Dark Brown Hexagon | ?

**Comment by b-g** [comment]
Yes ... possible. But as this seems to be special case it is probably quicker just to do it manually :) Also we are not so keen to add even more complexity (for relative little gain) to the just recently re-written build system. Sorry!

But you totally could write such a generator on your own and generate the emojis ... and we could then include them under extras-openmoji :)

**Comment by loominade** [comment]
> But as this seems to be special case it is probably quicker just to do it manually :) 

But what are the rules for that? Not all cases are as easy as  
🏳️ + 🟥 = RED FLAG

The Black Hexagon is already black, what should if thise are combined?
⬢ + ⬛ = ?

The white star is officially white but usually depicted as yellow. What if it combined with yellow: 
⭐️ + 🟨 = ?

I'd propose these combinations should be regarded as invalid.

**Comment by carlinmack** [comment]
I would assume the script would just change the fill colour to the colour provided, and so it wouldn't change.

I think it would be a neat challenge to write such a script, if I had the time for it

what type of script where you imagining?

**Comment by HaasJona** [comment]
> The white star is officially white but usually depicted as yellow.

No, "white" doesn't mean that. See https://emojipedia.org/glossary/#white. The star should be yellow (or even better: gold) by default.

**Comment by loominade** [comment]
> what type of script where you imagining?

Lets say we changed the [White Star](https://github.com/hfg-gmuend/openmoji/blob/master/src/travel-places/sky-weather/2B50.svg) like this:

```diff
  <g id="color">
-    <polygon fill="#FCEA2B" stroke="none" points="35.9928,10.7363 27.7913,27.3699 9.4394,30.0436 22.7245,42.9838 19.5962,61.2637 36.0084,52.6276 52.427,61.2515 49.2851,42.9739 62.5606,30.0239 44.2067,27.3638"/>
+    <polygon class="token-color" fill="#FCEA2B" stroke="none" points="35.9928,10.7363 27.7913,27.3699 9.4394,30.0436 22.7245,42.9838 19.5962,61.2637 36.0084,52.6276 52.427,61.2515 49.2851,42.9739 62.5606,30.0239 44.2067,27.3638"/>
  </g>
```
The [color pallette](https://github.com/hfg-gmuend/openmoji/blob/master/data/color-palette.json) could should be grouped:
```yaml
colors:
  blue: ['#92D3F5', '#61B2E4']
  red: ['#EA5A47', '#D22F27']
  yellow: ['#FCEA2B', '#F1B31C']
…
```

A build script could assume that since that element has a fill of `#FCEA2B` and the class `class="token-color"` that the Glyph already has a yellow color scheme. Thus it can iterate over the remaining color scheme and associate a colored square ligature.

**Comment by carlinmack** [comment]
I don't even think you need to add a class, just put the ones you want to transform into a folder and have it output to another folder (and append the `extras-openmoji.csv` information to a file)

**Comment by loominade** [comment]
> I don't even think you need to add a class, just put the ones you want to transform into a folder and have it output to the extras-openmoji folder (and append the extras-openmoji.csv information to a file)

The class would make sense in cases where emoji contain multiple colors from different schemes.

Lets say you want to use the police car: 
![police car](https://raw.githubusercontent.com/hfg-gmuend/openmoji/master/color/svg/1F693.svg)

but in your country police card are green. So you'd writer `🚓🟩`. the green should only apply to the blue stripe, not the the yellow headlight. So we'd only add the `token-color` class to the stripe.

**Comment by carlinmack** [comment]
I didn't realise that you meant glyphs that had more than one fill - the issue is named "generic shapes". The complexity of this is extraordinary and would imply thousands of new glyphs which is unfeasible to support.

Also I would say "`🚓🟩` should be a green police car?" This opens up debate on the colouring of thousands of emoji, which isn't worth is as people generally don't care about the colouring of emoji that don't represent people

**Comment by loominade** [comment]
> I didn't realise that you meant glyphs that had more than one fill - the issue is named "generic shapes". The complexity of this is extraordinary and would imply thousands of new glyphs which is infeasible to support.

So far I only propose generic shapes, but a good solution should be extensible to more complicated cases.

**Comment by carlinmack** [comment]
Surely only if those more complicated cases are feasible?

**Comment by carlinmack** [comment]
I would be hesitant to apply this sort of colour mapping to anything greater than a generic shape. Yes I'm sure people would use grey/white cat and dog emojis, but what about green cat/dog? what about different colours of elephant? I think we should assess the value of these glyphs by how much they are likely to be used

**Comment by carlinmack** [comment]
sorry I pressed close and comment rather than deleting my message 😅

**Comment by carlinmack** [comment]
I think the heart of the matter is:

- there are lots of edge cases like you mention
- every OpenMoji goes through manual review before being added

So a script that generates 100? 1000? +? new glyphs creates a lot of new work for us in terms of discussion and tweaking, for relatively little gain

Additionally, people don't type ZWJ sequences —  it would be bad UX to have people guess which sequences work. Also I think having them listed inline in the keyboard would make emoji selection confusing. I imagine that the keyboard/picker implementation to accommodate this, like skintones,  would be even more complex and we simply don't have the man-power for it. 

I hope this makes sense. I do like the idea, especially the flag+colour combinations, but sadly I don't think this is feasible at the moment.

**Comment by fuddl** [comment]
> I hope this makes sense. I do like the idea, especially the flag+colour combinations, but sadly I don't think this is feasible at the moment.

@carlinmack: Would you approve if someone manually added flag+colour combinations?

**Comment by carlinmack** [comment]
yep! you can still script it if you want :)
