### ISSUE TITLE
How to credit in YouTube description?

### ISSUE THREAD

**Issue by in2Rafi** [hfg-gmuend/openmoji#213]
Hi, I want to use Openmoji emojis in my YouTube video description. I see you have mentioned one can use Openmoji and give credit like this.. 

All emojis designed by [OpenMoji](https://openmoji.org/) – the open-source emoji and icon project. License: [CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/#).

Since YouTube doesn't support anchor texts I can't write the credit according to your given way. In this case how can I give you credit?

Secondly do I have permission to use Openmoji emojis commercially?

Thanks and really appreciate your contribution...

**Comment by b-g** [comment]
Hi @in2Rafi!

> Since YouTube doesn't support anchor texts I can't write the credit according to your given way. In this case how can I give you credit?

You could add into the video description underneath and/or at the end of video ...

> Secondly do I have permission to use Openmoji emojis commercially?

Yes ... see  https://github.com/hfg-gmuend/openmoji/blob/master/FAQ.md

Good luck with the project!

**Comment by in2Rafi** [comment]
Hi, I think you didn’t understand my first question! I meant YouTube description section doesn’t support anchor text. I mean I can’t wrap a link using the Openemoji or CC by- SA 4.0 texts. In these cases how can I link back to your given links?

**Comment by b-g** [comment]
YouTube description text (underneath video player):

> All emojis designed by OpenMoji – the open-source emoji and icon project. License: CC BY-SA 4.0. https://openmoji.org/

or

> All emojis designed by OpenMoji – the open-source emoji and icon project. License: CC BY-SA 4.0.

(plain text is fine too)

**Comment by in2Rafi** [comment]
Fantastic. Many Thanks B-g. May Allah bless you...
