### ISSUE TITLE
How To Use Openmoji on YouTube Description?

### ISSUE THREAD

**Issue by in2Rafi** [hfg-gmuend/openmoji#215]
Hi, I have installed .ttf file and now just a bit confused! Actually I don't know how can I use the emojis in the video description. Do I need to copy special emoji code and paste in YouTube description? If so where will I get the codes? Can you please help me?

**Comment by b-g** [comment]
Just paste in the credit text (without any emojis). Use the OpenMoji images e.g. png files in your video. Hope that works for you. Good luck with the project!

**Comment by in2Rafi** [comment]
Hi b-g. Not sure why I'm failing to explain! I mean how can I use emojis? In this page...
https://openmoji.org/library/
I see emojis are with codes. But to use emojis I need to copy codes from this page again and again. Instead can you give me a pdf file or something like this to save on my local hard disk? Then to use emoji everytime I don't need to browse this library page.
Thanks and much appreciated...

**Comment by carlinmack** [comment]
Hi, our emoji only render if you distribute the font, which you can't do in the youtube description. You can type the emojis available on your platform, ctrl+. on Windows, Command - Control - Spacebar on Mac etc. 

In your video you can use OpenMoji by using the font or by inserting images etc

**Comment by carlinmack** [comment]
The codes on that page are actually the identifier of the character given by the governing body of emoji, Unicode.   
![image](https://user-images.githubusercontent.com/6676843/81584257-85510d80-9380-11ea-88bc-209e2cb31e73.png)
you can see that the identifier on the left becomes the emoji on the right, which is rendered with Microsoft emojis as I'm on Windows

**Comment by in2Rafi** [comment]
Hi! You mean the emojis will not be rendered on someone's computer who didn't install Openmoji on his/her computer?

**Comment by carlinmack** [comment]
sadly yes because it is a font rather than pictures
