### ISSUE TITLE
OpenMoji Release 12.3 Discussion

### ISSUE THREAD

**Issue by carlinmack** [hfg-gmuend/openmoji#216]
I remember hearing somewhere that we are going to do the next release before the end of the month, is this the case?

**Comment by b-g** [comment]
@carlinmack Yes good call! As we have plenty of new things ... I think we could do a 12.3 any time. What about this or next Friday?

**Comment by b-g** [comment]
Kind of related ... @fuddl What about adding a portrait emoji and your links to https://openmoji.org/about/#team ? It is an optional but nice tradition. We would love to have you listed there!

**Comment by carlinmack** [comment]
@lizbravob just pinging to let you know that the next release is coming up, if you have any other additions :) no worries or pressure if not 👍

**Comment by carlinmack** [comment]
We'll be doing the 12.3 release on next Friday the 22nd 😀

**Comment by lizbravob** [comment]
Awesome :) I hope to make any other additions ... soon.

Congrats for the new release the 22nd, you rock. 🚀

**Comment by carlinmack** [comment]
@b-g will you add the subset of gardening emojis for tomorrows release?

**Comment by fuddl** [comment]
Is there something I can do to get #198 in?

**Comment by carlinmack** [comment]
as it's such an old PR I've had to cherry-pick it up 77 commits

**Comment by carlinmack** [comment]
merged 🚀
