### ISSUE TITLE
Add Gardening Openmojis

### ISSUE THREAD

**Issue by b-g** [hfg-gmuend/openmoji#227]
[adjusted-gardening.zip](https://github.com/hfg-gmuend/openmoji/files/4666400/adjusted-gardening.zip)

**Comment by b-g** [comment]
@carlinmack 

> will you add the subset of gardening emojis for tomorrows release?

No, don't have enough time for this. Sorry!

> before you release can you add the California and Berlin flags to the changelog

Done.

**Comment by carlinmack** [comment]
if you could add the metadata as well then they can be merged

**Comment by b-g** [comment]
@carlinmack Done! Could you check whether the gardening vocabulary matches the emojis?

**Comment by carlinmack** [comment]
will do!
