### ISSUE TITLE
Idea: Black Hole Emoji

### ISSUE THREAD

**Issue by fuddl** [hfg-gmuend/openmoji#230]
![BLACK HOLE](https://user-images.githubusercontent.com/842548/82724900-8ca9dc80-9cd9-11ea-948f-c778ca367537.png) ![BLACK HOLE BLACK](https://user-images.githubusercontent.com/842548/82724901-8d427300-9cd9-11ea-8b95-d8de86de70d8.png)

Based on a [NASA Visualization ](https://www.nasa.gov/feature/goddard/2019/nasa-visualization-shows-a-black-hole-s-warped-world) which is pretty close to a [popular depiction in the film _Interstellar_](https://www.wired.com/2014/10/astrophysics-interstellar-black-hole/).
![BH_Accretion_Disk_Sim_360_Continuous](https://user-images.githubusercontent.com/842548/82725001-44d78500-9cda-11ea-9c93-de66852a6881.gif)

Could be mapped on `🕳️`+`⬛`

**Comment by carlinmack** [comment]
wow that's very cool and closely matches the gif, nice! I saw this recently https://twitter.com/matthen2/status/1263678557697396738

**Comment by carlinmack** [comment]
also randomly someone rated all the "black hole" emojis and we won hahah https://twitter.com/PhilipLynchGW/status/1236633891814936578

but anyway yes I think it's good and if @b-g likes it we'll merge :)

**Comment by b-g** [comment]
@fuddl Super! Just wondering whether the ring could be a bit more "visually impossible" to commemorate the black hole better? I'm thinking of an Escher triangle or a Möbius strip replacing your current ring (which could also be read as ring of Jupiter) ... but not sure whether this is feasible :)

![6b3ea2e8a1eced5a76052081b23c1c67](https://user-images.githubusercontent.com/480224/82823316-a3059300-9ea7-11ea-90d9-af96a0952442.jpg)

**Comment by fuddl** [comment]
the is nothing _visually impossible_ about this depiction of a black hole. just the part of the accretion disc which is _behind_ the black hole appears warped around it's horizon. Can you further demonstrate what you propose?

**Comment by axelpale** [comment]
Nice! Also for me, the ring resembles the ring of saturn quite much. Maybe the ring should be connected to the event horizon like in the gif instead of being visually separate. To give an idea what I mean, see my poorly drawn sketch below.

![sketch-blackhole](https://user-images.githubusercontent.com/992081/82892801-ca686880-9f58-11ea-8e16-75a648630284.png)

**Comment by b-g** [comment]
+1. I think @axelpale expressed it better with what I was trying to refer with "visually impossible". Currently for my eyes it looks too much like a normal planet and not like something really special lie a black hole. Hope that makes sense.

**Comment by fuddl** [comment]
like this?
![BLACK HOLE](https://user-images.githubusercontent.com/842548/83051782-c159c300-a04e-11ea-81dd-a851333e29d1.png)

**Comment by carlinmack** [comment]
I think you should look at axelpale's design more closely

**Comment by carlinmack** [comment]
Still looks like a planet, I think connecting the orange lines in the top half would make it more clear

**Comment by b-g** [comment]
+1 

<img width="227" alt="Screen Shot 2020-05-28 at 08 07 22" src="https://user-images.githubusercontent.com/480224/83105144-6067d480-a0ba-11ea-88f5-b524463646e9.png">

@fuddl Many thanks for this! Sorry for all the iterations ... but this just show that we all like the idea and are excited ... and want to get it right :)

**Comment by dnlutz** [comment]
What about going back to good old 2D?
You have to face the Black Hole head-on ; )
<img width="491" alt="black_hole" src="https://user-images.githubusercontent.com/38292227/83133054-915bff80-a0e2-11ea-953d-9a050a8fe075.png">

**Comment by b-g** [comment]
@dnlutz Good alternative! My favs is lower left. 

Maybe we could combine the two approaches e.g. 2d + halo with the colors step gradient?

**Comment by axelpale** [comment]
Here are a couple of thoughts for further discussion.

I thinks the lower left by @dnlutz resembles a galaxy quite much, especially when converted to black-white.
![black-hole-bw_HALF](https://user-images.githubusercontent.com/992081/83140928-8069b900-a0f7-11ea-84a4-ecf56d95e71c.png)

My sister came up with a sketch where the regular spiral has been replaced by more chaotic shape. Just to bring up the idea of chaotic shape.
![2020_05_28-tarina-blackhole](https://user-images.githubusercontent.com/992081/83139612-54e5cf00-a0f5-11ea-9aae-858ba9238dd9.png)

Here is also a still from the gif shared by @fuddl to inspect the shape better.
![still-nasa-black-hole](https://user-images.githubusercontent.com/992081/83139656-67600880-a0f5-11ea-8484-7ac4f5230d5f.png)

**Comment by dnlutz** [comment]
I really like the chaotic shape!
Maybe we can make it a little bit less chaotic,
but I think it would work really well!

**Comment by fuddl** [comment]
> Sorry for all the iterations ... but this just show that we all like the idea and are excited ... and want to get it right :)

no. it's fine. I just need some time

> What about going back to good old 2D?

I like the idea but the top-down view is too ambiguous. could be a cyclone or a galaxy. How about a perfect side view?

**Comment by axelpale** [comment]
> How about a perfect side view?

Oh, a bit like an eye? I like that idea.

![1F441-FE0F-200D-1F5E8-FE0F_color_HALF](https://user-images.githubusercontent.com/992081/83308793-46400a80-a210-11ea-9b86-2ce4a28be294.png)

Maybe [eye in speech bubble](https://openmoji.org/library/#search=eye&emoji=1F441-FE0F-200D-1F5E8-FE0F) provides some inspiration?

**Comment by axelpale** [comment]
For reference a side view. Resembles eye a bit and also brings the empty set ∅ to mind.

![black-hole-side-view](https://user-images.githubusercontent.com/992081/83309396-cf0b7600-a211-11ea-92ba-9c6f6cde9ee0.jpg)

**Comment by carlinmack** [comment]
sorry for not chiming in much, I've been travelling home the past few days. My vote is either with an emoji version of the image directly above, or the 45° version but with the orange lines connected in the top half. 

I don't think the "2D views" are recognisable at all, but a blue version of the bottom left would make a great replacement for our cyclone emoji https://emojipedia.org/cyclone/

**Comment by b-g** [comment]
thanks everyone for the plenty ideas! I guess we should leave it to @fuddl to synthesize then into a new iteration :)

**Comment by fuddl** [comment]
> Still looks like a planet, I think connecting the orange lines in the top half would make it more clear

you mean like this? just a sketch, I'm not happy with the linework:
![BLACK HOLE LINES CONNECTED](https://user-images.githubusercontent.com/842548/83938133-50df3e80-a7d2-11ea-927c-1d49eebc4117.png)

I also tried a 2D side view and it's hard to have it not look like an eye:
![BLACK HOLE FLAT](https://user-images.githubusercontent.com/842548/83938134-5177d500-a7d2-11ea-8487-8144bb61b4f0.png)

If we keep it 3D we should probably remove the intersecting lines under the disk:
![BLACK HOLE NON INTERSECTING](https://user-images.githubusercontent.com/842548/83938256-0a3e1400-a7d3-11ea-9178-5da0e105cccc.png)

**Comment by axelpale** [comment]
@fuddl Great work! What do you think about this sketchy variation, extending the first one of the three by merging the orange lines into a single shape? The simpler the better?

![black-hole-revisit](https://user-images.githubusercontent.com/992081/83940714-e2f54000-a7ee-11ea-82ae-73dd6d0afc37.png)

**Comment by fuddl** [comment]
I like it.

**Comment by b-g** [comment]
@fuddl @axelpale Could we finish the black hole OpenMoij? We have the next release coming up (before we go into the summer break). any chance getting a black hole PR in the next days / until end of July? Sorry to bother! :)

**Comment by axelpale** [comment]
@fuddl I don't want to push you but if you have the time available, it would be great if you committed either the last of [your three](https://github.com/hfg-gmuend/openmoji/issues/230#issuecomment-639997796) or modified it according to [my proposal](https://github.com/hfg-gmuend/openmoji/issues/230#issuecomment-640018578). I think the both are good enough! We can always modify it later if people find it confusing in some way.

Here is a sample of the black-white version made directly by removing the red and orange areas. I think it also looks good enough.
![2020-07-20-openmoji-black-hole-bw](https://user-images.githubusercontent.com/992081/87966454-f66e1900-cac5-11ea-9a3f-0b61ed2f9b03.png)

If you feel you have too much to do right now, I might be able to help. Just let us know.

_Black holes may be entrances to Wonderlands. But are there Alices or white rabbits?_ - Carl Sagan

**Comment by fuddl** [comment]
@axelpale 

![BLACK HOLE COLOR](https://user-images.githubusercontent.com/842548/88463251-bdf98100-ceb1-11ea-955d-837c66d1f9bf.png) ![BLACK HOLE BLACK](https://user-images.githubusercontent.com/842548/88463252-be921780-ceb1-11ea-909d-9085cba98b6b.png)

**Comment by b-g** [comment]
@fuddl Nice! PR please! :)

**Comment by axelpale** [comment]
@fuddl Oh yeah! Great work!

**Comment by b-g** [comment]
done. thanks everyone!
