### ISSUE TITLE
British flag suggestions

### ISSUE THREAD

**Issue by inferno986return** [hfg-gmuend/openmoji#232]
I have a few suggestions for British flags. I have tried prototyping a few of them in Affinity Designer, as many of these are simple geometric designs that reuse components of other flag emojis:

- White Ensign (or British naval flag)
- Blue Ensign
- Red Ensign
- Royal Air Force Ensign
- UK county flags
- City of London flag (not a UK county)
- Ulster banner

![city_of_london_OpenMoji](https://user-images.githubusercontent.com/1838420/82765679-b154a000-9e10-11ea-907f-1867885bfff5.png)
![white_ensign_OpenMoji](https://user-images.githubusercontent.com/1838420/82765713-f5e03b80-9e10-11ea-8ba7-3fd888bc7e5e.png)

**Comment by carlinmack** [comment]
I'd be happy to merge if you made a PR :)

**Comment by b-g** [comment]
Hi @inferno986return, Yes many thanks for this! 

However could you hold back a bit on the obvious military related flags? 

We are currently working on an OpenMoji Code of Conduct and also how we should deal with non unicode standard contributions. 
A general "no" to any kind of "military insignia" could be a point in the contributions guidelines. Yes ... this is a tough discussion ... sorry to slow you down. I hope you understand.

**Comment by inferno986return** [comment]
@b-g As long as I know what the rules are.

There are plenty of non-military flag designs that would be great in emoji form. 😃

**Comment by b-g** [comment]
Closed due to inactivity. Please re-open if you want to give it another try :)
