### ISSUE TITLE
Pokeball emoji

### ISSUE THREAD

**Issue by inferno986return** [hfg-gmuend/openmoji#233]
Watching _Detective Pikachu_ recently gave me the idea for a Pokeball emoji. I am happy with the current mockup I made in Affinity Designer using the pie tool.

![openmoji_pokeball](https://user-images.githubusercontent.com/1838420/82833707-bec46580-9eb6-11ea-88d8-2dd033cc742d.png)

**Comment by carlinmack** [comment]
looks great, could you do 

File > Export > SVG > Preset > SVG (for Export) 

then 

More... > Use hex colors > Close > Export 

then save as E157.svg in openmoji/src/extras-openmoji/objects

then you'd be ready to PR :)

**Comment by inferno986return** [comment]
I've sent the PR. Let me know if there's anything else. :-)

**Comment by b-g** [comment]
Closed due to inactivity. Please re-open if you want to give it another try :)
