### ISSUE TITLE
Colorless flag emojis: use ISO country codes

### ISSUE THREAD

**Issue by eltos** [hfg-gmuend/openmoji#234]
Currently, the country flags appear blank without color and are indistinguishable.  
I propose to include the [ISO country code letters](https://en.wikipedia.org/wiki/List_of_ISO_3166_country_codes) for the no-color version via the `line-supplement` layer.

![blank flag](https://github.com/hfg-gmuend/openmoji/raw/f7c54bfd76983c3bde00a1cb844216100ab4355b/black/72x72/1F1E9-1F1EA.png)

**Comment by b-g** [comment]
Hi @eltos, Nice to e-meet you! Yes this is a good idea to improve this! Especially as the hexcodes of the flags already holds this info:

![2020-05-26 at 13 08](https://user-images.githubusercontent.com/480224/82894131-604cc500-9f52-11ea-91ce-55dd437cc00f.png)

However we a quite busy with other things ... hence if you would like to see it fast ... you will have to help / take care of it / support it :)

**Comment by b-g** [comment]
Closed due to inactivity. Please re-open if you want to give it another try :)
