### ISSUE TITLE
Duplicate EMoji

### ISSUE THREAD

**Issue by Michele0512** [hfg-gmuend/openmoji#242]
There are two brain (1F9E0 and E319) and two plaster/adhesive band (E306 and 1Fa79).

I believe that is because brain and adhesive band were released in 2019 but they were already present in openmoji as extra. 
I definitely prefer the more recent plaster: 1FA79.

**Comment by Michele0512** [comment]
I have just noticed that it was already reported with a much longer list

**Comment by carlinmack** [comment]
no worries! feel free to contribute to the discussion there with your thoughts :)

since the last release E306 has improved but I also prefer 1FA79 :)

![image](https://user-images.githubusercontent.com/6676843/85046179-0ceb2280-b15e-11ea-9f9c-29abb4176183.png)
