### ISSUE TITLE
Redesign Croatian flag

### ISSUE THREAD

**Issue by ak-42** [hfg-gmuend/openmoji#247]
Hello Opemoji team

I hate to do this because I do highly value this project, and I realise that it is a stylised simplification of the overly complex Croatia flag, however...

Your current design bears strong resemblance to the flag of Nazi era puppet state, so called Independent State of Croatia aka NDH.

While there is no argument that Croats have used the checker board shield for hundreds of years, the design where the shield stands alone (without a crown) was used by the NDH. The crown is the key, and while you have put the line above the shield, the line is not connected to the shield, thus shield is visually on its own. Furthermore, the current day Croatian shield has a red square in the very top left of the shield while the old NDH design has a white square on the very top left. Your design also has a white square in the very top left, thus unambiguously indicating this is an NDH flag.

Just for the sake of historical context, around 400 000 people were murdered under the flag of NDH by the Ustaše regime under the patronage of Nazi Germany, and NDH ran the largest and most brutal concentration camp outside of Nazi Germany, Jasenovac camp. Please have a look through [https://en.wikipedia.org/wiki/The_Holocaust_in_the_Independent_State_of_Croatia](https://en.m.wikipedia.org/wiki/The_Holocaust_in_the_Independent_State_of_Croatia)

If you are going to redesign the flag, I strongly suggest the redesign follows following rules if you want to avoid NDH association:

- The shield must have a crown that is visually attached to the top of the shield. Omit the coats of arms that are found in the crown on the actual flag if you must, but the crown shape must be preserved.
- The top left most quare must be red, just like modern day Croatian flag.
- The outline of the shield should not be particularly thick, or at least the border of the top of the shield must be as prominent as the rest. Another common NDH design is to nestle the shield inside of the letter U for Ustaša (name of the party, equivalent to Nazi in Germany). This would often be done by making the U shape (without the top border) in the shield itself more prominent.

Thank you for your work on this great project.

**Comment by b-g** [comment]
Dear @ak-42, many thanks for reporting this! Sorry that we've got it wrong! But to speed up this and to minimize iterations I would kindly ask to be more visually -> to provide a very rough sketch or a screenshot of the existing ones with annotations ... which we then can use to fine tune a new version. Would that be possible for you?

**Comment by ak-42** [comment]
This is the current Croatian coat of arms found on the modern flag. -> https://upload.wikimedia.org/wikipedia/commons/thumb/c/c9/Coat_of_arms_of_Croatia.svg/604px-Coat_of_arms_of_Croatia.svg.png
It consists of two key parts. The shield portion and the crown, which is visually attached to the shield. The shield's checker board has a red square in the top left of the shield.

This is the historic NDH flag. -> https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/Flag_of_Croatia_%281941%E2%80%931945%29.svg/3000px-Flag_of_Croatia_%281941%E2%80%931945%29.svg.png
Note that it consists of a shield in a slightly different shape, and lacks any crown whatsoever. It has a white square on the top left of the checker board pattern.

To avoid associations with NDH, a stylistic redesign must have:
- shield in the shape of modern Croatian flag (no sharp point at the bottom) and it must have a red square in the top left, with the rest of the design following the checker board pattern from there
- it must have a crown shape, retaining the spiky look of the crown, with the ends of the crown being visually attached to the top of the shield

I hope that helps.

**Comment by b-g** [comment]
Hi @ak-42 is this better! :) Please confirm. I would go with 3.

<img width="741" alt="Screen Shot 2020-07-08 at 15 51 40" src="https://user-images.githubusercontent.com/480224/87017803-bf982900-c1d0-11ea-9c4a-956ec0a355c9.png">
<img width="553" alt="Screen Shot 2020-07-08 at 17 16 40" src="https://user-images.githubusercontent.com/480224/87017812-c1fa8300-c1d0-11ea-9b8b-77f5f4fd2300.png">
<img width="774" alt="Screen Shot 2020-07-08 at 18 11 09" src="https://user-images.githubusercontent.com/480224/87017816-c2931980-c1d0-11ea-931c-7ba77b780725.png">

**Comment by ak-42** [comment]
From the perspective of the resemblance to the NDH flag, all three are good. I don't think any reasonable person could claim any of those look similar to the NDH flag. Attached crown and the top left square is red.

From personal aesthetic preference, I do agree with option no 3, but it feels to me that the blue crown is just a touch too tall/narrow. Maybe if it was shrunk just a bit.

**Comment by b-g** [comment]
Many thanks! Done. Might take a while until we have time for a release. Please use in the meantime the files in the master branch, see https://github.com/hfg-gmuend/openmoji/commit/42de852ec5a9fad4af75a99081f4e58bd5563c5b.
