### ISSUE TITLE
Emoji search in natural language

### ISSUE THREAD

**Issue by amitkoth** [hfg-gmuend/openmoji#253]
Is the search for emojis at https://openmoji.org/library/#search=testing%20github open source too? 

How is it build exactly? 

I want to be able to type any sentence at all and get back the best-match emoji. 

How could I achieve that?

**Comment by b-g** [comment]
Many thanks for the interest! 

Yes the openmoji.org is open source as well. Check: https://github.com/hfg-gmuend/openmoji.org

The fuzzy search is powered by fuse.js and the dataset is in `data/openmoji.json`
