### ISSUE TITLE
Padding around emoji images (4px)

### ISSUE THREAD

**Issue by vavrecan** [hfg-gmuend/openmoji#257]
I was wondering, why there is padding 4px around original emojis as the other libraries do not have any 
for example "😀":

in twemoji
https://twemoji.maxcdn.com/v/13.0.0/svg/1f600.svg

facebook 
https://raw.githubusercontent.com/iamcal/emoji-data/master/img-facebook-96/1f600.png

openmoji 
https://raw.githubusercontent.com/hfg-gmuend/openmoji/master/color/svg/1F600.svg

This extra padding makes emoji smaller and therefore harder to see in web / mobile apps. 

What is the reason for this padding?

I decided to write simple script that removes this excessive padding - https://github.com/vavrecan/openmoji-mod

**Comment by carlinmack** [comment]
hey, just to let you know that there is some discussion about this issue here https://github.com/hfg-gmuend/openmoji/issues/112#issuecomment-629439112 I can advise if you have any thoughts :)

**Comment by b-g** [comment]
Many thanks for the script and effort!

> What is the reason for this padding?

I'm afraid but this padding is on purpose:

<img width="179" alt="Screen Shot 2020-10-07 at 14 59 35" src="https://user-images.githubusercontent.com/480224/96090882-28c2c300-0ec9-11eb-8592-7cdd9b5a68c3.png">

We approach the whole topic a bit more "visually" and not so much "technically" does it perfectly fit in a square. The padding allows us to make exceptions which make visually most sense.

However I see your point but unfortunately no quick silver bullet. Removing the padding is too simple as we don't want to have different sizes and it is important that the underlying grid stays intact (see grid layer in src files).

Plus your openmoji-mod is really fun! You might want to consider to add it to the Community Extensions in the README.md.

Will close the issue as I don't see a solution. Please re-open if I missed something.

**Comment by vavrecan** [comment]
thank you! I understand.
Do you think it would be possible to make other face emojis closer to other platforms?
For example hugging face emoji https://emojipedia.org/hugging-face/ or Smiling Face with Hearts https://emojipedia.org/smiling-face-with-hearts/
to have hands / hearts closer to face circle? If this would be done then it would be possible to automatically cut emojis to consistent size.

**Comment by b-g** [comment]
Many thanks for your understanding!

I guess yes this would theoretically be possible ... however the ratio of effort and what we would potentially get from it, makes it a low priority. OpenMoji is non commercial, think love/hobby project, hence we have to realistic in terms of priorities. Top prio is always to support new emojis, to have fun with the project and to make it as accessible as possible for everyone. Hence I'm frankly not very optimistic that someone will every take care of your suggestion. I'm sorry.

**Comment by carlinmack** [comment]
I think that we would potentially get a lot from it ![photo](https://user-images.githubusercontent.com/6676843/82107438-98077180-96f5-11ea-871d-21a8211e9e59.png)

but agree otherwise

**Comment by vavrecan** [comment]
I would say it is around like 10 or 20 emojis that need to be changed like that. What do you think?

**Comment by b-g** [comment]
@vavrecan Could you create a list with links so that we could look into? (This is not a promise that it will happen ... but ca. 10 sounds a lot more feasible :)

**Comment by vavrecan** [comment]
thank you! here is the list that i made from utf-8 emoji list of smileys section

https://raw.githubusercontent.com/hfg-gmuend/openmoji/master/color/svg/1F602.svg
https://raw.githubusercontent.com/hfg-gmuend/openmoji/master/color/svg/1F923.svg
https://raw.githubusercontent.com/hfg-gmuend/openmoji/master/color/svg/1F970.svg
https://raw.githubusercontent.com/hfg-gmuend/openmoji/master/color/svg/1F914.svg
https://raw.githubusercontent.com/hfg-gmuend/openmoji/master/color/svg/1F917.svg
https://raw.githubusercontent.com/hfg-gmuend/openmoji/master/color/svg/1F624.svg
https://raw.githubusercontent.com/hfg-gmuend/openmoji/master/color/svg/1F613.svg	
https://raw.githubusercontent.com/hfg-gmuend/openmoji/master/color/svg/1F631.svg
https://raw.githubusercontent.com/hfg-gmuend/openmoji/master/color/svg/1F976.svg
https://raw.githubusercontent.com/hfg-gmuend/openmoji/master/color/svg/1F92C.svg
https://raw.githubusercontent.com/hfg-gmuend/openmoji/master/color/svg/1F927.svg
https://raw.githubusercontent.com/hfg-gmuend/openmoji/master/color/svg/1F92D.svg
https://raw.githubusercontent.com/hfg-gmuend/openmoji/master/color/svg/1F973.svg

other minor
https://raw.githubusercontent.com/hfg-gmuend/openmoji/master/color/svg/1F624.svg
https://raw.githubusercontent.com/hfg-gmuend/openmoji/master/color/svg/1F92F.svg
https://raw.githubusercontent.com/hfg-gmuend/openmoji/master/color/svg/1F92E.svg

https://emojipedia.org/face-with-tears-of-joy/
https://emojipedia.org/rolling-on-the-floor-laughing/
https://emojipedia.org/smiling-face-with-hearts/
https://emojipedia.org/thinking-face/
https://emojipedia.org/hugging-face/
https://emojipedia.org/downcast-face-with-sweat/
https://emojipedia.org/face-screaming-in-fear/
https://emojipedia.org/cold-face/
https://emojipedia.org/face-with-steam-from-nose/
https://emojipedia.org/face-with-symbols-on-mouth/
https://emojipedia.org/face-vomiting/
https://emojipedia.org/sneezing-face/
https://emojipedia.org/face-with-hand-over-mouth/
https://emojipedia.org/partying-face/

**Comment by b-g** [comment]
Thanks! We will have a look ...
