### ISSUE TITLE
what would an openmoji stick figure look like?

### ISSUE THREAD

**Issue by fuddl** [hfg-gmuend/openmoji#258]
There are a few [stick figures in unicode](https://www.unicode.org/charts/PDF/U1FB00.pdf):

![stick figures](https://user-images.githubusercontent.com/842548/90270111-fad5e980-de59-11ea-902e-c10fe241a58e.png)
![stick figures](https://user-images.githubusercontent.com/842548/90270105-f90c2600-de59-11ea-88c1-b24538617321.png)

I don't think they would look like the full body _person_ emoji:
![](https://openmoji.org/data/color/svg/1F9CD.svg)

What do you think a stick figure should look like?

**Comment by dnlutz** [comment]
"symbols for legacy computing" is a really cool new unicode block ; )
the stick figures could look like this?
<img width="513" alt="stick_figure" src="https://user-images.githubusercontent.com/38292227/95301254-a3b02c00-0880-11eb-9320-3100d59a120e.png">

**Comment by loominade** [comment]
how about having it like a _skeleton_ version of the regular people?

![skeleton](https://user-images.githubusercontent.com/11677380/95309577-9e0c1380-088b-11eb-91e2-9376c3fc1b56.png)

**Comment by dnlutz** [comment]
also an interesting option!
however further away from the unicode stick figure template.
the dress looks quite tight ; )

**Comment by loominade** [comment]
I suppose it doesn't have to look exactly like the one in the unicode chart.

**Comment by loominade** [comment]
I think this dress looks more comfortable:

![more comfortable](https://user-images.githubusercontent.com/11677380/95316642-6190e580-0894-11eb-8986-fdd7dd9bc35f.png)

**Comment by b-g** [comment]
Hi @fuddl, hope this ping finds you all well! This is just a quick heads up ... there will be soon an OpenMoji v13.0 release. Would be lovely to have the stick figures in it too (+ sidenote: did you ever contribute the nice Firefox logo?). Many thanks for all the nice contributions!! 🙏 Best, Benedikt

**Comment by fuddl** [comment]
For completeness I wanted the dressed version to be able to do the same as the naked one. But those would be openmoji extra.

   ↘                          | Stick figure… | …with dress
---------------------|--------------|--------------
…                              | ![stick figure](https://user-images.githubusercontent.com/842548/97964221-b3a42880-1db8-11eb-969a-c340156813c3.png) | ![stick figure with dress](https://user-images.githubusercontent.com/842548/97964241-bbfc6380-1db8-11eb-8554-3ae705a051bd.png)
**…with arms raised**  | ![stick figure with arms raised](https://user-images.githubusercontent.com/842548/97964283-cd457000-1db8-11eb-874d-bfd8e6c3e2a0.png) | ![stick figure with arms raised and dress](https://user-images.githubusercontent.com/842548/97964314-d8989b80-1db8-11eb-9ba1-cf3dfa77dd52.png)
**…leaning left**          | ![stick figure leaning left](https://user-images.githubusercontent.com/842548/97964356-ef3ef280-1db8-11eb-8f00-16598c82a737.png) | ![stick figure with dress leaning left](https://user-images.githubusercontent.com/842548/97964363-f0701f80-1db8-11eb-8854-49dd03a8b95b.png)
**…leaning right**        |  ![stick figure leaning right](https://user-images.githubusercontent.com/842548/97964426-0c73c100-1db9-11eb-9be6-86536cabdf3c.png) | ![stick figure with dress leaning right](https://user-images.githubusercontent.com/842548/97964428-0d0c5780-1db9-11eb-9c55-b1a23a16a0f8.png)

If you want me to commit them give me a sign. 🙂

**Comment by dnlutz** [comment]
yes please! i especially like the expressive leaning left and right figures ; )

**Comment by fuddl** [comment]
The question has been answered
