### ISSUE TITLE
Consider a non-attribution licence (in some cases)?

### ISSUE THREAD

**Issue by Convincible** [hfg-gmuend/openmoji#262]
Hi there,

Would OpenMoji consider a licence that does not require attribution? – if not for all the emoji, perhaps for some subsets, or in some situations?

This is such a great project which I'd really like to make use of. In particular, your collection of simplified country flags is invaluable for any project that needs to represent countries in a very small space. However, it may be hard or undesirable in many cases to include an attribution, for instance if the emoji is used in a single small image file designed for web display.

I am of course a full believer in giving credit and recognising your good work. At the same time, from what I understand of the "project intent", you have a genuine desire for OpenMoji to be a generally useful free resource that helps designers and UX people everywhere (and others). Not requiring attribution would open up many more use cases for your work.

Options might be:

- The "Unsplash model": essentially "please attribute us, but you don't have to"
- The "Noun Project" model: attribute us, or pay a small fee and then no need
- Attribution not required if emoji are only a small element within a larger design
- Apply to us for non-attribution usage (charities, open source projects, your criteria)
- Attribution required only once somewhere on a central website, not on each design piece
- Just allow non-attribution use across the board

Would like to know how you feel about this proposal.

Thanks!

**Comment by carlinmack** [comment]
as far as I know we currently allow the 5th option (Attribution required only once somewhere on a central website, not on each design piece) but would need to get permission from b-g who is the principle lead of the project. This isn't permission, but I would be in favour of pretty much all those options as attribution can be a barrier to use. But as I mentioned b-g has the final word in this :)

**Comment by mavit** [comment]
If the licence is under consideration, it's worth noting that the [SIL Open Fonts License](https://scripts.sil.org/cms/scripts/page.php?item_id=OFL) is designed specifically for fonts.

**Comment by fuddl** [comment]
I suppose every contributor needs to agree on this. I'd be in.

**Comment by CuliTif** [comment]
Quick somewhat related question: I'm working on a wiki for Food Not Bombs (a mutual aid group) and was interested in using a lot of the fruit/veggie icons. Would attribution on the file pages for the icons be enough?

**Comment by b-g** [comment]
Hi @mavit, Yes it seems obvious that CC is not very suited for some cases e.g. font files. Maybe we could say only the **exported font files** would go under a different non-attribution license? It is a bit shady but we have a similar problem with e.g. the OpenMoji-Stickers in iOS. If you text a message with an OpenMoji there is no CC credit underneath the "image" in the chat.

Thoughts?

**Comment by mavit** [comment]
> Maybe we could say only the **exported font files** would go under a different non-attribution license?

I'm not a lawyer, but, to make that work, I think you'd need to own the copyrights on the source files, since otherwise the exported files would inherit the licence of the sources and you'd have no right to grant an alternate licence.  You could require all contributors assign you their copyrights (and some people [think this is a good idea](https://www.gnu.org/licenses/why-assign.html) anyway), but it's a barrier to contribution and a lot of paperwork.

**Comment by b-g** [comment]
Ok. Many thanks for the thoughts. I guess then we can close this issue as we will and have to stick with CC in terms of licenses.

**Comment by Convincible** [comment]
@b-g Sorry to immediately comment after you just closed this!

I think @mavit was saying that if the decision was to _retain a restrictive approach with an exception for font files_, then you'd need contributors to agree to special licences, which wouldn't work.

I proposed that OpenMoji adopt a less restrictive approach across the board – that is, not requiring attribution for many other uses – going way beyond an exception for fonts.

Would you consider this to allow OpenMoji to be used in many other situations, where CC-BY is a barrier?

**Comment by b-g** [comment]
No worries ... 

RE: Would you consider this to allow OpenMoji to be used in many other situations, where CC-BY is a barrier?

Yes I can think of many situations e.g. album of record cover ... where you don't want give credits directly. Because of this we had from the beginning this hint, see README.md

> As an open source project, attribution is critical from a legal, practical and motivational perspective. Please give us credits! Common places for attribution are for example: to mention us in your project README, the 'About' section or the footer on a website/in mobile apps.

However I don't think it is realistic to approach all our contributors to make bigger changes ... so I guess we will / have to stick with it?

**Comment by b-g** [comment]
Closing this. Don't see any quick solution to make this happen :)

**Comment by carlinmack** [comment]
sorry can you clarify what you mean by this?

> However I don't think it is realistic to approach all our contributors to make bigger changes ... so I guess we will / have to stick with it?

**Comment by b-g** [comment]
@carlinmack I don't think "we" (or maybe better "me") could file 70+ legal contracts to have the discussed legal foundation to make really big changes on the licence. OK?

**Comment by carlinmack** [comment]
ah I see, I was unclear with what bigger changes meant. I think it would actually be more along the lines of https://cla-assistant.io but still quite a bit of effort :)

**Comment by b-g** [comment]
Good idea ... but just a fraction of the contributors have actually a Github account (most of the HfG students).

**Comment by carlinmack** [comment]
Public discussion of our license https://news.ycombinator.com/item?id=28403894
