### ISSUE TITLE
Special interest emojis: produce items

### ISSUE THREAD

**Issue by kneeluck** [hfg-gmuend/openmoji#264]
Hey, I'm working on a wiki project for a group called Food not Bombs that does work to make meals for houseless folks out of excess produce that might otherwise be wasted. I'd like to use this project to have a consistent style across the wiki for fruit/veggie icons, but there are a few non-unicode icons that I'd find really helpful.

I'm practicing graphic design and hope to eventually make these myself, but I know that will take a while. So I wanted to make a post here for some of the icons I'd really like just in case there was someone else interested in helping out. 

Produce items we'd need most immediately:
- white mushroom (like not the poisonous Amanita muscaria that's usually presented)
- zuchinni and other squash (this is complicated because there are two main types: softshell summer squash, like yellow squash or zucchini, and hardshell winter squash, like pumpkins. In addition, there's also stuff like butternut squash which is a different species of squash and looks more distinct. I think this can be boiled down to having 3 additional emojis: zucchini, yellow squash, and butternut squash)
- cauliflower 
- ginger (the root not the hair color)
- jicama

Stuff we'd need eventually:
- asparagus 
- breadfruit
- more citrus: lime, grapefruit, orange
- more stonefruit: apricot, plum, 
- guava
- peas and beans 
- lychee
- tomatillos
- okra
- green grapes

I know some of these suggestions might seem strangely specific, but these are partially based on produce my FNB chapter actually deals with a lot of. Some of these might also be hard to work on due to how similar they look to other produce, but those small differences in appearance often represent large botanical differences which in turn represent differences in the ways they're cooked, how to best store them, and the ways different cultures have interacted with them. So I hope that's a good enough justification for the creation of a special interest group 

Anyways, just wanted to thank all the contributors of this really awesome project. Like I said, I'd like to eventually work on these myself, but would definitely love to have a more experienced designer work on them if they get the chance

**Comment by kneeluck** [comment]
Also, relevant emojis being added in Unicode 13: blueberries, olives, bell pepper

There are also movements to get some of these emojis included in upcoming updates (like the pea emoji)

**Comment by kneeluck** [comment]
I've also noticed some emojis that don't line up with the OpenMoji style guide. I don't remember all the issues I saw, but I'm gonna start keeping a running list here and come back and update as I find them again:

- the 🍇 emoji uses the dark variation of purple instead of the light version and uses the light version for shading instead of the other way around
- the 🍎 emoji (the red version not the green) has a couple issues. The borders close all the way (no open contour, see green apple for a better model) and in addition they use light gray to add shine to the apple. This is an added detail that none of the other fruit have and I think goes away from the goals. In addition, the placing of the stem hole makes it so the apple has a 3d perspective instead of being flat like the style guide says (And like the green apple does well)
- I don't have anything too specific, but the 🥒 emoji could do better. It's much too curvy and round for a cucumber and it looks more like a germ
- the 🍅 uses the darker green for the leaves instead of the lighter green 
- just like the 🍎 emoji, the 🍊 emoji uses a 3d perspective for the stem instead of a flat one

**Comment by kneeluck** [comment]
it's october tho

**Comment by b-g** [comment]
Hi @kneeluck, 

many thanks for the feedback and interest! 

Yes there is always room for improvement, and yes more fruit & veggis emojis would be nice ... however you would have to contribute them on your own. We are busy with maintaining and finish off the remaining ones to fulfill Unicode 13 (see #138, nearly there). Hence we won't be able to help you actively creating those emojis. 

Will close the issue now. Please re-open if you would like to continue the conversation ... or otherwise simply propose small PRs step by step :)

**Comment by carlinmack** [comment]
PS I love your feedback on the individual emojis and will move them to #142 or #143 :)

**Comment by carlinmack** [comment]
I think we could also have the capacity to have an edible mushroom emoji as the main emoji :) Thanks for the detailed list of common fruit and veg that are missing!

**Comment by carlinmack** [comment]
Added all your comments to #142 :) I'll tag you after I've closed the easy ones
