### ISSUE TITLE
Improve the flag of Singapore

### ISSUE THREAD

**Issue by Funmoring46** [hfg-gmuend/openmoji#265]
Hello, the singapore star is not a star it is a dot. Can you make it into a star?
![1F1F8-1F1EC](https://user-images.githubusercontent.com/71857158/94978249-61c66500-04d1-11eb-8f3a-cfab5b8481e3.png)
![image](https://user-images.githubusercontent.com/71857158/94978265-77d42580-04d1-11eb-8afb-8ec04964538e.png)

**Comment by Funmoring46** [comment]
> 🏝 OpenMoji is on hold over summer (project maintainers are out of office until Oct 2020).

?????

**Comment by Funmoring46** [comment]
It's Oct 2, 2020!!!

**Comment by Funmoring46** [comment]
#124

**Comment by Funmoring46** [comment]
f

**Comment by Funmoring46** [comment]
f

**Comment by Funmoring46** [comment]
l

**Comment by Funmoring46** [comment]
l

**Comment by Funmoring46** [comment]
l

**Comment by Funmoring46** [comment]
j

**Comment by carlinmack** [comment]
Can you please stop commenting single letters. We will get back to you

**Comment by Funmoring46** [comment]
OK

**Comment by carlinmack** [comment]
I've had a look and you're right, feel free to make a PR if you want :)

**Comment by b-g** [comment]
Hi @Funmoring46, Many thanks for the interest! This is on purpose e.g. see also flag of USA ... there is simply not enough resolution and OpenMoji in general aims to simply boldly. I hope this works for you too.

**Comment by carlinmack** [comment]
We have small stars for Christmas Island, Tokelau, etc? 

I feel the american flag simplification works because the stars are much smaller and closer together, here they are quite big and spaced out

**Comment by b-g** [comment]
OK good point. I would vote for as it is. But if you want to change it ... will not veto. Here is a comparison in small size ... I still think dots are better as not enough resolution.

<img width="435" alt="Screen Shot 2020-10-09 at 10 01 15" src="https://user-images.githubusercontent.com/480224/95558502-9af15e80-0a16-11eb-9ac8-07fd6e5207e3.png">
