### ISSUE TITLE
Copyright Question

### ISSUE THREAD

**Issue by XYZI0N** [hfg-gmuend/openmoji#267]
I am making some cover art for a friend of mine for his music album and my question is how am I able to give credit to Openmoji in this sense? If I were to add a message in the picture that the stuff was made by Openmoji, the text will take away from the overall image. So I don't want to add any unnecessary text or copyright info in the picture. I don't even include my own name as the artist for these types of projects so I'm not sure how to go about giving proper credit.
![Dumb Smart Deluxe Emoji Version](https://user-images.githubusercontent.com/45477261/95254748-5c795b00-07ee-11eb-92c4-480f6a11dbdf.png)

It says: 

> This means you are free to:

Share — copy and redistribute OpenMoji in any medium or format
Adapt — remix, transform, and build upon OpenMoji
for any purpose, even commercially.
Under the following terms:

Attribution — You must give OpenMoji appropriate credit, and indicate if changes were made (e.g. like we do in our changelog). You may do so in any reasonable manner, but not in any way that suggests the OpenMoji Project endorses you or your use.

What classifies as appropriate credit?

**Comment by inferno986return** [comment]
I'm not a lawyer but I would add tiny attribution text to your work to credit the OpenMoji project. 

If the album art is just the cover then do this on the cover itself, of there's a tracklist on the back then I would do it there. Something to think about. 😃

**Comment by b-g** [comment]
Hi @XYZI0N! Nice cover! :) Please credit OpenMoji somewhere else e.g. small text inside in the booklet ... and we are good, see https://github.com/hfg-gmuend/openmoji#attribution-requirements. Good luck with the album!
