### ISSUE TITLE
Guemil-OpenMoji icons kit

### ISSUE THREAD

**Issue by m-pulgar** [hfg-gmuend/openmoji#269]
Hi! i'm Monserrat Pulgar a collaborator from **Guemil Icons for Emergency**. Guemil is an open source icon initiative oriented to represent risk and emergency situations, so we've been working with this new icons kit of Covid emergency. I'll leave attached the Zip archive where there's the icons that i've been working on with this last time for its review. 

Thank u and stay safe!

[SVG - openmoji.zip](https://github.com/hfg-gmuend/openmoji/files/5459505/SVG.-.openmoji.zip)

**Comment by carlinmack** [comment]
these are so good!! thank you
![image](https://user-images.githubusercontent.com/6676843/97598209-15d9e380-19dd-11eb-9791-250d84fd7b62.png)
I would only suggest maybe having the mask covering the chin? Let me know :)

**Comment by b-g** [comment]
@m-pulgar These are great! Many thanks! Comments:

- Same feeling here, it would be better to have the mask covering the chin ... would also reduce line complexity
- we could better express in the hexcodes of "person with mask" and "person sneezing in elbow" the genders as we have all of the 3 ones:
```
XXXX (person)
XXXX-200D-2640-FE0F (woman)
XXXX-200D-2642-FE0F (man)
```
- I guess the category would be again [extras-openmoji/emergency](https://openmoji.org/library/#group=extras-openmoji%2Femergency), correct? If so ... then the first hexcode should be for gloves: E0AD

OK?

**Comment by b-g** [comment]
Last question ... should `Private Area.svg` replace https://openmoji.org/library/#group=extras-openmoji%2Femergency&emoji=E08B?

**Comment by m-pulgar** [comment]
Hi again! hoping you're all fine and safe, i'll leave down here the Open-Moji with the feedback you guys gave me last week! 
**Some comments**: I fix the mask and now is covering the chin and fix the hexcodes as Benedikt told me. 
And for your question, yes! that one replace E08B. It's an iteration with E0A8. 
I'll wait for your comments,

Stay safe!

[SVG-OPENMOJI.zip](https://github.com/hfg-gmuend/openmoji/files/5497503/SVG-OPENMOJI.zip)

**Comment by carlinmack** [comment]
![image](https://user-images.githubusercontent.com/6676843/98313459-e65d4500-1fa1-11eb-8a14-78a81dc7aa59.png)
thanks, looks great!

**Comment by b-g** [comment]
Hi @m-pulgar, great + many thanks! I've added everything to the library https://github.com/hfg-gmuend/openmoji/commit/2deb9c60315197955d5362172b45d3e30c3e1a7a. Will be released with upcoming OpenMoji v13 soon. Perfect timing! Stay save and all the best!

@carlinmack could you cross check my "DEnglish" annotations in `data/extras-openmoji.csv`?
