### ISSUE TITLE
Rainbow Flag

### ISSUE THREAD

**Issue by p4cx** [hfg-gmuend/openmoji#27]
It is possible to recreate the rainbow-flag? On every platform it will looks like the pride flag, except on yours. It would be nice, if it could be change to the same shape (rectangle) like the national flags. 
[look here](https://emojipedia.org/rainbow-flag/)
It's even possible with your colour palette. [White](https://openmoji.org/library/#search=rainbow&emoji=1F3F3-FE0F-200D-1F308) isn't even a part of a rainbow.

**Comment by b-g** [comment]
Hi @p4cx, happy to discuss things ... but please be more visual and add images to the discussion here. It is not 100% clear to IMO what you want us to do ... Even quicker than a long discussion might be simply you producing the flag :) Contributions are welcome!

Please see the [OpenMoji Styleguide ](https://openmoji.org/styleguide/) and a more technical guide [how to contribute](https://github.com/hfg-gmuend/openmoji/blob/master/CONTRIBUTING.md) via Github (only if you are into it).

**Comment by gromain** [comment]
Would something like that be ok @p4cx ?

![1F3F3-FE0F-200D-1F308](https://user-images.githubusercontent.com/2188885/64631287-509e4800-d3e6-11e9-864d-b240c981fc59.png)

However, as stated in [emojipedia](https://emojipedia.org/rainbow-flag/), the flag should be a combination of the waving white flag and the rainbow emojis. Thus a recommendation could be to just replace the bottom white part with the correct purple?
Also, a lot of platforms don't really follow this and their [waving white flag](https://emojipedia.org/waving-white-flag/) is quite different from their rainbow flag so... :man_shrugging: 

What do you reckon?

**Comment by p4cx** [comment]
Wow - thats looks exactly what i had in my mind. Maybe the stripes in the same size? The Red and Purple one are smaller than the others. 
Thanks for your suggestion.

**Comment by gromain** [comment]
Changed it real quick this morning.

@b-g do you want a PR for this?

**Comment by b-g** [comment]
Hi @gromain, Yes please! That would be wonderful! Please overwrite `1F3F3-FE0F-200D-1F308` and change also the author / changelog infos corresponding. Many thanks!!

Now I am just wondering whether we should keep (and fix) the old flag? Opinions? cc @dnlutz 

![1F3F3-FE0F-200D-1F308](https://user-images.githubusercontent.com/480224/64715096-db864d80-d48d-11e9-85e1-bd8a3224df58.png)

**Comment by p4cx** [comment]
Ou, thats looks nice. Way more homogeneity. 
I do not think you should fix something there. With the "white flag" this layout makes sense, but not with the "rainbow flag". The white flag is swung when given up.
The best thing will be if the old flag is simply overwritten with the new one.

**Comment by Sam0711er** [comment]
I’m pro keeping the swing style @b-g. More consistent with Unicode guidelines and other emoji sets, also better distinguished that it’s not a state flag but that it has a different meaning :)

**Comment by b-g** [comment]
@Sam0711er We already decided to overwrite `1F3F3-FE0F-200D-1F308` with the new proposal. Sorry! But it you want to fix the existing rainbow flag flag (remove white stripe, fix sloppy start points of stripes on the left), then we could keep it as an alternative :)

@gromain Ping: Happy to get your PR, any time you are ready :)

**Comment by gromain** [comment]
@b-g I'll send it tonight. I was letting the discussion continue a little bit to see if there was another opinion emerging!
@sam0711er from emojipedia we can see that not all emoji ses are following the guideline... Hence my asking and proposal!

**Comment by gromain** [comment]
Also, Openmoji is now featured in emojipedia! https://blog.emojipedia.org/openmoji-a-free-and-open-source-emoji-set/

**Comment by b-g** [comment]
Yay! Finally! We also integrated emojipedia descriptions texts (we got access to their API) for the emoij detial views on the website e.g. https://openmoji.org/library/#emoji=1F418 

> An elephant, the largest land animal on Earth, with a long trunk and, often, tusks. Generally depicted in gray in full profile on all fours facing…
