### ISSUE TITLE
Consitency of Arrows and Geometric shapes

### ISSUE THREAD

**Issue by fuddl** [hfg-gmuend/openmoji#273]
I hereby propose to make the (black) geometric shapes the darkest shade of grey rather than black. so they look more in line with the arrow symbols:

![arrows and geometric shapes](https://user-images.githubusercontent.com/842548/98465707-0754ae80-21cb-11eb-95d7-eb35b8cca661.png)

**Comment by carlinmack** [comment]
I propose that all shapes should have a full black #000 fill. @b-g you can decide :)

**Comment by carlinmack** [comment]
PS I think you missed the middle square here 
![image](https://user-images.githubusercontent.com/6676843/98466043-0572f700-219b-11eb-87aa-dbab8673d457.png)

**Comment by fuddl** [comment]
see also  #274

**Comment by b-g** [comment]
> I hereby propose to make the (black) geometric shapes the darkest shade of grey rather than black. so they look more in line with the arrow symbols
From my end 👍 + good call, looks nicer! ... But handing over for more feedback to @dnlutz

**Comment by dnlutz** [comment]
i'm also in favor of the darkest shade of grey!

**Comment by carlinmack** [comment]
In favour, but can we adjust these as shown? 
![image](https://user-images.githubusercontent.com/6676843/98544326-d70c1f00-2261-11eb-91b5-8abfe44cb8ab.png)

**Comment by dnlutz** [comment]
👍

**Comment by fuddl** [comment]
I can take care of this if you like

**Comment by fuddl** [comment]
@carlinmack wouldn't you say this is a case for [overlapping contours](https://openmoji.org/styleguide/#open_contour)?

![overlapping lines](https://user-images.githubusercontent.com/842548/98715082-f3a37680-2389-11eb-9f71-dea0261e2382.png)

**Comment by carlinmack** [comment]
How do you know the right one is on top?

**Comment by fuddl** [comment]
well, I decided so 😆

I guess we are allowed interpret what _OVERLAPPING BLACK SQUARES_ means. I suppose _overlapping_ means: one is on the top of another. Unicode does not specify which is on top.

**Comment by carlinmack** [comment]
I actually agree with your interpretation, I was just wondering if you had an intuition behind it. I think this works as we are free to interpret the intent of design, rather than copying the exact character representation :) 

Sorry that this issue couldn't be included in OpenMoji v13.0

**Comment by fuddl** [comment]
I will post a PR over the weekend
