### ISSUE TITLE
Black Stars and Half Stars

### ISSUE THREAD

**Issue by fuddl** [hfg-gmuend/openmoji#274]
Unicode 11 introduced [half stars](http://www.righto.com/2016/10/inspired-by-hn-comment-four-half-star.html) for things like rating systems.

[Miscellaneous Symbols and Arrows](https://www.unicode.org/charts/PDF/U2B00.pdf):
![half stars](https://user-images.githubusercontent.com/842548/98465924-944c3780-21cc-11eb-81f7-54b5f3b29311.png)
in addition to 
[Miscellaneous Symbols](https://www.unicode.org/charts/PDF/U2600.pdf):
![stars](https://user-images.githubusercontent.com/842548/98465965-d2495b80-21cc-11eb-9d49-cdfd7317a605.png)

So I suggest to implement the black star and the two half black stars
![stars and half stars](https://user-images.githubusercontent.com/842548/98465999-0fade900-21cd-11eb-8dcb-7ad40d881bb0.png)

**Comment by b-g** [comment]
@fuddl Nice! Very handy for building user interface etc.! Could you do a PR with the proposed stars above?
