### ISSUE TITLE
Invalid annotation for 2B21-FE0F-200D-1F7E9

### ISSUE THREAD

**Issue by cyberalien** [hfg-gmuend/openmoji#279]
2B21-FE0F-200D-1F7E9 has annotation "brown hexagon", but it should be "green hexagon".

**Comment by b-g** [comment]
Thanks for spotting and reporting! Fixed https://github.com/hfg-gmuend/openmoji/commit/fff1397ab8993773d79b54cc7d4ac2e1242bba6e
