### ISSUE TITLE
About breads…

### ISSUE THREAD

**Issue by fuddl** [hfg-gmuend/openmoji#283]
1. What do you think about this color adjustment on the regular bread?
   ![toast](https://user-images.githubusercontent.com/842548/100511172-ccf98400-316e-11eb-9d0c-f380806c8710.png)
2. the [industry standard](https://emojipedia.org/bread/) for the bread emoji unfortunately is a boring old toast. In my culture, this is not a prototypical bread. For consistency's sake I'd propose to add **an additional** type of bread which I would call **BOULE BREAD**
  ![BOULE BREAD](https://user-images.githubusercontent.com/842548/100513600-83f5ff80-316f-11eb-8d2e-ed9be6b0a51a.png)

**Comment by carlinmack** [comment]
Hello!

I've also been unsatisified with our bread emoji and I think it can be reimagined a little. I think that we should keep it a loaf, but lose the mushroom/muffin-top protusions at the top. I contribute this bread-board to the discussion :) 


![image](https://user-images.githubusercontent.com/6676843/100517716-cf51e300-315a-11eb-877c-fdb8a6b8b1d9.png)

**Comment by b-g** [comment]
@fuddl Nice! Yes the bread world is bigger than toast :) 
1. (standard) = toast like shape of bread (less musshroomy)
2. (alternative) = more "???" style. However I would still call it **loaf bread**, even if we go with the one you are proposing. (@carlinmack what would be a nice wording which is not inter culturally "offensive". First I was thinking "central European style" but this might sound too much for others doing bread the same shape :)

cc @dnlutz

**Comment by dnlutz** [comment]
Toast is a special kind of bread. So I think it is a good idea to add a normal / default bread.
I like the boule bread approach, but i would suggest to make the colour a bit lighter.
At the moment it looks like pretzel pastries (which I really like btw ; ) but pretzel ≠ "normal" bread.

For the toast i would also make it less mushroomier but i would keep the colour,
if we make the left part white it looks a bit like an error.

**Comment by carlinmack** [comment]
just a nitpick, but as a british person "toast bread" is a subset of sandwich or sliced bread :) when I was in America, this was the normal/default bread as it is in the UK
