### ISSUE TITLE
Make 🤭 1F92D more smiling 

### ISSUE THREAD

**Issue by b-g** [hfg-gmuend/openmoji#285]
Stumble upon https://twitter.com/slitherpunk/status/1335326567824646144

<img width="581" alt="Screen Shot 2020-12-14 at 08 26 40" src="https://user-images.githubusercontent.com/480224/102052191-1a6c2700-3de6-11eb-919c-5ca594f5517d.png">

Definition according to https://emojipedia.org/face-with-hand-over-mouth/
"Smiling Face with Smiling Eyes and Hand Covering Mouth"

hence I think we should make https://openmoji.org/library/#search=mouth&emoji=1F92D more smiling ...

**Comment by carlinmack** [comment]
thought it was already covered under #143 but apparently not, good catch!

**Comment by lizbravob** [comment]
and if we add blush on the cheeks and change the eyes? 
![1F92D](https://user-images.githubusercontent.com/60933333/102624221-79050e00-4122-11eb-9db9-a6d236937eb4.png)
 
[1F92D.svg.zip](https://github.com/hfg-gmuend/openmoji/files/5716148/1F92D.svg.zip)

**Comment by carlinmack** [comment]
looks great!

**Comment by b-g** [comment]
@lizbravob Many thanks! Perfect! Just added it with https://github.com/hfg-gmuend/openmoji/commit/879b33797ff4d46bedd7995b0778b6bbb636390a.
