### ISSUE TITLE
Add special face emoji: annoyed face with tongue

### ISSUE THREAD

**Issue by woswos** [hfg-gmuend/openmoji#287]
Hi,
I have realized that both in Unicode and OpenMoji, all face emojis with tongues are smiling. However, people don't necessarily smile while sticking their tongue out in real life. For example, the kid below sticks her tongue out to (possibly) indicate an emotion for being frowned/annoyed while still making fun of the situation.

![speech121](https://user-images.githubusercontent.com/10498874/103476164-ba591700-4dcc-11eb-9f35-1a6859667cc8.jpg)

Of course, everyone would have a different interpretation of her face, but my point is that there is no "tongue out face" emoji without a smile to represent such an emotion.

So, I propose a new face emoji "~~slightly frowning~~ annoyed face with tongue":

<img width="100" alt="Screen Shot 2021-01-03 at 12 26 16" src="https://user-images.githubusercontent.com/10498874/103476301-e1fcaf00-4dcd-11eb-94f9-1ffc84845b35.png">

Please let me know what you are thinking about it. Yes, it kinda looks like a duck :)

**Comment by b-g** [comment]
Hi @woswos, true! Nice idea! Yes would be nice ... but could you do a few iterations more looking into making it less duck like? cc @dnlutz any hints for us to de-duckify the overall appearance? :)

**Comment by dnlutz** [comment]
the openmoji [face with tongue](https://openmoji.org/library/#group=smileys-emotion%2Fface-tongue&emoji=1F61B) features an open mouth with the tongue sticking out of it. what about taking this mouth and just flipping it vertically? that could make the whole face less duck-like …

**Comment by woswos** [comment]
@b-g and @dnlutz, thank you for the interest and suggestion! 

I think it looks worse:

<img width="466" alt="Screen Shot 2021-01-04 at 18 57 44" src="https://user-images.githubusercontent.com/10498874/103548254-f076c380-4ebe-11eb-8bb0-4d61bffa5b7c.png">

I will try to come up with more variations.

**Comment by dnlutz** [comment]
maybe you could try to change the form of the tongue to make it less beak-like?
the two little white spots could become gray or black?
good success!

**Comment by woswos** [comment]
@b-g @dnlutz I gave up on de-duckifying the initial proposal. Making the white spots gray or black doesn't work as well.

<img width="100" alt="Screen Shot 2021-01-14 at 18 09 19" src="https://user-images.githubusercontent.com/10498874/104616461-c0d87000-56a3-11eb-8a38-be0cd8ccbf49.png"> <img width="100" alt="Screen Shot 2021-01-14 at 18 08 43" src="https://user-images.githubusercontent.com/10498874/104616471-c2a23380-56a3-11eb-9e27-d21f81f4acb1.png">

I have a new version that doesn't look like a duck (I hope 😀), and I think it conveys the emotion better:

![Screen Shot 2021-01-14 at 19 58 41 (2)](https://user-images.githubusercontent.com/10498874/104616599-e9f90080-56a3-11eb-8094-aec4f93ad16d.png)

My personal favorite is the one in column 2 - row 1. What do you think?

**Comment by dnlutz** [comment]
… interesting move ; ) i think you new designs show your intentions for the emoji much better.
i also like the one you selected, nice!

**Comment by b-g** [comment]
@woswos Many thanks! Merged with #289!

**Comment by woswos** [comment]
Thanks, everyone!
