### ISSUE TITLE
badger face icon?

### ISSUE THREAD

**Issue by lortas** [hfg-gmuend/openmoji#291]
It would be great, to have a [badger](https://openmoji.org/data/color/svg/1F9A1.svg) face emoji. Similar like the emoji of the [fox](https://openmoji.org/data/color/svg/1F98A.svg)
:-)

**Comment by atharva21-stack** [comment]
Hello Sir/Mam, 
May I solve this issue?

**Comment by carlinmack** [comment]
That would be very much appreciated :)
