### ISSUE TITLE
Wrong color for the flag of Indonesia

### ISSUE THREAD

**Issue by ikabod** [hfg-gmuend/openmoji#296]
The color for the flag of Indonesia (1F1EE-1F1E9) should be #ff0000 instead of the same color as Monaco (#d22f27; 1F1F2-1F1E8). Note: The flag for Monaco on Wikipedia has a slightly different color: #ce1126.

https://en.wikipedia.org/wiki/Flag_of_Indonesia
https://en.wikipedia.org/wiki/Flag_of_Monaco

Btw: The links on the homepage https://openmoji.org/library to decodeunicode.org are broken (e. g. http://www.decodeunicode.org/en/u+1F1EE-1F1E9).

If they can be fixed they should be changed to "https" to avoid unnecessary redirects.

**Comment by carlinmack** [comment]
Hello, the colours on the flags use the most similar colour from the [colour palette](https://openmoji.org/styleguide/#color). This was a design decision from the beginning of the project. We will update the links to https, thanks

**Comment by b-g** [comment]
Hi @ikabod, 

yes this was design decision that the color palette should stay minimal. We even introduced a couple of colors to address the flags.

> If they can be fixed they should be changed to "https" to avoid unnecessary redirects.

thanks for spotting! Done and deployed. Cheers!
