### ISSUE TITLE
Tag icon

### ISSUE THREAD

**Issue by wkoszek** [hfg-gmuend/openmoji#308]
It'd be nice to have an icon similar to this one:

<img width="194" alt="image" src="https://user-images.githubusercontent.com/483344/114344592-f9f27600-9b14-11eb-8008-5992abfd4750.png">

Or this:

<img width="532" alt="image" src="https://user-images.githubusercontent.com/483344/114344618-04147480-9b15-11eb-9040-04c363f30b37.png">

**Comment by b-g** [comment]
@wkoszek Many thanks for the suggestion! Yes! What about giving it a try! :) Happy to discuss your sketches here ...

**Comment by loominade** [comment]
there already is [🏷](https://openmoji.org/library/#emoji=1F3F7)

**Comment by b-g** [comment]
Closing. Solved with https://openmoji.org/library/#emoji=1F3F7
