### ISSUE TITLE
How to credite OpenMoji on packaging ?

### ISSUE THREAD

**Issue by lexlam** [hfg-gmuend/openmoji#309]
Hello OpenMoji ! 

I'm working for a small French company which is specialiazed into natural solid cosmetics. 
Looking for open-source emoji libraries to use it on our future packaging in combinaison with descriptif text, we found out OpenMoji which is certainly the most qualitative. So thank you for creating it and making it available to the public ! 

We reviewed the attribution requirements and we care about doing it correctly. So, to be perfectly sure to respect your work, here is my question: how can we correctly credite you on our packaging ? Do we have to print a special mention about OpenMuji and the license CC-BY-SA 4.0 ?

Thanks a lot for your answer !

Regards,

Alex

**Comment by b-g** [comment]
Hi Alex! 

Many thanks for the interest. We are aware of the problem that sometimes there is simply not enough space to print the credits ... what about a compromise? Maybe:

Minimal super tiny credits on the package:
> Emojis by OpenMoji

And then full credits on the package insert:
> All emojis designed by OpenMoji – the open-source emoji and icon project. License: CC BY-SA 4.0

See also:
https://github.com/hfg-gmuend/openmoji#attribution-requirements
https://github.com/hfg-gmuend/openmoji/blob/master/FAQ.md

Would that work?

+ We love to see OpenMojis in the wild. You are very welcome to post the results here #125 :)

**Comment by lexlam** [comment]
Hi Benedikt !

Thanks for your quick answer. 

Indeed, space is one of the main problems we face when designing a new packaging: each word counts :)

The compromise you suggest seems perfectly achievable and suits to us ! Now we know exactly how to correctly credite OpenMoji on our packaging :) 

We are only at the beginnings of the development of our project but we will certainly share the results with you !

**Comment by b-g** [comment]
Best of luck with it! Looking forward to! :)
