### ISSUE TITLE
Climate & environment

### ISSUE THREAD

**Issue by laem** [hfg-gmuend/openmoji#310]
Hi, I wonder if a task force is already working on bringing more emojis to this category https://openmoji.org/library/#group=extras-openmoji%2Fclimate-environment.

Lots of ideas and needs :)

**Comment by b-g** [comment]
Hi @laem Many thanks for the interest. Nothing planned. But we are happy to have contributions on this topic. PRs are welcome :)

**Comment by laem** [comment]
Well I'll start here with some ideas : https://github.com/laem/openmoji-environment/blob/master/coal-plant.svg
