### ISSUE TITLE
Why is there a transparent border around the emojis?

### ISSUE THREAD

**Issue by Quasarman** [hfg-gmuend/openmoji#312]
Hello,

I was wondering why each emoji image is "warpped" with a transparent border and does not have the full size? This is really unintuitive if settings the emoji image to be a fixed size, e.g., 20px. It appears smaller than the expected size. When comparing the pictures to the twemoji assets they do not have this border and therefore will correctly be displayed with 20px size if configured that way.

The reason why I am asking is that I like to use alternatives in my application (default, twemoji and openmoji) but the fact that the space/size is not consistent would take additional effort to remove the transparent outline in the case of openmoji. The images below show this behavior, all images have been set to 20px:

![image](https://user-images.githubusercontent.com/30523269/115105970-477e4100-9f62-11eb-9fe3-3b0df3e7b8de.png)

Twemoji
![image](https://user-images.githubusercontent.com/30523269/115106144-6df0ac00-9f63-11eb-97ca-be2d0eafb399.png)

Openmoji
![image](https://user-images.githubusercontent.com/30523269/115106114-3eda3a80-9f63-11eb-889b-ce65d37f931e.png)

**Comment by b-g** [comment]
Hi @Quasarman! 

Many thanks for the interest! You might want to check out this for OpenMojis without a padding :)

https://github.com/vavrecan/openmoji-mod

The whys have been discussed here: #257, #276.
