### ISSUE TITLE
flag icons get blurry when downscaled

### ISSUE THREAD

**Issue by bam80** [hfg-gmuend/openmoji#317]
Hi, we are considering to swap old raster icons used in KDE keyboard layout applet to Openmoji, but faced with the blurring problem: SVG icons looks ugly being fitted to panel size:
https://phabricator.kde.org/T13722#255660
Here I suggested a theory what's going on, not sure about the correctness:
https://phabricator.kde.org/T13722#255709
Could you guys help us by any mean?
@ferdinandsorg

**Comment by b-g** [comment]
Hi @bam80, 

Nice! Glad to see that big project like KDE are even considering OpenMoji :)

Some ideas (brainstorming):
- the native height of the flags is 38 px. You will get non-blurry results if the flag has a height of either 38px or is multiplied with an integer e.g.  38 * 2, 38 * 3 etc. Do these heights by any chance fit with the height of your panel?
- we also have an alpha version of openmoji as color-font. Does the QT renderer support rendering color-fonts with sub-pixel anti-aliasing? If so ... you should get a nice quality output.
- in general you will get nicer results for down-scaling images with a strategy, let's say you target resolution were 64px height e.g. 1. render the svg really big 1024px 2. scale several times by 50%: 512px, 256px, 128px, 64px ... now it should look much better. You could also consider to "round" every color of the final small image to the openmoji color-palette to make it even more crips etc.

Hope this is helpful!

![2021-05-17 at 08 07](https://user-images.githubusercontent.com/480224/118439862-0f942600-b6e7-11eb-99ed-dbdd7fed6709.jpg)

**Comment by bam80** [comment]
Thank you for your answer Benedikt!

- our old icons are mostly 21*14: https://lxr.kde.org/source/frameworks/kdelibs4support/src/l10n/,
but panel can be resized smoothly in real-time.
- I'm not aware about rendering color-fonts, but could try
- yeah, that double-scaling approach came to my mind too. I just considered twice-scaling of original png's.

My personal feeling currently is we need some flag icons theme supporting different sizes.
E.g, raster icons for smallest size and one or more SVG variants for bigger sizes.
Could Openmoji itself provide something like this, or it's out of it's goal and we need to make our own?

**Comment by b-g** [comment]
I see ... 14px is really really small and unfortunately 38/2 is 19 px. Would there be 5px more space to fit it in the panel?

Providing additional pngs is out of scope for us. We currently have 72x72, 618x618 and svgs (see folders `black` and `color`) ... but you could very easily generate them on your own. Basically just modify these lines and run `npm run generate`.

https://github.com/hfg-gmuend/openmoji/blob/master/helpers/export-png.sh#L19
https://github.com/hfg-gmuend/openmoji/blob/master/helpers/export-png.sh#L22

**Comment by bam80** [comment]
> I see ... 14px is really really small and unfortunately 38/2 is 19 px. Would there be 5px more space to fit it in the panel?

It's still ~1.5 times more, but we need to see..
We'll try to generate some samples when get a chance and I'm eager to see how it looks like :) Thanks!

**Comment by b-g** [comment]
Great! Good luck! Let me know if you need pointers in our repo.

The most future proof still would be to render color-fonts ... might be something to investigate in your renderer in the long run.

Will close the issue now. Re-open if there is anything to add.

**Comment by bam80** [comment]
Hello, seems we are having troubles generating the PNGs, because of the dependencies and such.
If it doesn't bother you, it would be cool if you could generate some sample for us, with 19 and 38 px.
Thanks!

**Comment by b-g** [comment]
I'm afraid ... but this is a bit out of scope :) Sorry! But it should be really easy. Install node.js e.g. v14.x and these 3 additional command line dependencies. Should be very Linux friendly, check https://github.com/hfg-gmuend/openmoji/tree/master/helpers#additional-dependencies
