### ISSUE TITLE
Flags just showing as 2 red X squares

### ISSUE THREAD

**Issue by Kxeo** [hfg-gmuend/openmoji#318]
For some reason, this happens on youtube.
Everywhere else it's just fine, and I'm using Firefox here.
![Screenshot 2021-05-15 191928](https://user-images.githubusercontent.com/50978401/118381709-7e706280-b5b3-11eb-9d18-59cc6830b19c.png) 
That was supposed to be the mexico flag.

**Comment by b-g** [comment]
Many thanks for the interest ... but as @carlinmack already has stated

> the fonts are early beta and don't work yet in mainstream browsers, hopefully #260 will solve these issues

Help is welcome. Please read beforehand the entire of #93 and #260 to bring you up to speed.
