### ISSUE TITLE
OpenMoji not working in Opera GX

### ISSUE THREAD

**Issue by Kxeo** [hfg-gmuend/openmoji#319]
Self explainatiory. Opera GX and Opera don't work with OpenMoji. Before, the font wasn't there, but when I use the font, it doesn't do anything. Sometimes it shows a rectangle for flags but it just doesnt work.

**Comment by carlinmack** [comment]
the fonts are early beta and don't work yet in mainstream browsers, hopefully #260 will solve these issues
