### ISSUE TITLE
Venezuela flag error

### ISSUE THREAD

**Issue by OliviaEljest** [hfg-gmuend/openmoji#32]
the flag of venezuela is in reality yellow-blue-red; while it shows as yellow-orange-blue here

**Comment by b-g** [comment]
Hi @OliviaEljest, many thanks for the bug report! It seems the yellow of the flag is kind of in-between:

![1F1FB-1F1EA](https://user-images.githubusercontent.com/480224/65536264-172f0780-ded1-11e9-9f2d-6e8b4155953a.png)
<img width="1399" alt="Screen Shot 2019-09-24 at 13 41 04" src="https://user-images.githubusercontent.com/480224/65536265-172f0780-ded1-11e9-9c34-eee4a440c016.png">

According to https://en.wikipedia.org/wiki/Flag_of_Venezuela the yellow is:

<img width="695" alt="Screen Shot 2019-09-24 at 13 42 37" src="https://user-images.githubusercontent.com/480224/65536338-37f75d00-ded1-11e9-88dc-b8a82eef67c1.png">

Which we don't have in our color palette. We will have to discuss how to deal with this one ... as we want to have a minimal color palette and hence can't accommodate every detail of the flags.

**Comment by MahdiBaghbani** [comment]
I think you don't need to discuss how to deal with yellow color code, it's good idea to stick to the minimal color palette, fixing the flag's color order is all good.

**Comment by b-g** [comment]
Hi @MahdiBaghbani, thanks for pointing this out! :) I think I crossed wires and didn't get that the order is the issue and not the tone of the yellow. This can be easily fixed.

**Comment by b-g** [comment]
Done! https://github.com/hfg-gmuend/openmoji/commit/ee4d66211be53871b6fd3d0ad33d5d8fd50bf9c8
