### ISSUE TITLE
Am I able to embed OpenMoji with Windows so it's displayed everywhere?

### ISSUE THREAD

**Issue by Kxeo** [hfg-gmuend/openmoji#324]
The title explains what I'm saying here, I want to make it so that I can put it into my emoji picker, and allowing me to see the emojis and put them in, then displaying the OpenMoji that I picked.

**Comment by Kxeo** [comment]
This needs the tag "nice to have"

**Comment by b-g** [comment]
Hi @Kxeo, I'm not on Windows so no idea. Sorry! @carlinmack do you know more?

**Comment by carlinmack** [comment]
As far as I know, there is no way to change the default emoji font on windows. I would investigate if this is possible with say Apple emojis and then what type of file needs to be provided.
