### ISSUE TITLE
Blob/Emoji Kitchen

### ISSUE THREAD

**Issue by Extarys** [hfg-gmuend/openmoji#325]
I have no talent in graphic stuff but I was curious to know if there is a plan to implement the blob emoji? (Is that what they are claled?)

I read today [this blog post](https://blog.emojipedia.org/emoji-kitchen-beta-magics-back-the-blobs/) talking about it.

- [Mending heart](https://emojipedia.org/mending-heart/)

Some of them can be implement client side wise though. I'm not sure what would be the nicest approach.
![image](https://user-images.githubusercontent.com/11581433/122293629-364fa300-cec5-11eb-9725-8a5258fbc095.png)

**Comment by b-g** [comment]
Hi there! Many thanks for the interest! But "blob emojis" are exclusively done by Google (for their product e.g. Androind). We won't be stepping on Google's toes and are going to leave the blob world to them. Sorry! All the best
