### ISSUE TITLE
Potential Antarctic Flag Emoji

### ISSUE THREAD

**Issue by townseev** [hfg-gmuend/openmoji#327]
Hey Openmoji community,

I have a potentially complicated question regarding the Antarctic flag emoji that I'd love to have your input on.

Here are the basics:
- The Antarctic flag emoji (🇦🇶) appears as a light blue flag with a white silhouette on all supported platforms.
- **This design has no official status whatsoever.** It was simply the most popular of dozens of unofficial proposals at the time of emoji's creation.
- True South, an Antarctic flag proposed last year, is **the first and only Antarctic flag with official designation**. It has been formally adopted by national Antarctic programs, expedition teams, and other Antarctic organizations from around the world.

Those of us behind the flag plan to approach Unicode and other emoji providers to notify them of the new flag's status. While we anticipate this will lead to a change in their emoji design, we also anticipate this will be a long and difficult process. OpenMoji was created in response to the restrictive, bureaucratic system we're trying to navigate, which is exactly why we're reaching out. We'd be honored to have OpenMoji be the first emoji system to feature the True South design for the 1F1E6+1F1F6 designation.

You can find more information on the new flag and the old proposals on [the Wikipedia page](https://en.wikipedia.org/w/index.php?title=Flag_of_Antarctica&type=revision&diff=1028760400&oldid=1028760277). 

Thanks in advance for your input!

**Comment by joshcoales** [comment]
I was surprised to find that openmoji isn't using this flag yet! So I've created a PR to switch to it, as it didn't seem there was any particular discussion here yet, hopefully that can spark something, or it can be updated

**Comment by carlinmack** [comment]
The decision to recognise the flag seems to have happened in the last month, which explains why we haven't updated it :) Many thanks for the contributed pull request!

**Comment by b-g** [comment]
IMO still no official status, hence: https://github.com/hfg-gmuend/openmoji/pull/366#issuecomment-1012087266
