### ISSUE TITLE
Readme: Github Darkmode Ruins Header Image

### ISSUE THREAD

**Issue by ndom91** [hfg-gmuend/openmoji#328]
Hi everyone, I just stumbled upon your repository here and almost had a heart attack when I saw the image in the header of your readme. It was only after I visited your homepage and saw the "real" version did I realize what had happened.

Github darkmode seems to use the same, or similar color, as its background-color as you do for the "stroke" in some of your emojis. Causing your readme header image to look like this:

<img width="920" alt="Screenshot 2021-07-06 at 22 38 24" src="https://user-images.githubusercontent.com/7415984/124664042-29faac80-deab-11eb-8860-cdd65ec2ec8c.png">

Maybe put the whole image infront of a different colored background or change the stroke color to a slightly different black/dark gray for the readme version of this image 😁

**Comment by b-g** [comment]
Ups. Many thanks for the pointer! Yes we badly need a dark mode soon! Will fix it with a white background.

<img width="1157" alt="71999652-1a60c000-3242-11ea-974a-96fef098147b" src="https://user-images.githubusercontent.com/480224/124712580-c8b0f880-deff-11eb-8516-3def8df2a42e.png">

**Comment by ndom91** [comment]
Ah now that I'm looking at this on another monitor, the black from the stroke and the black background have a bit more contrast. 

On my macbook last night when I created this issue, they looked identical and the yellow "loops" at the top of the fingers made the character look like salad fingers haha.
