### ISSUE TITLE
Mermaid/Merperson/Merman

### ISSUE THREAD

**Issue by mycelialinn** [hfg-gmuend/openmoji#329]
The mermaid has a face matching skin color, while the merman and merperson have a blank face. Everything else about them seems fine.

**Comment by b-g** [comment]
Hi @greenserenabean, many thanks for reporting. Please provide links and images. Thanks.

**Comment by greenserenabean** [comment]
![Screenshot_20210716-145705_Chrome](https://user-images.githubusercontent.com/65576637/126231344-c82d7083-4d4b-4a20-be3b-e30ac32b0632.jpg)

**Comment by Kirylchyk** [comment]
Looks like the issue is resolved, I see consistency. Foe example, <img src="../node_modules/openmoji/color/svg//1F9DC-1F3FF.svg" alt="Emoji" width="100" height="100" />
@mycelialinn please confirm

**Comment by mycelialinn** [comment]
>
