### ISSUE TITLE
Get a recognition from Unicode Consortium

### ISSUE THREAD

**Issue by axelpale** [hfg-gmuend/openmoji#33]
I believe OpenMoji should be listed on the official emoji chart published by Unicode Consortium:
https://unicode.org/emoji/charts/full-emoji-list.html

Only major non-free emoji providers are listed there currently. Thus it should be a no-brainer for the Unicode to include a creative commons alternative to the list.

What do you think?

**Comment by dnlutz** [comment]
So far we had no contact with the Unicode Consortium yet. But I will soon meet somebody who knows the Consortium pretty well, so I will ask him. All in all I think it is a good idea to have OpenMoji linked to the Unicode site.

**Comment by b-g** [comment]
Closing this. Daniel will try to make it happen :)
