### ISSUE TITLE
Issue when using in android. Only outline appears for Openmoji-color

### ISSUE THREAD

**Issue by karthiceaswar** [hfg-gmuend/openmoji#332]
I tried using the openmoji color ttf in my android using magisk. even though its applying it only displays outline.
![photo6314367752604856517](https://user-images.githubusercontent.com/74752653/126075423-16b7ce38-1be7-42f3-9eaf-a975ba266dca.jpg)

**Comment by b-g** [comment]
I'm afraid but the fonts are experimental and not intended for production, see discussion https://github.com/hfg-gmuend/openmoji/issues/93 for updates.
