### ISSUE TITLE
Some black elements in SVG sources are being rendered with current font colour in TTF font

### ISSUE THREAD

**Issue by kevincox** [hfg-gmuend/openmoji#339]
It appears that some strokes on the emoji use the font colour. This looks bad when the font colour is not black as expected.

Example:

```html
<span style=color:black>😃</span>
<span style=color:white>😃</span>
<span style=color:blue>😃</span>
<span style=color:green>😃</span>
```

![image](https://user-images.githubusercontent.com/494012/129491567-47235576-4747-4d27-b410-db9f36770fbf.png)

Expected behaviour:

Most emoji should not incorporate the default font color into the design.

**Comment by b-g** [comment]
Closed as discussed in #340 Sorry!

**Comment by kevincox** [comment]
Sorry why is this closed? This is a bug with the generated TTF files and is still an issue even if you don't want to edit the source SVG.

**Comment by kevincox** [comment]
The `openmoji.css` only affects users who are using a browser and using that style. It won't help system-font usage or other cases.

Well you have a copy of the built font file in your repo so it seems that you are taking some responsibility for the generation. The argument would make sense if the project was just the SVG files but it seems like it is also maintaining a build process for fonts using pinned versions of dependencies so it is unclear how it could be fixed anywhere else. If you think it is a bug with scfbuild I can also open a bug upstream, but it seems like we would still want to keep this bug open to update the build process and checked in font file to use the newer version.

**Comment by b-g** [comment]
Re-opened: https://github.com/hfg-gmuend/openmoji/pull/340#issuecomment-936074516

**Comment by b-g** [comment]
@kevincox ok. Can you think of a more descriptive name for the issue? e.g.

Problems with SVG default color in font files?

**Comment by kevincox** [comment]
I'm not sure this is completely accurate either because my fix didn't completely solve the problem. How about "Some black elements in SVG sources are being rendered with current font colour in TTF font?"

**Comment by mesaprotector** [comment]
I am guessing that this issue is why most of the smiley emojis are unreadable for me in Mozilla software (Firefox and Thunderbird) due to the seemingly light-gray outlines; in anything else, they look fine. 

I've had Openmoji as my default emoji font for nearly a year, but still have no idea how to resolve this.
