### ISSUE TITLE
Scottish Flag

### ISSUE THREAD

**Issue by carlinmack** [hfg-gmuend/openmoji#34]
The scottish flag in OpenMoji connects the blue at the four corners - there is no precedent for this and can't be thought of a stylistic choice as it makes it a different flag. I would contribute a pull request but I don't have access to illustrator. Thanks 🏴󠁧󠁢󠁳󠁣󠁴󠁿

**Comment by b-g** [comment]
Hi @carlinmack, mayn thanks for the report. Could you please be more visual and provide an annotated image of the issues? Also the src files are 100% open svg files. You can edit it with any svg editor. Just make sure that it follows the styleguide (that the pass the OpenMoji Tester App), see https://github.com/hfg-gmuend/openmoji/blob/master/CONTRIBUTING.md. PR are very welcome! ;)

**Comment by carlinmack** [comment]
Okay I'll use inkscape :) is it just the color and black and white emoji's I need to change?

**Comment by b-g** [comment]
Great! :) It is just a single file: https://github.com/hfg-gmuend/openmoji/blob/master/src/flags/subdivision-flag/1F3F4-E0067-E0062-E0073-E0063-E0074-E007F.svg if it just colors, then you might be able to fix in your favorite code editor.

**Comment by b-g** [comment]
Fixed with https://github.com/hfg-gmuend/openmoji/pull/37
