### ISSUE TITLE
unicode link broken (decodeunicode.org)

### ISSUE THREAD

**Issue by Cyrille37** [hfg-gmuend/openmoji#341]
Hello
Thanks a lot for this fabulous work! So lovely <3

By the way, on openmoji card, eg. [1FAC2](https://openmoji.org/library/#group=people-body%2Fperson-symbol&emoji=1FAC2), the unicode link https://www.decodeunicode.org/en/u+1FAC2 does not work but those work:
- https://www.decodeunicode.org/en/u+1FAC2
- https://emojiguide.org/people-hugging

Regards & cheers

**Comment by b-g** [comment]
Hi @Cyrille37, many thanks for reporting! Just there is nothing we can do about this ... we simply link to this database and hope that there is definition for the particular unicode. But you could write the https://decodeunicode.org project and let them know. I'm sure they appreciate any hints for missing unicode code points on their end.

**Comment by Cyrille37** [comment]
Hi
I'm afraid that nobody left behind decodeunicode.org ...

I sent a email and get answer "Your message to <poarangan@decodeunicode.org> was automatically rejected:
Quota exceeded (mailbox for user is full)" that means no one read emails ...

**Comment by b-g** [comment]
I'm sorry about this. Maybe this is just temporarily? Maybe try in a few days?
