### ISSUE TITLE
Unicode Emoji 14.0

### ISSUE THREAD

**Issue by dnlutz** [hfg-gmuend/openmoji#344]
dear fellow emoji designers,

this week unicode officialy launched the additions for emoji 14.0!
https://www.unicode.org/emoji/charts-14.0/emoji-versions.html

we have to keep up to date … will we be able to do this by the end of the year?
https://twitter.com/Emojipedia/status/1437788665661509639?s=20

every collaboration is welcome: professional designers, enthusiastic hobbyists, students and teachers ; )

daniel

**Comment by dnlutz** [comment]
Emoji v14.0 To Do List

Details: https://www.unicode.org/emoji/charts-14.0/emoji-released.html

- [ ] 1FAE0 Melting Face
- [ ] 1FAE2 Face with Open Eyes and Hand Over Mouth
- [ ] 1FAE3 Face with Peeking Eye
- [ ] 1FAE1 Saluting Face
- [ ] 1FAE5 Dotted Line Face
- [ ] 1FAE4 Face with Diagonal Mouth
- [ ] 1F979 Face Holding Back Tears
- [ ] 1FAF1 Rightwards Hand
- [ ] 1FAF2 Leftwards Hand
- [ ] 1FAF3 Palm Down Hand
- [ ] 1FAF4 Palm Up Hand
- [ ] 1FAF0 Hand with Index Finger and Thumb Crossed
- [ ] 1FAF5 Index Pointing at the Viewer
- [ ] 1FAF6 Heart Hands
- [ ] 1F91D Handshake > Skin tones
- [ ] 1FAE6 Biting Lip
- [ ] 1FAC5 Person with Crown
- [ ] 1FAC3 Pregnant Man
- [ ] 1FAC4 Pregnant Person
- [ ] 1F9CC Troll
- [ ] 1FAB8 Coral
- [ ] 1FAB7 Lotus
- [ ] 1FAB9 Empty Nest
- [ ] 1FABA Nest with Eggs
- [ ] 1FAD8 Beans
- [ ] 1FAD7 Pouring Liquid
- [ ] 1FAD9 Jar
- [ ] 1F6DD Playground Slide
- [ ] 1F6DE Wheel
- [ ] 1F6DF Ring Buoy
- [ ] 1FAAC Hamsa
- [ ] 1FAA9 Mirror Ball
- [ ] 1FAAB Low Battery
- [ ] 1FA7C Crutch
- [ ] 1FA7B X-Ray
- [ ] 1FAE7 Bubbles
- [ ] 1FAAA Identification Card
- [ ] 1F7F0 Heavy Equals Sign

**Comment by lizbravob** [comment]
Let's begin! :)

[v14_lb.zip](https://github.com/hfg-gmuend/openmoji/files/7274901/v14_lb.zip)

**Comment by b-g** [comment]
Yay!!! Thanks for the great start!

Looks good to me! @dnlutz more detailed feedback?

<img width="981" alt="Screen Shot 2021-10-05 at 08 12 58" src="https://user-images.githubusercontent.com/480224/135970050-61b833b0-2024-4f27-9884-e4f0ecb0129c.png">

**Comment by dnlutz** [comment]
1F979 i would suggest to delete the moon like white lines in the left of the eyes
1FAE2 would you try a less organic and more geometric hand?
1FAE5 just a little bit more space between the eyes and the mouth?
1FAE0 / 1FAE5 ¡perfecto!
thank you for the nice start and many greetings!

**Comment by fuddl** [comment]
![Biting Lip](https://user-images.githubusercontent.com/842548/137449107-6a71f87f-81af-43f0-8804-f91bc7be4a09.png)

**Comment by dnlutz** [comment]
thank you for your contributions @fuddl and @lizbravob !
the rest of the emoji will be done by students from  @hfg-gmuend/openmoji 
it will still take some time … but all remaining 14.0 emoji are now under way ; )

**Comment by fuddl** [comment]
@dnlutz Should I open pull requests for my proposals then?

**Comment by dnlutz** [comment]
is it possible that you give the wheel another try?

**Comment by fuddl** [comment]
@dnlutz I'd do the biting lips and the bubbles, of you think they are alright

**Comment by lizbravob** [comment]
[openmoji_lb.zip](https://github.com/hfg-gmuend/openmoji/files/7611003/openmoji_lb.zip)

Hi @dnlutz :) Cool, great news. 
Here are my contributions with fixes. If you need some support, count on me. Greetings ☺️

**Comment by b-g** [comment]
Hi @lizbravob! Many thanks and very nice!! 👍 Just to make sure that I gather across this thread the final openmojis, please double check the image below. These are correct? If so I would go ahead and add those to the OpenMoji library ...

<img width="1054" alt="Screen Shot 2021-11-29 at 08 36 16" src="https://user-images.githubusercontent.com/480224/143826846-665a4eb5-cb23-47d7-b9c8-4293c5f3fc33.png">

cc @dnlutz

**Comment by lizbravob** [comment]
Yes, it's correct :)

**Comment by b-g** [comment]
Hi @lizbravob, tried to merge you new OpenMojis to the lib ... but there a two tiny "bugs" which prevented me from doing so. Could you please get rid of any white fills in the line and line-supplement layers? Would be suer nice of you. Possible?

You can use the https://openmoji-tester.glitch.me/ app to validate everything (nothing should be red).

<img width="1184" alt="Screen Shot 2021-11-30 at 15 42 29" src="https://user-images.githubusercontent.com/480224/144068441-08944d2b-7e34-422e-a9bb-e6a1c310bf0b.png">

<img width="952" alt="Screen Shot 2021-11-30 at 15 40 03" src="https://user-images.githubusercontent.com/480224/144068574-f1989ac6-429e-4e19-be0d-26d9739cc8d2.png">
<img width="737" alt="Screen Shot 2021-11-30 at 15 41 56" src="https://user-images.githubusercontent.com/480224/144068578-9a31734e-bf4f-4324-9098-d35b0ac48d76.png">

**Comment by fuddl** [comment]
@b-g if you put it into a feature branch I’d try to fix it

**Comment by b-g** [comment]
@fuddl Would be super! There is now https://github.com/hfg-gmuend/openmoji/tree/emoji14 ... Cheers!

**Comment by lizbravob** [comment]
Hola 👋🏼 I was passing around here, and I had not realized this. Sorry, if it has not been fixed, here they are. 
[openmoji.zip](https://github.com/hfg-gmuend/openmoji/files/8028423/openmoji.zip)

Can I help with something with the new release? I'm on vacation. 

If you need help, happy to support :)
Greetings

**Comment by b-g** [comment]
Hi @lizbravob, many thanks for this!! Just added your super nice contributions to the collection https://github.com/hfg-gmuend/openmoji/commit/b92993a7bcc14690fcdc5fc53fca411bd199fcd7 Yay!

> If you need help, happy to support :)

That is super nice of you! ❤️ I think we are mostly good with the remaining emojis of v14 (cc @dnlutz) ... Most of the other energy goes currently in making the technical side of the website better and finding a technical way to finally having OpenMojis also working on a black background. But all of this is quite code heavy. Sorry! The only thing which comes to my mind is this old request of designing a nice "DJ" (think of music and party) emoji https://github.com/hfg-gmuend/openmoji/issues/47. We tried something but couldn't figure it out. Would that be something?

+ Happy holidays! :)

**Comment by b-g** [comment]
Also @lizbravob here are more things which would be nice but somehow we never had the time -> https://github.com/hfg-gmuend/openmoji/wiki/Backlog-and-Wishlist

**Comment by tif-calin** [comment]
@b-g Hey cool I hadn't seen that wiki before. I made a special interest request in 2020 (used a diff account) to add more produce emojis. Would that be a good fit for that page? Since I was gonna use those emojis for a specific project I think I might actually get a friend to create them with the OpenMoji style guide and upload them to this project if that's cool

Here's the original post: https://github.com/hfg-gmuend/openmoji/issues/264

**Comment by b-g** [comment]
Hi @tif-calin, sure! Would be lovely to have more every day objects and items. Please open a new issue to discuss things, list the proposals ... and then start easy e.g. with a few examples, so that you get feedback BEFORE an entire set has been designed. Please be aware that all new OpenMojis should be carefully crafted following our Styleguide.

**Comment by b-g** [comment]
Done. Many thanks everyone!!
