### ISSUE TITLE
Is it possible to change the black-icon color via CSS?

### ISSUE THREAD

**Issue by waldenn** [hfg-gmuend/openmoji#350]
Hi, first of all thank you for a great icon library, I use it with together with FontAwesome in my https://conze.pt encyclopedia project.

I would like to change the black stroke color using CSS upon hover. This works for FontAwesome, but not OpenMoji.

Any idea why this is and if it can be fixed / worked around? Thanks.

**Comment by fuddl** [comment]
We need _OpenmojiMonochrome_ more than anyone needs _OpenmojiBlack_. I through it’s the easier thing to to. I have generated lots of monochrome fronts from svg files and there are libraries for that. But, correct me if I’m wrong, all shapes would need to be merged to a compound path and even before that, strokes need to be converted to outlines. I guess this is the difficult part.

**Comment by kevincox** [comment]
> And tell the user to use css e.g. color: black for the desired color.

This sounds good for the openmoji-black. However we should do the opposite for the openmoji-color set and ensure that they are black no matter what the font color is otherwise they look very bad and are hard to read.

**Comment by RobertWinslow** [comment]
> We need _OpenmojiMonochrome_ more than anyone needs _OpenmojiBlack_.... But, correct me if I’m wrong, all shapes would need to be merged to a compound path and even before that, strokes need to be converted to outlines. I guess this is the difficult part.

I wrote a little script to convert the black SVGs into a simple monochrome font using FontForge's importOutline() and removeOverlap() functions. 

This results in a font which has a significantly smaller filesize than the ones in current releases, which seems to work properly in a much wider variety of software, and which readily accepts color changes.

You can [download the OpenMoji-MonoChrome.ttf file here](https://github.com/RobertWinslow/openmoji/blob/monochrome-font/font/OpenMoji-MonoChrome.ttf).
And [here is the script I used to build it](https://github.com/RobertWinslow/openmoji/blob/monochrome-font/helpers/fontforge_font_builder/build_font_with_fontforge.py).

**Comment by b-g** [comment]
Hi @RobertWinslow, wow! Many thanks for this lovely gift in such dark times! This is great on all levels ... but even greater would be to have this part of the `npm run generate-font` build pipeline and to use your OpenMoji-MonoChrome.ttf as OpenMoji-Black.ttf. 

Could you have a look?

Comment: 
- I would vote to use this `PLACEHOLDERGEOMETRYSVG = '25A1.svg'` https://openmoji.org/library/#search=missing&emoji=25A1
- I think the Docker container should already satisfy the dependencies https://github.com/b-g/scfbuild/blob/master/Dockerfile

**Comment by RobertWinslow** [comment]
> even greater would be to have this part of the npm run generate-font build pipeline and to use your OpenMoji-MonoChrome.ttf as OpenMoji-Black.ttf

Thanks for the feedback. I'll certainly look into this. I'll need to familiarize myself with some of the build tools first.

**Comment by RobertWinslow** [comment]
I believe after #422, the answer to this question is definitively "yes".

**Comment by b-g** [comment]
Solved. The new fonts will be released with the next release, or see in the meantime the `font` folder of this repo: https://github.com/hfg-gmuend/openmoji/tree/master/font
