### ISSUE TITLE
Regional Indicator Symbol Letter A-Z emoji missing

### ISSUE THREAD

**Issue by lolbot-iichan** [hfg-gmuend/openmoji#351]
There are 26 emojis missing with codepoints U+1F1E6~U+1F1FF (🇦 ~ 🇿).

Option 1:

Some fonts are rendering them as capital letters in some kind of frame (Twitter, Facebook, JoyPixels, Emojidex, Softbank, EmojiTwo, Symbola). See:
https://www.emojiall.com/en/emoji/%F0%9F%87%B5
https://www.emojiall.com/en/emoji/3%EF%B8%8F%E2%83%A3
https://emojipedia.org/regional-indicator-symbol-letter-p/
https://emojipedia.org/keycap-digit-three/

There is already an emoji that looks exactly like this, emoji U+1F17F (🅿️) that can take place of (U+1F1F5) 🇵:
https://www.emojiall.com/en/code/1F17F
https://emojipedia.org/p-button/
Compare:
https://openmoji.org/data/color/svg/0033-FE0F-20E3.svg
https://openmoji.org/data/color/svg/1F17F.svg

My suggestion is:
1. Rename 1F17F.svg to 1F1F5.svg
2. Create 1F1E6.svg, ..., 1F1FF.svg - with colors and letter size of 1F1F5.svg and letter lines from openmoji-abc.svg
3. Create a new 1F17F.svg - with lines of 1F17F.svg and blue colors from different emoji (e.g. colors of 🈳 or 🆓).

Motivation: 🅿️ is blue in all other emoji sets, so 1F17F.svg is currently wrong anyway.

Option 2:

Some fonts are rendeding them as blue/cyan/grey/black capital letters on transparent background (Google, Samsung, Microsoft, HTC, LG, BlobMoji).

So, the other option is to leave 1F17F.svg as is, and to add new 1F1E6.svg, ..., 1F1FF.svg files with just black capital letters without a frame.

**Comment by dnlutz** [comment]
should we place the letters in squares? we could store them in the [unicode block "enclosed alphanumeric supplement"](https://en.wikipedia.org/wiki/Enclosed_Alphanumeric_Supplement).
the openmoji font is monospaced and all the glyphs in it have the same width.
so we can't include flags. but the [squares](https://openmoji.org/library/#group=symbols%2Falphanum) would be simple and pragmatic?

**Comment by fuddl** [comment]
Regional indicators are within the _Enclosed Alphanumeric Supplement_ block. I didn’t mean to say the regional indicators should have a different aspect ratio: Only the enclosing element should be flag shaped.

**Comment by b-g** [comment]
Done with https://github.com/hfg-gmuend/openmoji/commit/0ade38a3763c7b6600115a18b636dccee0d23f0a, closing. Many thanks.
