### ISSUE TITLE
Non-Standard 'People' emoji have no skin tones

### ISSUE THREAD

**Issue by fuddl** [hfg-gmuend/openmoji#353]
Like the gardener, the person with medical mask or the barista.

At first I thought, that simply every svg with a `skin` layer should automatically have all the skintones but specific people like _Greta Thunberg_ and _trump_ need to be excluded.

**Comment by b-g** [comment]
Hi @fuddl, yes having skintones for every person would be nice! 

However the effort to implement this would be rather enormous, 1. as we would have to extend/change our current build system and 2. in addition we have a hard dependency towards emojibase-data for all the Emoji Unicode definitions. Currently we create only skintones according to the official Unicode definitions ... 

And as we have so many other (IMO more important) open issue / task / todos ... I'm personally not willing to invest into this. Hence I guess it is either you tackle it all :) or there is no realistic chance to have this in the near future. Sorry!

Would you want to look into it, or should we close the issue and put the suggestion to your backlog? What do you think?
