### ISSUE TITLE
HAL9000

### ISSUE THREAD

**Issue by fuddl** [hfg-gmuend/openmoji#357]
Do you like it? Should I commit?

<img width="281" alt="HAL9000" src="https://user-images.githubusercontent.com/842548/139489697-bd0ccfbc-597d-409a-87fc-12c3aa68d6d3.png"><img width="140.5" alt="HAL9000" src="https://user-images.githubusercontent.com/842548/139489697-bd0ccfbc-597d-409a-87fc-12c3aa68d6d3.png"><img width="70.25" alt="HAL9000" src="https://user-images.githubusercontent.com/842548/139489697-bd0ccfbc-597d-409a-87fc-12c3aa68d6d3.png"><img width="35.125" alt="HAL9000" src="https://user-images.githubusercontent.com/842548/139489697-bd0ccfbc-597d-409a-87fc-12c3aa68d6d3.png"><img width="17.5625" alt="HAL9000" src="https://user-images.githubusercontent.com/842548/139489697-bd0ccfbc-597d-409a-87fc-12c3aa68d6d3.png"><img width="8.78125" alt="HAL9000" src="https://user-images.githubusercontent.com/842548/139489697-bd0ccfbc-597d-409a-87fc-12c3aa68d6d3.png"> 

Tags: `AI`, `Artificial intelligence`, `Rouge AI`, `I'm sorry Dave, I'm afraid I can't do that`, `Space Odyssey`, `science fiction`, `2001`, `computer`

**Comment by inferno986return** [comment]
How does it look at small sizes? It's rather detailed for an emoji. 🤔

**Comment by fuddl** [comment]
@inferno986return I scaled it down for you 😅

**Comment by b-g** [comment]
Hi @fuddl, neat! :) But I'm wondering whether people rather know only the "eye" like camera lens and the current vertical box makes it rather harder to get it? Maybe it would be better to emphasize more on the red eye and less on the box?

e.g. google Hal 9000 also yields for me more red eyes ... and [wikipedia lists](https://de.wikipedia.org/wiki/HAL_9000) an image of the red eye first too

<img width="1347" alt="Screen Shot 2021-11-02 at 12 00 21" src="https://user-images.githubusercontent.com/480224/139834913-c553d4b5-d298-4a2e-b026-2d162c2d2d83.png">

**Comment by fuddl** [comment]
The aspect ratio of the box around the eye is reoccurring in several significant objects in the film (the black monolith, the space station entrance, Hal’s computer core) that’s why I wanted to include it.

The Red eye on the other hand became somewhat of a meme itself 

![566A7AA0-ACC1-43E0-9F76-B22295C53C2A](https://user-images.githubusercontent.com/842548/139837071-17050736-582c-4542-9a6c-65c7db21e833.jpeg)
![3DEDA1CF-3DA1-4892-8041-B112F11358CD](https://user-images.githubusercontent.com/842548/139837073-5493d386-5681-45dd-810f-c4a07ac50b42.jpeg)

Might be a good idea👍

**Comment by b-g** [comment]
Hi @fuddl, sorry for the slow response ... very busy here! I would like to propose a compromise: what about having two HAL 9000 openmojis? 1.  as proposed above and 2. a big meme friendly red eye without the vertical device box? I think this way "OpenMoji users" could make more use of it in terms of expressiveness.

**Comment by fuddl** [comment]
@b-g gladly

**Comment by fuddl** [comment]
Image | Name | Sequence | Tags
-------|------|------------|-------------
![FISH EYE figma](https://user-images.githubusercontent.com/842548/141674992-6c83c1f2-db8f-40f4-a9bc-8c8ddbd15abc.png) | Fish eye | `◉` | `iris`
![FISH EYE RED figma](https://user-images.githubusercontent.com/842548/141674994-1166fcb5-f3ed-4005-8a2f-0a357a6fa028.png)| Red eye | `◉`+`vs-16`+`zwj`+`🔴` | `turret`, `ai`, `rogue ai`, `portal`
![HAL9000 figma](https://user-images.githubusercontent.com/842548/141674993-789d9aed-b03b-4b10-b460-2d10c8df37b5.png)  | HAL9000 | `◉`+`vs-16`+`zwj`+`🔴`+`zwj`+`▮`+`vs-16` | `AI`, `Artificial intelligence`, `Rouge AI`, `I'm sorry Dave, I'm afraid I can't do that`, `Space Odyssey`, `science fiction`, `2001`

**Comment by b-g** [comment]
@fuddl good call to map to existing Unicode char “◉ Fisheye” (U+25C9)! Just spelling (spaces) ... I believe it is: "Fisheye" and "HAL 9000". Very nice! Please PR! :)

PS: Fisheye -> extras-unicode, Red eye and HAL 900 -> extras-openmoji

**Comment by joshcoales** [comment]
Ooh, I like that using 🔴 in the sequence also means [SAL9000](https://2001.fandom.com/wiki/SAL_9000) could get some care too, with 🔵
