### ISSUE TITLE
chicken emoji 1F414

### ISSUE THREAD

**Issue by donavon** [hfg-gmuend/openmoji#359]
You can't tell against a white background, but the white body on the [chicken emoji (1F414)](https://openmoji.org/library/#group=animals-nature&emoji=1F414) extends out past the black stroke.

![image](https://user-images.githubusercontent.com/887639/139574089-d69301bf-ef74-44d2-97d3-25f307d0b8bd.png)

**Comment by b-g** [comment]
Hi @donavon! Many thanks 👏 for spotting 👀 and reporting (on Twitter :) and here! 💉🐔 Fixed! Will be shipped with the next release.
