### ISSUE TITLE
Incorporating the search engine of openmoji in a webapp/website?

### ISSUE THREAD

**Issue by francoisschwarzentruber** [hfg-gmuend/openmoji#363]
First of all, thank you for your very nice project. I love the images. My question is: is it possible to incorporate the image search engine https://openmoji.org/library/in a webapp/website?

My need would be to have a sort of dialog box and then to get directly the svg as a result.

The use would be for the online blackboard project Tableaunoir (https://tableaunoir.github.io/ and https://github.com/tableaunoir/tableaunoir). The idea would be to easily being able to add magnets (images that are moveable on the blackboard).

What do you think?

PS: I love so much openmoji that Tableaunoir already relies on openmoji for some of the icons.

**Comment by b-g** [comment]
Hi @francoisschwarzentruber, many thanks for the kind words + Tableaunoir looks interesting! I guess you basically would want an Emoji picker, correct? If so ... feel free to check/re-use the source code of https://github.com/hfg-gmuend/openmoji.org and see #123 #170. Good luck! :)

**Comment by francoisschwarzentruber** [comment]
Thank you! Yes I want a sort of Emoji picker, but with an emphasis with a search engine. For instance, if the user types e.g. "person", then the dialog box proposes all the emojis that represent a person, like in the openmoji.org website. Thank you also for pointing me to the issues #123 and #170.

**Comment by b-g** [comment]
I see! We are using for the search a fuzzy search library called "fuse" https://fusejs.io/ with this config https://github.com/hfg-gmuend/openmoji.org/blob/master/src/library.js#L97. The search is then fired against data/openmoji.json which holds the meta information of each openmoji. Hope these pointers help :)

**Comment by francoisschwarzentruber** [comment]
Thank you for all the information. I started a small project that could become an npm package:
https://github.com/tableaunoir/openmoji-fetch

That npm package enables to fetch information from openmoji:
- emojis that match a string
- the svg code of some emoji
In particular, the package does not contain any DOM manipulation, any js code for some GUI. Tableaunoir's GUI will be built on top of that.
What do you think?

**Comment by francoisschwarzentruber** [comment]
Now, openmoji is available in Tableaunoir :)
![image](https://user-images.githubusercontent.com/43071857/144747144-d636dd03-dc8e-4bbc-9cc7-7e1e33e00888.png)

**Comment by b-g** [comment]
@francoisschwarzentruber That's great! Many thanks for featuring OpenMoji in Tableaunoir! 👍
