### ISSUE TITLE
SVG size and Firefox

### ISSUE THREAD

**Issue by francoisschwarzentruber** [hfg-gmuend/openmoji#371]
As far as I understand, Firefox has some difficulties to get the size of SVGs when the width and height are not explicitly specified (see the bug report https://bugzilla.mozilla.org/show_bug.cgi?id=700533). As the size of SVGs in OpenMoji is unspecified, Firefox has troubles in these two situations.
1. It is impossible to draw SVGs from OpenMojis in an HTML canvas: `context.drawImage(img, x, y)` does not work on Firefox. It does not trigger any error, it just draws nothing.
2. SVGs from OpenMojis are not displayed in the snapshots of the developer tools in Firefox.
On Chrome, everything works perfectly.

Do you plan do add explicitly that the width and height of the images are 96 x 96?

PS: I need point 1 to work. I use OpenMoji in the online blackboard Tableaunoir (tableaunoir.github.io/). The regular use is ok. But the tool provides the possibility to "print" magnets (i.e. to draw an image directly on the canvas for editing purposes). That part works on Chrome, but not on Firefox :(.

**Comment by b-g** [comment]
@francoisschwarzentruber Many thanks for adding OpenMoji to Tableaunoir! I'm afraid we currently are not planning to enhance the svg src files with redundant width and height attributes. However you could easily patch the files with JSDOM on the fly eg. https://github.com/hfg-gmuend/openmoji/blob/master/helpers/lib/export-svg-color.js#L15. Sorry!

**Comment by francoisschwarzentruber** [comment]
Thank you for your answer. You are right. Probably the most elegant way would be to patch the svg on the fly. It is so sad that Firefox cannot infer automatically the width and height of SVGs!

**Comment by francoisschwarzentruber** [comment]
@b-g Sorry to disturb you again about that. I think the easier way to go would be to:
1. copy all images of OpenMoji
2. run a script (inspired from your proposition) that adds the width and height parameters to each svg file
3. make a repository contains the new svg files
4. Tableaunoir will then point to these new svg files instead of refering directly to OpenMoji

Do you agree with that approach?

And thank you for your help.

**Comment by b-g** [comment]
Hi @francoisschwarzentruber, Sorry for the late response ... very busy here at the end of the term. I have no obligations if you want to have a custom repo for the fix. However with every new OpenMoji coming from us, you would have to deal again with this issue. Hence I guess the cleaner way would be to reflect these changes in our build system so that this is automatically added in all future releases. For the later we would ask you for help. Either way is fine for us.

**Comment by francoisschwarzentruber** [comment]
Dear @b-g thank you for your answer! Do not worry, I perfectly understand. Making a custom repo was a stupid idea of mine, sorry for that.

I found a quite elegant way to programmatically add the viewport `width="72" height="72"` so it works now! (see the last commit of the issue https://github.com/tableaunoir/tableaunoir/issues/211)

Concerning OpenMoji, I would be glad to help. Firefox just requires the viewport (width and height) to be mentioned and not only the viewbox. Maybe the easiest way could be to keep the source svg as they are (your src folder). But the production files mention the viewport too.

It seems that the viewport is `width="72" height="72"` for all the emojis. Do you confirm?

**Comment by b-g** [comment]
Hi @francoisschwarzentruber, Great and Yes! Any help to add the `width="72" height="72"`to the production files in /color/svg and black/svg is very welcome. I think actually adding this to the buildsystem is easy ... but then checking everything for any unwanted side effects e.g. `npm run generate-fonts` is the time consuming part.
