### ISSUE TITLE
Some SVG files have multiple elements with the same id attribute.

### ISSUE THREAD

**Issue by RobertWinslow** [hfg-gmuend/openmoji#372]
There are 13 glyphs for which the SVG source files contain duplicate id attributes. 
According to the SVG specifications, the id attribute must assign a _unique_ name to each element. 
These duplicated names caused trouble for me when trying to parse the SVG files with another program.

As an example, you can look at the source for the spoon: [1F994.svg](https://github.com/hfg-gmuend/openmoji/blob/master/src/food-drink/dishware/1F944.svg)
There are two seperate path elements with the attribute `id="_xD83E__xDD44_" `

I have already fixed the issue, and will make a pull request shortly.

**Comment by b-g** [comment]
Many thanks + Great! Merged with https://github.com/hfg-gmuend/openmoji/commit/0e555f6ad5d3a41a334850f72316a44529a61368
