### ISSUE TITLE
Significant alpha padding in PNGs

### ISSUE THREAD

**Issue by jjb** [hfg-gmuend/openmoji#378]
Thanks for a great project! <img src="https://openmoji.org/data/color/svg/1F389.svg" height="25px"><img src="https://openmoji.org/data/color/svg/1F929.svg" height="25px">

While considering to use the pngs in a project <img src="https://openmoji.org/data/color/svg/1F914.svg" height="25px">, I discovered that they all have significant alpha padding around each emoji <img src="https://openmoji.org/data/color/svg/1F62F.svg" height="25px">. I did a bit of research on [rsvg-convert](https://github.com/hfg-gmuend/openmoji/blob/master/helpers/lib/export-png.sh) <img src="https://openmoji.org/data/color/svg/1F575.svg" height="25px"> and couldn't find a way to reduce this padding for an individual png. My guess is that the padding is "baked in" to the svg itself? I also did some research on the svg format and where it might be coming from, but didn't get anywhere. <img src="https://openmoji.org/data/color/svg/1F937.svg" height="25px">

For the purposes of my project I came up with this command to remove padding from the large pngs and then reduce them to 72x72 <img src="https://openmoji.org/data/color/svg/1F9D9.svg" height="25px">:

    find . -name '*.png' -exec convert {} -trim +repage -resize 72x72 {} \;

This achieves exactly what I want but the quality is not as nice as if I do the analogous steps in Preview.app on macos. I'm guessing there are more options I can give to imagemagick to improve the quality.

Also, the resulting files are not exactly 72x72, but are 72 on their longest side. Depending on application, this may or may not be desirable. I'm sure this could also be accommodated with some imagemagick flags.

I thought maybe this was intentional placement of the canvas within the svg in a way that is nice when the emojis are next to one another, something like that. but, the padding seems to be consistent and identical for all emojis (admittedly i only spot checked a handful)

I'm wondering how intentional this is, and if there might be interest in making tighter PNGs?

**Comment by b-g** [comment]
Hi! Glad that you like! Many thanks for sharing the useful "trim" command!

Yes the padding is intentional and due to: 

> The Grid serves as orientation for the size of the emojis. If possible your emojis should stay inside the Grid, but for edge cases use 4px of padding.

see https://openmoji.org/styleguide/#grid and every src file

Basically removing the safe zone and trimming to a minimal size will "kill" the edge cases.

Yes the padding is "baked in" to the svg in terms of the position of the emoji inside the 72x72 viewport. If you want to have better alignment of the emojis to you text, you will have to align you files according to 0/0 reference point and set a css style which allows your images to have an overlap with other html elements.

Hope this helps. Also this question has been asked quite a few times in different flavors :) See: https://github.com/hfg-gmuend/openmoji/issues?q=padding

**Comment by jjb** [comment]
Thanks for the info. I promise I did look for previous discussion first <img src="https://openmoji.org/data/color/svg/1F605.svg" height="25px"> but I think i was searching for "margin".

The docs mention The Grid and 4px for edge cases, but doesn't say what the padding is for non-edge cases. Is the grid in the template at the bottom of the page? (i'm not a designer so don't know my way around such files)

In this ticket, the asker asks about 4px padding, and you give the example of needing it to accommodate exceptions such as shooting star: https://github.com/hfg-gmuend/openmoji/issues/257#issuecomment-708963052

But what I'm talking about is much greater padding, such as in E32B, there is 17px on each side. In 1F981, there is 8 on each side, 7 on the top, 4 on the bottom.

a) are we talking about the same thing?
b) why can't the emojis which do _not_ need the padding simply be rendered without it? I think one case where you don't want this is with faces, where you want all the face circles to have the same diameter (although in my layperson opinion this isn't necessary). But in other cases, there isn't such a need for consistency?

Maybe some of this info should go into the FAQ or styleguide - i'll try to make a PR with the results of this discussion if it's helpful.

Thanks!

**Comment by b-g** [comment]
No worries! :)

All OpenMojis follow a grid system ... for consistency reason AND to allow aligning OpenMojis in a nice way in combination with text. The "correct" way to do this, is to align the [baseline](https://en.wikipedia.org/wiki/Baseline_(typography)) of a font with our grid like this:
![158382904-04366686-c7b3-4d97-a722-6882e6a6dca2](https://user-images.githubusercontent.com/480224/158410328-8815751f-39e2-471b-8122-f13022146281.jpg)

Now removing paddings based on the bounding box of the emojis would no longer allow for this (and would create even more problems for the entire font build pipeline).

Does this help?
