### ISSUE TITLE
surprised at rendering quality

### ISSUE THREAD

**Issue by jjb** [hfg-gmuend/openmoji#379]
using this code:

```html
<!-- referencing emoji.org just for experimental purposes, don't worry I won't use the website as my CDN in production -->
<img src="https://openmoji.org/data/color/svg/1F605.svg" alt="😅" data-emoticon="true" style="height:1.4em;">
```

I get this rendering:

<img width="44" alt="Screen Shot 2022-03-15 at 12 25 09 AM" src="https://user-images.githubusercontent.com/6097/158306483-8a26dad6-0329-4d93-82ab-98f85434ad38.png">

The rendering looks a big jagged to me. Or maybe I've been staring at this too long and that is simply the limitations of the pixels available? 

Here's a screenshot of the apple emoji

<img width="25" alt="Screen Shot 2022-03-15 at 12 25 24 AM" src="https://user-images.githubusercontent.com/6097/158306515-89f07932-9d93-4df8-8831-5603c386a2be.png">

You can click on the two images above and open the straight image files and compare them analogously.

<img width="236" alt="image" src="https://user-images.githubusercontent.com/6097/158306963-ea856389-4b86-4e90-b579-d909137f13b1.png">

In case it's interesting, here's openmoji at 400%

<img width="95" alt="Screen Shot 2022-03-15 at 12 24 59 AM" src="https://user-images.githubusercontent.com/6097/158306546-05f29f0c-d060-44ad-b2a5-c3e1aee0ce98.png">

I don't know much about SVGs but I was surprised that the rendering was a bit jagged. Is there any way I can address this in my html? Is it a consequence of trying to save space in the SVG files?

Thanks! let me know if i can provide any more info

**Comment by b-g** [comment]
Hi there! A SVG file is a vector file, hence every browser and application will render this slightly different. If the dimensions of the emoji become really small ... rendering will always become pixelated or blurry. There is nothing we can do about that, hence will close the issue. 

> Is it a consequence of trying to save space in the SVG files?

No. The production and src files are (almost) identical, but: floating point precision is stripped to 3 decimals e.g. 0.123 and the grid (guides) layer is removed.

**Comment by jjb** [comment]
Gotcha, thanks for the info.

am i seeing things or is the top one rendered slightly less nicely than the bottom one?

```html
          <img class="lazy astro-XCJPZWXF" data-src="" data-ll-status="observed" src="/data/color/svg/1F605.svg" style="height:1.4em;">
          <img class="lazy astro-XCJPZWXF" data-src="" data-ll-status="observed" src="/data/color/svg/1F632.svg" style="height:1.4em;">
```

<img width="109" alt="image" src="https://user-images.githubusercontent.com/6097/158404860-a2a67b72-8323-45e9-afb1-368c262da6b0.png">

for example there's a little fuzzy pixel at the top of the head for this first one:

<img width="82" alt="image" src="https://user-images.githubusercontent.com/6097/158405029-8cab5fd8-22eb-423f-9e61-0e7c6e651d53.png">
<img width="85" alt="image" src="https://user-images.githubusercontent.com/6097/158405043-29ee9ad9-4b40-49f9-9c15-405bdc8d926f.png">
