### ISSUE TITLE
Best practice: Access emojis images with python

### ISSUE THREAD

**Issue by kolibril13** [hfg-gmuend/openmoji#386]
I had the idea to write a plugin for the python based animation package manim, so that openmojis can be easily used in animations.
Therefore, I'd like to access emojis with a function call like `get_emoji("👩‍⚕️")` that would then return an image of the emoji.
With the Twitter emojis, this can be done in a few lines of code:
```py
from PIL import Image
import numpy as np
import requests

#get twitter emoji
def get_emoji(emoji):
    emoji_code = "-".join(f"{ord(c):x}" for c in emoji)
    url = f"https://raw.githubusercontent.com/twitter/twemoji/master/assets/72x72/{emoji_code}.png"
    im = Image.open(requests.get(url, stream=True).raw)
   # image = np.array(im.convert("RGBA"))
    return im

get_emoji("👩‍⚕️")
```
<img width="72" alt="image" src="https://user-images.githubusercontent.com/44469195/162633474-4d6f271e-3959-44ae-8315-ddf5aeccaea1.png">
And also with openmoji this can be accomplished, e.g. with this script:

```py
from PIL import Image
import numpy as np
import urllib.request
from pathlib import Path

import zipfile

path_emojis = Path.cwd() / f"temp_emojis"
# get openmoji version 13.1.0
if not path_emojis.exists():   # Download and unzip assets, in case that not already downloaded
    path_zip = Path.cwd() / f"openmoji-618x618-color.zip" 
    url = f"https://github.com/hfg-gmuend/openmoji/releases/download/13.1.0/openmoji-618x618-color.zip"
    urllib.request.urlretrieve(url, path_zip)
    with zipfile.ZipFile(path_zip, "r") as zip_ref:
        zip_ref.extractall("temp_emojis")
    path_zip.unlink() # delete zip folder


def get_emoji(emoji):
    emoji_code = "-".join(f"{ord(c):x}" for c in emoji)
    im = Image.open(path_emojis / f"{emoji_code}.png") # open image from local location
    # im = np.array(im.convert("RGBA"))
    return im


get_emoji("👩‍⚕️")
```
<img width="72" alt="image" src="https://user-images.githubusercontent.com/44469195/162633588-f404bfc8-a6fb-4bd5-bcf7-74fa2ad05f71.png">

I like the current `get_emoji` twitter implementation a bit more, because it always uses the latest version of the emojis, and no download of all assets is required. In case that someone is interested in discussing a best practice access, feel free to leave a message here 💬

**Comment by b-g** [comment]
@kolibril13 Many thanks for sharing! (We liked as well your animations on twitter :)

Why not simply as well with e.g. https://raw.githubusercontent.com/hfg-gmuend/openmoji/master/color/72x72/1F600.png ?

```py
from PIL import Image
import numpy as np
import requests

#get openmoji
def get_emoji(emoji):
    emoji_code = "-".join(f"{ord(c):x}" for c in emoji)
    url = f"https://raw.githubusercontent.com/hfg-gmuend/openmoji/master/color/72x72/{emoji_code}.png"
    im = Image.open(requests.get(url, stream=True).raw)
   # image = np.array(im.convert("RGBA"))
    return im

get_emoji("👩‍⚕️")
```

**Comment by b-g** [comment]
PS. @kolibril13 In case you are interested in helping/contributing. We will soon need a new video for upcoming OpenMoji 14.0, see https://github.com/hfg-gmuend/openmoji-glyphs-video. Would be lovely to bring this to the next level e.g. with a nicer in between animation https://twitter.com/nagayama/status/1494840017260548097

**Comment by kolibril13** [comment]
@b-g I am glad you liked the animations :)
And thanks for pointing me to the right folder, I was only looking in the source folder `https://github.com/hfg-gmuend/openmoji/tree/master/src`, but your implementation is exactly what I was looking for.
Right now I am even thinking of re-writing the `get_emoji` function in a way that I only download one svg at a time from https://github.com/hfg-gmuend/openmoji/tree/master/color/svg and let python do the conversion to png with this script:
```
import cairosvg
width = 640
height = 480
cairosvg.svg2png(url='emoji_code.svg', write_to='image.png', output_width=width, output_height=height)
```
> We will soon need a new video for upcoming OpenMoji 14.0

That sounds like a fun project, I will have a look on it! I think that it would be possible to reproduce these kinds of animation with manim.

**Comment by b-g** [comment]
👍 !

**Comment by kolibril13** [comment]
> Why not simply as well with e.g. https://raw.githubusercontent.com/hfg-gmuend/openmoji/master/color/72x72/1F600.png ?

I've just tested your code, and it works fine when one first capitalizes all letters in the emoji string:
```py
from PIL import Image
import numpy as np
import requests

#get openmoji
def get_emoji(emoji):
    emoji_code = "-".join(f"{ord(c):x}" for c in emoji)
    emoji_code = emoji_code.upper() # <- this needs to be added
    url = f"https://raw.githubusercontent.com/hfg-gmuend/openmoji/master/color/72x72/{emoji_code}.png"
    im = Image.open(requests.get(url, stream=True).raw)
   # image = np.array(im.convert("RGBA"))
    return im

get_emoji("🐶")
```
<img width="62" alt="image" src="https://user-images.githubusercontent.com/44469195/162700452-31b8102a-e09f-4c2f-baea-ad4b3e6b869a.png">

**Comment by b-g** [comment]
Great! Many thanks for this nugget! Should I close the issue now?

**Comment by kolibril13** [comment]
Yes, this issue can be closed.
> Many thanks for this nugget!

It's a pleasure! :)
As the script might be useful for other people as well, maybe it can be documented somewhere? 
Two suggestions: As I am using the python package PIL, I could send a pull request to their documentation: https://pillow.readthedocs.io/en/stable/index.html
And then one could link to this PIL documentation example later in the FAQ: https://openmoji.org/faq/.
But as most links on the internet will break over time, maybe it's better to mention this script directly in the FAQ or the openmoji documentation. What do you think?

**Comment by b-g** [comment]
Sure! Good call! What about linking in https://github.com/hfg-gmuend/openmoji/#downloads--distribution-channels under Community Extensions to the relevant resources?
