### ISSUE TITLE
Images for polar explorer man and polar explorer woman have been swapped

### ISSUE THREAD

**Issue by MEibenst** [hfg-gmuend/openmoji#390]
It looks as if the images for polar explorer man and polar explorer woman have been swapped.
![IMG_20220508_102931](https://user-images.githubusercontent.com/72352961/167288759-9e666aba-32f0-4714-9a16-7512fc527323.png)
In comparison
![IMG_20220508_103304](https://user-images.githubusercontent.com/72352961/167288791-a6c3acb5-1439-43b5-bd04-741204362fe6.png)
![IMG_20220508_102857](https://user-images.githubusercontent.com/72352961/167288805-a4e5b75d-c71e-4065-8471-552a7221dc66.png)

**Comment by b-g** [comment]
Many thanks for spotting and reporting! Fixed!
