### ISSUE TITLE
Excessive whitespace

### ISSUE THREAD

**Issue by TikoyX** [hfg-gmuend/openmoji#395]
Some of the emojis have an excessive amount of whitespace around them.
I have only used the SVGs in colorformat, so they are the only one i have checket.
I have so far found E002, E1D5, E090, E325, E256, E207, E319 (generally in the healthcare section)

**Comment by b-g** [comment]
Yes we a far from perfect and we are aware. We simply don't have the resources to have the same level of consistency like the big tech vendors. Sorry! Daniel Utz has a gigantic list of other things more important to the overall project. Closing. But happy to get high quality PRs to improve there. Wink wink :)
