### ISSUE TITLE
Add special interest emoji: Null Island

### ISSUE THREAD

**Issue by b-g** [hfg-gmuend/openmoji#40]
https://en.wikipedia.org/wiki/Null_Island
https://twitter.com/nullislandbuoy

![images](https://user-images.githubusercontent.com/480224/66577049-b6493580-eb46-11e9-8ce9-e5b40ce614f4.jpg)
![null-island-2](https://user-images.githubusercontent.com/480224/66577050-b6493580-eb46-11e9-987c-fd367ecf094b.png)

**Comment by dnlutz** [comment]
never heard of this nonexistent island … but of course we can add it! there is still room in the private use area ; ) any volunteers?

**Comment by andest01** [comment]
for the interested, over the years an unofficial lore has developed that this is where the game Myst takes place...
