### ISSUE TITLE
U+1F237 Japanese “monthly amount” button lacks a horizontal stroke

### ISSUE THREAD

**Issue by mandel59** [hfg-gmuend/openmoji#41]
U+1F237 🈷️ Japanese “monthly amount” button lacks a horizontal stroke, and the left vertical stroke of it doesn't have Wān (curve; one of [CJK strokes]) 

[CJK strokes]: https://en.wikipedia.org/wiki/Stroke_(CJK_character)

https://github.com/hfg-gmuend/openmoji/blob/7587bc799048b332e0d64490a065acdc20d61665/black/svg/1F237.svg

**Comment by dnlutz** [comment]
fixed. is it okay like that?
![1F237](https://user-images.githubusercontent.com/38292227/66734752-92e2fb00-ee64-11e9-939c-86845ac8533a.png)

**Comment by mandel59** [comment]
Looks good!
Although the character seems placed at slightly left of center, the shape is great.

**Comment by dnlutz** [comment]
@b-g here's the corrected svg file 
[1F237.zip](https://github.com/hfg-gmuend/openmoji/files/3780042/1F237.zip)

**Comment by b-g** [comment]
Done https://github.com/hfg-gmuend/openmoji/commit/17ac23ecfc16ac8829569dce70e0e1ad3d7e5ef0
