### ISSUE TITLE
Generate WOFF2 fonts for use on websites

### ISSUE THREAD

**Issue by JeppeKlitgaard** [hfg-gmuend/openmoji#413]
Now that _the color wars_ are approaching an end with COLRv1 appearing to be the emerging standard, we're approaching a point where OpenMoji could possibly be used on websites – I am quite keen to try this on my own site. Ideally a version targeting websites would be made available using WOFF2 for compression.

I am currently working on setting up a build environment for this.

**Comment by b-g** [comment]
That's great! Please let us know how it goes, see also the endless saga of #260 ... and the current build process of the fonts in https://github.com/hfg-gmuend/openmoji/blob/master/helpers/generate-fonts.sh

**Comment by JeppeKlitgaard** [comment]
I am currently working on a small issue with `picosvg` over at https://github.com/googlefonts/picosvg/issues/278, but if we get that fixed it should be possible to finally sunset `scfbuild`

**Comment by JeppeKlitgaard** [comment]
Additionally since `nanoemoji` leverages the `ninja` build engine, I think we could tear out the old build system caching system, which would solve #403.

**Comment by JeppeKlitgaard** [comment]
I'm slightly more optimistic, partly on the back on COLRv1 now being implemented in all major browsers except Safari and Google making really good progress on their color font stuff - Noto Emoji seems to be a priority for them.

The `ninja` build system has a caching system with dependency resolution built in, essentially giving us the caching for free (and perhaps also more robustly). Changing this over would be an incremental change, as I believe `nanoemoji` and the existing build caching system can work together. I completely understand the frustration that I am sure you've felt around tooling, but I also feel that the best way to avoid more frustrations in the future will be to try and leverage as much tooling developed elsewhere as possible. If we can use much of the same tooling that Google uses for Noto Emoji, that would give us a really robust, long-term solution for very little effort (once changed over).

**Comment by b-g** [comment]
OK. Many thanks for the explanation! Great that your are optimistic! :) Happy to review a PR etc. 

Please note also, contributors come an go (which is great and much appreciated) but at the very end someone aka me will have to deal with any technical debt. As I'm busy with a lot of other things e.g. teaching / researching at my uni ... We won't be accepting anything which seems fancy now, but likely introduce even more work for us or has an uncertain future. Yes, what we have is bare metal and partly crappy ... but it works and we can deal alone with the complexity without having to rely on external contributors.

I'm just very upfront with my grumpy pragmatism, to not disappoint you. Please make sure to not potentially "waste" any time on this ... again we stopped investing any time into this issue after lots of wasted efforts.

**Comment by JeppeKlitgaard** [comment]
Oh no, I definitely appreciate that!

Would you (no guarantees given, of course) take a PR that:
1. Replaces `scfbuild` with `nanoemoji` (assuming this works)
	- This is for generation of TTF's with OT-SVG format and COLRv0 and COLRv1 (possibly also other formats supported by `nanoemoji`)
	- This would use a docker container, which is of equal complexity to the current approach
	- Additionally generates WOFF2 files from the TTFs

**Comment by b-g** [comment]
That would be very lovely! 🤞

One last note and esoteric requirement: as our audience involves a lot of designers ... it it important that at least one of the OpenMoji-fonts can be used in the current dominant tools like the Adobe CC Indesign. This works also with scfbuild. We are not a big fan of those, but it really helps in terms of designing all kind of things with OpenMoji.

**Comment by b-g** [comment]
👍 ! (Yes ... we can take care of checking in Adobe CC)
