### ISSUE TITLE
`1F4F5` has gaps

### ISSUE THREAD

**Issue by JeppeKlitgaard** [hfg-gmuend/openmoji#415]
The 'signage' in `1F4F5` has gaps. 

![image](https://user-images.githubusercontent.com/1814611/202152464-c67736be-a322-4ec4-9f32-acc3c0b7a87f.png)

**Comment by RobertWinslow** [comment]
I took a look at this, but I don't see any gaps.
![image](https://user-images.githubusercontent.com/5784659/209451330-94be6a85-ea96-4d98-9709-abab2265bb02.png)

**Comment by b-g** [comment]
Checked / Done
