### ISSUE TITLE
Spanish subdivision flags

### ISSUE THREAD

**Issue by Robot8A** [hfg-gmuend/openmoji#416]
Add the remaining Spain subdivision flags. So far only ES-AS, ES-CT and ES-PV implemented.
ES-AR, ES-IB and ES-VC could be easily implemented adapting ES-CT openmoji (as they all derive from the https://en.wikipedia.org/wiki/Senyera).
Also, ES-CN is equal to 🇮🇨.

**Comment by xavizardKnight** [comment]
Heyas! These lasts weeks I've returned to making more emojis, and I've finished all of the remaining Spain subdivision flags. Some of those still need a few tweaks here and there, but I'll have them done pretty soon.

![Captura de pantalla a 2024-03-30 18-50-16](https://github.com/hfg-gmuend/openmoji/assets/35200790/ef227e77-7ffb-4f34-8ce6-0a74bbcea1dd)

I'll open a PR in the upcoming days with these emojis and the other programming logos that I've mentioned in another issue (.NET, Kotlin and Go!). I'm having a few problems with NPM lately, will try to see what can I do to fix it…

**Comment by b-g** [comment]
Hi @xavizardKnight, Nice 😍! Would be super to have for a first country = Spain all the subdivision flags. Yay!

**Comment by xavizardKnight** [comment]
@b-g This issue can be closed as all the emojis are finally added, now that PR #495 has been merged.

**Comment by b-g** [comment]
Thanks + yay!
