### ISSUE TITLE
A red cross should not be used

### ISSUE THREAD

**Issue by maekawa-mugi** [hfg-gmuend/openmoji#417]
A red cross is used in the ambulance (U+1F691) emojis.
The Geneva Convention and Japanese law limit the use of the Red Cross to the Red Cross Society in principle.

Therefore, I propose that it should be changed to a blue asterisk instead.

**Comment by maekawa-mugi** [comment]
Additional Info:
Mr. Shigeta (ex. Docomo), known as the father of the emoji, spoke about the hospital emoji on Twitter.
According to his story, the Red Cross pointed out that the emoji colors have been changed.

https://twitter.com/sigekun/status/24565482257
https://twitter.com/sigekun/status/1578740490325094402

**Comment by carlinmack** [comment]
I understand and in principle agree, however[ many platforms still use the red cross](https://emojipedia.org/ambulance/) and so we will delay this change unless someone contributes a pull request. I hope this is okay

**Comment by b-g** [comment]
Done
