### ISSUE TITLE
Red hair is hard to see

### ISSUE THREAD

**Issue by pyfisch** [hfg-gmuend/openmoji#42]
While the default hair color for many people emoji is distinct from red hair it is very hard to spot the difference. Take for example the "woman" emoji and the "woman with red hair" emoji.

![](https://openmoji.org/data/color/618x618/1F469.png)
![](https://openmoji.org/data/color/618x618/1F469-200D-1F9B0.png)

**Comment by dnlutz** [comment]
you are right. but i think the real issue here ist that we don't have correct skin tone variations for "man and woman with red hair" at the moment. we will rather fix that: with the right skin tones, differentiation won't be a problem anymore.

**Comment by pyfisch** [comment]
> with the right skin tones, differentiation won't be a problem anymore.

I'm not sure if I understand you. Emojis with the red hair modifier can have all the same Fitzpatrick modifiers as other emoji.

**Comment by dnlutz** [comment]
F4AA41 is too close to our standard hair color F1B31C. i would suggest we switch all the red hair to E27022. then it is easier to spot the difference. ok?
<img width="1044" alt="red_hair" src="https://user-images.githubusercontent.com/38292227/68040812-5ec66180-fccf-11e9-8e21-b82046c629fa.png">

**Comment by pyfisch** [comment]
I really like the new color. It is very clearly red hair but still fits
well with the other emoji.

Am Freitag, den 01.11.2019, 09:49 -0700 schrieb Daniel Utz:

**Comment by b-g** [comment]
@dnlutz Same here! Nice compromise (in a good way)! Will update the new red hair color in the next days. Stay tuned.

**Comment by b-g** [comment]
Done!
