### ISSUE TITLE
Short clock hands are 30 minutes behind when half past the hour

### ISSUE THREAD

**Issue by Kaktus514** [hfg-gmuend/openmoji#423]
When a real clock is half past the hour the short hand will point in between two hour marks. For example if the clock is half past twelve the short hand will point between the _twelve_ and the _one_ but the [twelve-thirty](https://openmoji.org/library/emoji-1F567/) emoji in OpenMoji points straight at the _twelve_.

OpenMoji is far from the only emoji font that have this "problem". It seems like the majority do it this way, so maybe there if a reason for it, but I don't get it.

**Comment by b-g** [comment]
Many thanks for the hints and spotting such nice details! Please be more visual and provide images. This will help to make this issue more verbose and actionable.

**Comment by b-g** [comment]
Fixed with #465. Thanks @jkaving 🙏 !
