### ISSUE TITLE
"man: bald" and "woman: bald" look the same

### ISSUE THREAD

**Issue by pyfisch** [hfg-gmuend/openmoji#43]

**Comment by carlinmack** [comment]
Looking at [man bald](https://emojipedia.org/man-bald/) and [woman bald](https://emojipedia.org/woman-bald/) I think the best way to tackle this would be to alter the default woman head to have a pointed chin and/or lower set eyes. I think that adding make up or making lips fuller is a bit outdated and wouldn't fit with the style of the project.

It's a difficult design choice as it is hard to depict [differences in the skull](https://en.wikipedia.org/wiki/Human_skeleton#Skull) such as the [brow ridge](https://en.wikipedia.org/wiki/Brow_ridge#Structure) in such a simple style. 

Alternatively we could go the google way and colour code them, but that's a bit weak

**Comment by dnlutz** [comment]
thank you for your detailed comment @carlinmack. i agree with you, we should leave the bald emoji as they are. in real life man and women without hair are often very difficult (or impossible) to distinguish. why should it be different with the corresponding emoji ; ) ?

**Comment by pyfisch** [comment]
> why should it be different with the corresponding emoji

Because Emojis should imho make communication easier. Having one person send bald woman

**Comment by carlinmack** [comment]
Also emoji helps people express their identity and gender identity is an important part of that - it is a

**Comment by dnlutz** [comment]
thank you for your opinions. i can understand your arguments and we've been thinking this over but for the moment we would like to leave the bald emoji as they are. openmoji are more simplified than most of the other platforms. too many details (in the eyes or eyebrows) would not fit to the overall system. but maybe we will give it a try in the future.
