### ISSUE TITLE
New Antarctica Flag Emoji Design Suggestion

### ISSUE THREAD

**Issue by SecularSteve** [hfg-gmuend/openmoji#445]
As originally proposed and established in 2018 under a more open and clear licence by Evan Townsend:

![True_South_Antarctic_Flag.svg.png](https://user-images.githubusercontent.com/33793273/228581352-c20a4b60-e014-4ac5-8143-b6a2552cdb60.png)

Turns out the Blue Flag is in more legal limbo than we let on:

https://www.youtube.com/watch?v=U0wTDK0VOeY

And it looks better anyway.

**Comment by shankarsivarajan** [comment]
I think the legal argument is specious, but I agree this should be changed simply primarily because it looks better, but also because it's actually widely used, including _in Antarctica._

**Comment by SecularSteve** [comment]
#366
