### ISSUE TITLE
OpenMoji 15.0

### ISSUE THREAD

**Issue by jyo0329** [hfg-gmuend/openmoji#446]
![ロバとワイヤレス無線](https://user-images.githubusercontent.com/129174637/232261309-5ddaf949-7c9e-4d9b-854f-201801d89980.svg)
emoji 15.0 was announced last year
As a custom emoji in it There are donkeys and wireless Those two emojis are in emoji 15.0

**Comment by jyo0329** [comment]
![1F499 (2)](https://user-images.githubusercontent.com/129174637/232261467-afdcb072-745d-4e50-b3d9-e6afb0d2a53b.svg)
I thought that the blue heart was so light blue

**Comment by jyo0329** [comment]
![1F499 (2)6](https://user-images.githubusercontent.com/129174637/232291185-071cce36-eae2-48be-b8a8-aa7c49c6cd2d.svg)

**Comment by jyo0329** [comment]
everyone please comment.

**Comment by carlinmack** [comment]
@b-g I could move these to the official set if you're on board 👍

**Comment by b-g** [comment]
@carlinmack that would be wonderful! ❤️

**Comment by carlinmack** [comment]
We need emojibase to update first right? If so I think we're waiting on https://github.com/milesj/emojibase/pull/146 to be merged

**Comment by b-g** [comment]
@carlinmack managed to gentle ping milesj to release emojibase-data 15.0. Had to move a few src svgs to reflect some subgroup changes. Daniel and myself are trying to come up with the missing ones over the summer, see `data/openmoji-emoji-unicode-missing.csv`.
