### ISSUE TITLE
water bottle

### ISSUE THREAD

**Issue by per9000** [hfg-gmuend/openmoji#447]
Suggestion: image representing water in a bottle. 

I was thinking of some inexpensive plastic bottle in (blue) rippled plastic bottle, e.g. https://en.wikipedia.org/wiki/File:PET_Bottle_Water.jpg but perhaps it could also be a large water cooler style e.g. style https://en.wikipedia.org/wiki/File:Watercooler_Wikinews.jpg or even some other style.

It could be based on baby bottle https://openmoji.org/library/emoji-1F37C/ .

PS: I was looking for one but was surprised when I did not find it.

**Comment by b-g** [comment]
Done #454
