### ISSUE TITLE
Incorrect skin tone for kiss: man, man

### ISSUE THREAD

**Issue by kezsulap** [hfg-gmuend/openmoji#456]
In all the variants with different skin tones the left man has yellow skin rather than the selected tone.
https://openmoji.org/library/emoji-1F468-200D-2764-FE0F-200D-1F48B-200D-1F468/#variant=1F468-1F3FF-200D-2764-FE0F-200D-1F48B-200D-1F468-1F3FB
I looked through all emojis with skin tone colours and I believe this is the only one with this issue (but I can't be sure of course)

**Comment by b-g** [comment]
Hi @kezsulap, many thanks for reporting! Confirmed, this is a bug. We will look into it.

**Comment by b-g** [comment]
Done.
