### ISSUE TITLE
Add a licence for the code

### ISSUE THREAD

**Issue by roipoussiere** [hfg-gmuend/openmoji#46]
The [license section](https://github.com/hfg-gmuend/openmoji#license) explains that

> the emojis are licensed under the Creative Commons Share Alike 4.0 (CC BY-SA 4.0) license.

But there is no mention about the license of the code: more precisely, all files that are not images, such as test scripts, jsons, build configurations, etc.

Ideally the license section should contains 2 parts: one for the graphics and the other for the code, like in the [twemoji license section](https://github.com/twitter/twemoji/#license).

A good candidate is MIT, but take time to [chose a license](https://choosealicense.com/) according to your needs. ;)

Without a license, the work is under exclusive copyright by default and nobody else can copy, distribute, or modify your code (see also [No License](https://choosealicense.com/no-permission/)).

**Comment by b-g** [comment]
@roipoussiere Many thanks for the little push! Yes you are right ... that it would be appropriate to do this for everything but the emojis under CC BY-SA 4.0.

But I'm leaning more toward something not permissive e.g. GNU like https://github.com/processing/p5.js/blob/master/license.txt

Any feelings and comments on this? cc @dnlutz

**Comment by dnlutz** [comment]
the gnu license sounds reasonable to me.

**Comment by spVierSechs** [comment]
I'm definitely for LGPLv3, because OpenMoji and it's code is definitely not that bad of a library. Especially the meta stuff.

**Comment by b-g** [comment]
Done https://github.com/hfg-gmuend/openmoji/commit/f9d50d4a5c7e82666ad2b44f5827fa569b9d9e62
