### ISSUE TITLE
Question about commercial use

### ISSUE THREAD

**Issue by xavizardKnight** [hfg-gmuend/openmoji#462]
Heyas! First of all, thank you so much for this fantastic project. These emojis are beautiful!

I have a question regarding the CC-BY-SA-4.0 licence that OpenMoji uses, specifically regarding the Share-alike aspect.

I understand that if I edit an emoji, or I grab something from an emoji to create another one of my own, then I need to release this derived work using the same CC-BY-SA licence as OpenMoji. (In fact, I'm creating some emojis of my own that I'll release in a CC-BY-SA-4.0 repo when I finish them)

But, If I'm only using them without modifications in a project, like for using them as icons in a desktop application or for chat emojis in a videogame, for example; then do I need to release the entirety of said application or videogame project as CC-BY-SA as well?

Other similar open-source emoji packs like Emojitwo, Tweetmoji or Microsoft's Fluent Emoji, use permissive licences like CC-BY-4.0 or the MIT licence, which allows both commercial and non-commercial use only with attribution required and no share-alike. Some of these projects directly specify that commercial use with attribution is allowed.

But OpenMoji doesn't specify any of that. In [your FAQ page](https://openmoji.org/faq/), in the question “What's the license of OpenMoji for app / website / book / ad / video … projects?”, there is written the human-readable summary of the CC-BY-SA-4.0 licence, but no mention if “use” = “sharealike”.

I ask this because the CC-BY-SA-4.0 licence can be quite confusing in terms of what counts as “derivative works” or “collective works”. StackExchange has several questions like [here](https://opensource.stackexchange.com/questions/6542/creative-commons-license-cc-by-sa-doesnt-work-for-commercial-content), [here](https://opensource.stackexchange.com/questions/6777/can-i-use-source-code-licensed-under-cc-by-sa-for-commercial-closed-source-proje), [here](https://gamedev.stackexchange.com/questions/92536/is-it-legal-to-use-creative-commons-art-in-a-commercial-game) or [here](https://opensource.stackexchange.com/questions/7022/using-cc-by-sa-music-in-a-podcast/7036#7036), for example; of users asking about the sharealike of this licence, with different answers per question. One of the answers reefer to the [US court case of 'Drauglis v. Kappa Map Group, LLC'](https://en.wikipedia.org/wiki/Creative_Commons_license#Drauglis_v._Kappa_Map_Group,_LLC) as a precedent for the collective works vs derivate works in CC-BY-SA-2.0. But it seems this has changed in the 4.0 version.

Due to this confusion, I think that the best that I can do to solve this, is to directly ask about your interpretation of the licence.

If I only use your OpenMoji emojis, with no alterations, in a software/game, either commercially or non-commercially, and with correct attribution, will I need to release the source code as CC-BY-SA as well, or I can keep it under another licence (or closed-source)?

If your interpretation of the CC-BY-SA-4.0 licence disallows the commercial use in the same way as Tweetmoji or other emoji libraries do allow it, then this might be a serious disadvantage of OpenMoji when compared against other emoji libraries.

Sorry for such a long question text and for if this ends up being a stupid question, but I prefer to ask it anyway just to be safe.
Thank you for your work and have a nice day!

**Comment by b-g** [comment]
Hi @xavizardKnight, I will answer inline ... also I'm not a lawyer, this is how we/I think it is "correct":

> I understand that if I edit an emoji, or I grab something from an emoji to create another one of my own, then I need to release this derived work using the same CC-BY-SA licence as OpenMoji. (In fact, I'm creating some emojis of my own that I'll release in a CC-BY-SA-4.0 repo when I finish them)

✅ Yes

> But, If I'm only using them without modifications in a project, like for using them as icons in a desktop application or for chat emojis in a videogame, for example; then do I need to release the entirety of said application or videogame project as CC-BY-SA as well?

❌ No, you don't have to release the entirety e.g. you app, game, film ... under CC-BY-SA, but I believe you must credit the use of OpenMoji. We suggest this attribution putting it somewhere where interested people could find it e.g. footer, video title endcard, about section etc.: "All emojis designed by [OpenMoji](https://openmoji.org/) – the open-source emoji and icon project. License: [CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/#)"

> Other similar open-source emoji packs like Emojitwo, Tweetmoji or Microsoft's Fluent Emoji, use permissive licences like CC-BY-4.0 or the MIT licence, which allows both commercial and non-commercial use only with attribution required and no share-alike. Some of these projects directly specify that commercial use with attribution is allowed.

✅ Yes, we believe OpenMoji is with CC BY-SA 4.0 under a commercial permissive licence. We ask only for attribution, see above.

> But OpenMoji doesn't specify any of that. In [your FAQ page](https://openmoji.org/faq/), in the question “What's the license of OpenMoji for app / website / book / ad / video … projects?”, t[here](https://opensource.stackexchange.com/questions/6542/creative-commons-license-cc-by-sa-doesnt-work-for-commercial-content) is written the human-readable summary of the CC-BY-SA-4.0 licence, but no mention if “use” = “sharealike”.

> I ask this because the CC-BY-SA-4.0 licence can be quite confusing in terms of what counts as “derivative works” or “collective works”. StackExchange has several questions like [here](https://opensource.stackexchange.com/questions/6777/can-i-use-source-code-licensed-under-cc-by-sa-for-commercial-closed-source-proje), [here](https://gamedev.stackexchange.com/questions/92536/is-it-legal-to-use-creative-commons-art-in-a-commercial-game), [here](https://opensource.stackexchange.com/questions/7022/using-cc-by-sa-music-in-a-podcast/7036#7036) or here, for example; of users asking about the sharealike of this licence, with different answers per question. One of the answers reefer to the [US court case of 'Drauglis v. Kappa Map Group, LLC'](https://en.wikipedia.org/wiki/Creative_Commons_license#Drauglis_v._Kappa_Map_Group,_LLC) as a precedent for the collective works vs derivate works in CC-BY-SA-2.0. But it seems this has changed in the 4.0 version.

😶‍🌫️ We struggle with it as well. Sorry! Again we are not lawyers and we just wanted to put OpenMoji under a common and permissive licence ... which just makes sure that the project gets credits and can't be forked without giving the project credits.

> If I only use your OpenMoji emojis, with no alterations, in a software/game, either commercially or non-commercially, and with correct attribution, will I need to release the source code as CC-BY-SA as well, or I can keep it under another licence (or closed-source)?

✅ Yes, you can keep your software/game under any licence (or closed-source) ... but you must have an attribution/credit for OpenMoji

> If your interpretation of the CC-BY-SA-4.0 licence disallows the commercial use in the same way as Tweetmoji or other emoji libraries do allow it, then this might be a serious disadvantage of OpenMoji when compared against other emoji libraries.

❌ No, in our interpretation of the CC-BY-SA-4.0 licence allows the commercial use!! This was actually the very starting point of everything, we believe that the licences of e.g. Apple doesn't allow the use of their emojis at all, hence we started this project! :)

> Sorry for such a long question text and for if this ends up being a stupid question, but I prefer to ask it anyway just to be safe. Thank you for your work and have a nice day!

🙏 Many thanks for your valid questions! It is such a pity that this is all so complicated! I will add this issue here to your FAQ to hopefully clearly these questions even further for everyone.

**Comment by xavizardKnight** [comment]
Thank you so much for your detailed clarification. I agree that editing the FAQ will be a good idea to help other people that might also have the same question as me. Licences are complicated, especially when they are as long as the CC-BY-SA full text is. Thanks again!

**Comment by brendon-wong** [comment]
I just want to make a note for anyone else considering using OpenMoji that unfortunately, as @xavizardKnight alluded to, the license is in fact risky for use in any media or project that the creator doesn't want to release to the public under the same terms as OpenMoji. This would be a disaster for any serious project that isn't intended to be fully open source, whether commercial or noncommerical.

I'm not certain it matters that @b-g states that their current interpretation of the license is that they won't force the open sourcing of anything touching the library. Legally speaking, you may be giving up that right according to the legal terms you agree to by using OpenMoji, regardless of what a particular contributor to OpenMoji says.

See here for more information about the risks of this particular license: https://osmfoundation.org/wiki/Licence_and_Legal_FAQ/Why_CC_BY-SA_is_Unsuitable

This license is not OSI approved and the risk could be high depending on the situation: https://www.synopsys.com/blogs/software-security/top-open-source-licenses.html

I would strongly recommend that OpenMoji select a license that requires attribution but **does not** have a provision for sharealike, which essentially forces anything using OpenMoji to be released under the same license (even if it is closed source!).
