### ISSUE TITLE
Suggestion: Discord and Reddit brand emojis

### ISSUE THREAD

**Issue by alfister** [hfg-gmuend/openmoji#466]
I was looking to use openmoji for a project, but a couple brands I would need are missing, notably discord and reddit. 

<img width="125" alt="image" src="https://github.com/hfg-gmuend/openmoji/assets/64699476/cc9479c8-4e2c-4435-a73e-19a8e848035b">
<img width="110" alt="image" src="https://github.com/hfg-gmuend/openmoji/assets/64699476/ca16579a-276f-48c3-9965-f5ca9ab9ec72">

I think a lot of people would find these useful, so if you guys are interested I'd be happy to assign them to myself.

Lmk what you think!

**Comment by b-g** [comment]
Hi @alfister, good call. Yes probably a lot of people would find this useful. Happy to include them, if you take care of them (and if the logos follow the OpenMoji styleguide :)
