### ISSUE TITLE
Windsurfing emoji

### ISSUE THREAD

**Issue by moftasa** [hfg-gmuend/openmoji#469]
I would like to propose a windsurfing emoji for the OpenMoji collection. Windsurfing is a fairly established watersport that was developed in the 1960s and became an Olympic sport in 1984. A windsurfing emoji can also be used as a stand-in for several related watersports such as wind foiling, kitesurfing and wing-foiling. 

Windsurfing is not part of the standard unicode emojis. 

I have attached my design which combines elements from the surfing and rock climbing emojis. 

If you guys like it and think it is a useful addition to OpenMoji, I would be happy to try to contribute it through a pull request. But I may need some help in naming the file as it is a non-standard emoji and I am struggling to understand the instructions on naming. 
![windsurfing-openmoji-standard-compliant-optimised](https://github.com/hfg-gmuend/openmoji/assets/1017635/7ae19297-c5ed-4542-a590-6cb2719779f6)

**Comment by b-g** [comment]
Hi @moftasa, many thanks for this! Looks really nice! Happy to add this under `extras-openmoji` / `people` with the next available hexcode of `E189`. If then hopefully once the Windsurfing emoji becomes official, we would move it to the standard unicode. Looking forward for your PR :)

**Comment by moftasa** [comment]
Sorry, couldn't do a pull request (getting lots of error) and I resorted to emailing the file instead.

**Comment by b-g** [comment]
Hi @moftasa, sure! Email is fine as well! :) Sorry that installing all the cli tools is such a hustle. 

Just the https://openmoji-tester.glitch.me/ reports, that there is a "hole" visually in the middle of the sail. Could you fill this with a white background? Other then that I think we were good to go.

Note to self: add meta data
```
,E189,extras-openmoji,people,windsurfing,"windsurfing, watersport", Mostafa Hussein Omar, 2023-09-29

```

<img width="1018" alt="Screen Shot 2023-10-04 at 11 01 17" src="https://github.com/hfg-gmuend/openmoji/assets/480224/fa5f37a5-2866-40c5-ba7c-ba03543245cc">

**Comment by moftasa** [comment]
Well, I am a little conflicted. Technically, this hole is realistic because it depicts the transparent part of the sail that prevents the person's view from being blocked in certain occasions while windsurfing. However, I agree that it looks a little strange in dark mode and may be an extra complexity to an emoji. I have attached it here, should I still email it?
![E189_nohole](https://github.com/hfg-gmuend/openmoji/assets/1017635/aed57eed-9797-4c6b-a3d5-9e239e82d71b)

**Comment by b-g** [comment]
Many thanks for this! I see. You could try to hint the "window" with the lightest grey? But not sure this would loo better in the end. Please decide on your own. 

Posting here the svg file is fine. Just let me know once it is final / how you decide with the window.

**Comment by moftasa** [comment]
Ok, I think I am decided now. The one in my previous comment is the final (opaque white non-window).

**Comment by b-g** [comment]
Done! Many thanks!!
