### ISSUE TITLE
Add special interest emoji: "DJ" (disc jockey, party)

### ISSUE THREAD

**Issue by b-g** [hfg-gmuend/openmoji#47]

**Comment by lizbravob** [comment]
Hey :) What do you think about this?
[openmoji_dj.zip](https://github.com/hfg-gmuend/openmoji/files/8200312/openmoji_dj.zip)

**Comment by dnlutz** [comment]
nice!!! i like both versions but v1 looks a bit more professionial.
v2 is a poser … a real dj takes her work serious and keeps a hand on the turntables ; )
i would suggest we keep the minimum line width for the headphones?
![dj v1_mod](https://user-images.githubusercontent.com/38292227/157189097-bad1553a-a334-41a7-9168-42816c543155.svg)

**Comment by b-g** [comment]
@lizbravob Wow! I agree a hand on the turntables and one in air "hyper hyper" seems to be the perfect balance :)
<img width="1054" alt="Screen Shot 2022-03-08 at 08 54 49" src="https://user-images.githubusercontent.com/480224/157191995-1e4c220d-a0e5-4f98-aaf7-8415f528e507.png">

**Comment by b-g** [comment]
Thanks! +1 Yes to a female DJ ... but find that the pony tail looks more like a m
<img width="1054" alt="Screen Shot 2022-03-08 at 13 29 57" src="https://user-images.githubusercontent.com/480224/157238605-839bb4fb-7a16-4715-b40c-ca65c0c83834.png">
ic headset. Hmm. @dnlutz any idea?

**Comment by dnlutz** [comment]
<img width="962" alt="dj woman_test" src="https://user-images.githubusercontent.com/38292227/157619824-00d385ab-4332-4547-8dde-ce5a609f0fb8.png">
probably it is sufficient to modify the body. i think it works without additional hair. what do you think? 
i have enlarged the head a little bit so that it matches with the size of the body.
 
[dj woman_test.ai.zip](https://github.com/hfg-gmuend/openmoji/files/8221568/dj.woman_test.ai.zip)

**Comment by b-g** [comment]
Hi @lizbravob, OK? (see previous post). Could we finish this? We would love to include this! :)

**Comment by lizbravob** [comment]
Hi!! Yes, I agree with the female DJ  👏🏻

**Comment by b-g** [comment]
@dnlutz could please prepare the the female DJ src svg file?

Also what should be the hexcodes?

- person DJ: 1F9D1-200D-???
- male DJ: 1F468-200D-???
- female DJ: 1F469-200D-???

**Comment by b-g** [comment]
Done
