### ISSUE TITLE
(suggestion) improve woman symbol understandability

### ISSUE THREAD

**Issue by sotha1** [hfg-gmuend/openmoji#472]
(i don't know this is the best place for suggestions) my suggestion is to improve the understandability of woman symbols because as a layman i think that when you look at the woman current symbol you may confuse it, thinking that is a man, due to the less number of details. see this original one
![1F6BA_color(1)](https://github.com/hfg-gmuend/openmoji/assets/149703967/61933f8d-9b22-4a4b-b67d-9dc5a96801b5)
and my one:
![1F6BA_color](https://github.com/hfg-gmuend/openmoji/assets/149703967/6e3beb69-d795-411f-9327-8e4ea8aaf28e)
![1F6BB_color](https://github.com/hfg-gmuend/openmoji/assets/149703967/272c4d39-0afe-4759-b08e-4f8405103a45)
remembering that all of this is my opinion, and its also a simple detail

**Comment by b-g** [comment]
Dear @sotha1, many thanks for the thoughts and suggestions! This Github repo is definitively the right spot to discuss theses things ... and we are happy to get feedback and suggestions! 

I've discussed the pony tail detail with Daniel Utz and ca. 25 students in an Openmoji related course here at uni. We don't think we should add it, as yes it probably is a bit more "readable" ... but the trade off is that it helps to reproduce the cliche women = long hair, which we think we should avoid this time, as the current Openmoji is still enough readable in terms of genders. I hope you understand.

Please re-open if I have overseen something.

**Comment by sotha1** [comment]
i understand, and i accord to that reason!
