### ISSUE TITLE
Specified hair color is not shown when combined with skin tone modifiers

### ISSUE THREAD

**Issue by sourgift** [hfg-gmuend/openmoji#48]
Example: https://emojipedia.org/person-with-blond-hair-type-5/

The relevant indicators are Blond Person U+1F471, Red Hair U+1F9B0, and White Hair U+1F9B3.

When specified, the hair color should be the same regardless of skin tone.

**Comment by b-g** [comment]
Hi @sourgift,

you are referring to the 3 emojis of: https://openmoji.org/library/#search=1F471, correct? This seems to be a mistake of us.

The combinations of Red Hair U+1F9B0 and White Hair U+1F9B3 are not yet part of OpenMoji. Combinations for both are not part of Unicode Emoji 12, hence also currently not supported.

@dnlutz, please confirm that we've got it wrong.

**Comment by sourgift** [comment]
Yes, this includes Blond Person, Blond Man and Blond Woman.  The components for red hair, curly hair, white hair and bald are part of Emoji 12 https://unicode.org/emoji/charts/full-emoji-modifiers.html.  Note that curly hair and bald work as expected already in OpenMoji.

**Comment by b-g** [comment]
@sourgift OK. Convinced! :) My bad! 

Will have to fix the way the skintones variants are generated! Basically:

- Buggy: Blond Person U+1F471
- Already correct: Red Hair U+1F9B0
- Already correct: Curly Hair
- Already correct: White Hair U+1F9B3

Please confirm.

**Comment by sourgift** [comment]
I confirm, but I've added some detail below to be more explicit.

The following emoji should have blond hair:
* person: blond hair 1F471
* person: light skin tone, blond hair 1F471-1F3FB
* person: medium-light skin tone, blond hair 1F471-1F3FC
* person: medium skin tone, blond hair 1F471-1F3FD
* person: medium-dark skin tone, blond hair 1F471-1F3FE
* person: dark skin tone, blond hair 1F471-1F3FF
* **man: blond hair 1F471-200D-2642-FE0F**
* man: light skin tone, blond hair 1F471-1F3FB-200D-2642-FE0F
* man: medium-light skin tone, blond hair 1F471-1F3FC-200D-2642-FE0F
* man: medium skin tone, blond hair 1F471-1F3FD-200D-2642-FE0F
* man: medium-dark skin tone, blond hair 1F471-1F3FE-200D-2642-FE0F
* man: dark skin tone, blond hair 1F471-1F3FF-200D-2642-FE0F
* **woman: blond hair 1F471-200D-2640-FE0F**
* woman: light skin tone, blond hair 1F471-1F3FB-200D-2640-FE0F
* woman: medium-light skin tone, blond hair 1F471-1F3FC-200D-2640-FE0F
* woman: medium skin tone, blond hair 1F471-1F3FD-200D-2640-FE0F
* woman: medium-dark skin tone, blond hair 1F471-1F3FE-200D-2640-FE0F
* woman: dark skin tone, blond hair 1F471-1F3FF-200D-2640-FE0F

The following emoji should have red hair:
* **red hair 1F9B0**
* **man: red hair 1F468-200D-1F9B0**
* man: light skin tone, red hair 1F468-1F3FB-200D-1F9B0
* man: medium-light skin tone, red hair 1F468-1F3FC-200D-1F9B0
* man: medium skin tone, red hair 1F468-1F3FD-200D-1F9B0
* man: medium-dark skin tone, red hair 1F468-1F3FE-200D-1F9B0
* man: dark skin tone, red hair 1F468-1F3FF-200D-1F9B0
* **woman: red hair 1F469-200D-1F9B0**
* woman: light skin tone, red hair 1F469-1F3FB-200D-1F9B0
* woman: medium-light skin tone, red hair 1F469-1F3FC-200D-1F9B0
* woman: medium skin tone, red hair 1F469-1F3FD-200D-1F9B0
* woman: medium-dark skin tone, red hair 1F469-1F3FE-200D-1F9B0
* woman: dark skin tone, red hair 1F469-1F3FF-200D-1F9B0

The following emoji should have white hair:
* **white hair 1F9B3**
* **man: white hair 1F468-200D-1F9B3**
* man: light skin tone, white hair 1F468-1F3FB-200D-1F9B3
* man: medium-light skin tone, white hair 1F468-1F3FC-200D-1F9B3
* man: medium skin tone, white hair 1F468-1F3FD-200D-1F9B3
* man: medium-dark skin tone, white hair 1F468-1F3FE-200D-1F9B3
* man: dark skin tone, white hair 1F468-1F3FF-200D-1F9B3
* **woman: white hair 1F469-200D-1F9B3**
* woman: light skin tone, white hair 1F469-1F3FB-200D-1F9B3
* woman: medium-light skin tone, white hair 1F469-1F3FC-200D-1F9B3
* woman: medium skin tone, white hair 1F469-1F3FD-200D-1F9B3
* woman: medium-dark skin tone, white hair 1F469-1F3FE-200D-1F9B3
* woman: dark skin tone, white hair 1F469-1F3FF-200D-1F9B3

Lines in **bold** already have the appropriate hair color

Note - person: red hair, person: white hair and variants are part of Emoji 12.1 and not included here.

The inconsistent face and hair shape of person: blond is a separate issue.

**Comment by b-g** [comment]
Many thanks! Very helpful!

I think the problem is that we are using [`"emojibase-data": "^4.0.0-alpha.0"`](https://github.com/milesj/emojibase/tree/master/packages/data) as the main dependency to pull the Unicode definitions and the ones not in bold are simply not included. So I will have to update to the latest version and see whether they are included now, if so we should be able to generate the missing files while fixing the issues. 

But this is a bigger thing ... very likely for the next OpenMoji version. 

(Happy to get a hand on it ... wink wink ;)

**Comment by sourgift** [comment]
I'm starting to get confused.  The emoji I mentioned are in data/openmoji.csv, the base images (without skin tone modifiers) are in src/ and the skin tone images are generated using the helpers/export-svg-skintones.js script. The script changes the hair color based on skin tone. https://github.com/hfg-gmuend/openmoji/blob/b4e8448e5a5d62c5c89605bf9ce83f97320f1794/helpers/export-svg-skintones.js#L21 In most cases that is the right way to do it. There needs to be an exception made when blond, red or white hair is specified.

I'm not sure how emojibase-data is relevant, aside from emoji versions greater than 12.0.

**Comment by sourgift** [comment]
I just noticed that the solution for 'older person' emoji from commit 19893fb9dbdb521833d9b1518fb11c49b98bc8b5 was to move the hair shape to the color group.

My suggested solution (like in the pull request) is to add an exception to the generation script instead.

Which is the preferred solution?

**Comment by b-g** [comment]
Hi @sourgift, Many thanks for your contribution! Currently traveling ... so just quickly: I think your solution is better! I would prefer to have every "hair shape" in the hair layer. Seems to be semantically more correct and cleaner. So we have to move the grey hair of "older person" back to the hair layer. Could you add that to your PR, so that we can merge everything in one go?

**Comment by sourgift** [comment]
I've added the older person emojis to the pull request.

**Comment by b-g** [comment]
Done
