### ISSUE TITLE
Same heart color of the BLUE HEART emoji (U+1F499) and LIGHT BLUE HEART emoji (U+1FA75)

### ISSUE THREAD

**Issue by Benzuhaus** [hfg-gmuend/openmoji#483]
Hi,
I just found out that the two heart emojis "Blue Heart" and "Light Blue Heart" do have the same color in your new 15.0 release. They both have color hex-number #92d3f5.

As light blue heart emoji was added later with the release of Unicode 15.0 in 2022, the blue heart emoji already exists since 2010. 

Light blue heart:
![light-blue-heart-1fa75](https://github.com/hfg-gmuend/openmoji/assets/83719011/2a710287-0b5a-4091-a36e-ebf8399aacf1)

Blue heart:
![blue-heart-1f499](https://github.com/hfg-gmuend/openmoji/assets/83719011/7f0a7540-3b84-4f19-8cfb-30e78fb92992)

Best regards
Benjamin

**Comment by b-g** [comment]
Thanks for spotting! True! Just fixed it :)
