### ISSUE TITLE
Download named normal

### ISSUE THREAD

**Issue by katastrophe92** [hfg-gmuend/openmoji#487]
Hello y'all! How can I download the colored pack with emojis named not in unicode? Hope it can be understanding what I mean. Thank you!

**Comment by b-g** [comment]
Many thanks for the interest! But I'm afraid we won't be able to provide this. You could code this on your own by using the infos in data/openmoji.json to rename the OpenMoji png / svg files.

**Comment by katastrophe92** [comment]
Hey @b-g thanks for the replay! How could I do this, could you give me a quick explanation?

**Comment by b-g** [comment]
Plz check: data/openmoji.json https://github.com/hfg-gmuend/openmoji/blob/master/data/openmoji.json ... the file holds all the informations you need for renaming. Good luck.
