### ISSUE TITLE
Lobster (1F99E) is missing some transparency

### ISSUE THREAD

**Issue by adamshand** [hfg-gmuend/openmoji#490]
Hello,

First time participating here, hopefully I'm not misunderstanding anything.  I believe that the lobster emoji has a white background between it's claws (instead of transparent).  Screenshot attached.

![image](https://github.com/hfg-gmuend/openmoji/assets/130651/6f217240-70e7-4720-b06d-0353f0a52e68)

Loving the Openmoji project, having a lot of fun using it on my website.  Thank you to everyone who has helped to create it! :-) <3

Best wishes from New Zealand,
Adam.

**Comment by b-g** [comment]
Hi @adamshand, Many thanks for spotting :) Fixed! All the best to New Zealand, Benedikt
