### ISSUE TITLE
Question about license with respect to images rendered by an app

### ISSUE THREAD

**Issue by romadox** [hfg-gmuend/openmoji#503]
Hello,

A few months ago I used OpenMoji in a little [trading-card generator](https://nashhigh.itch.io/fedi-cardmaker) me & a friend made. I tried to adhere to the CC-BY-SA license & included the suggested attribution in the notes of our project page, with an added note that the emoji meta-data also came from your project (as it was a tremendous help to me--thank you!).

Someone has just pointed out though that since the rendered trading cards contain OpenMoji graphics & do not have an attribution on the cards themselves, this could be a violation of the license. I'm not great at legal & copyright stuff & don't pretend to know, but either way the most important thing to me is how you all feel about the implementation of the license & my use of your work. Should the rendered cards also have attribution for the font?

Thanks,
Nash

**Comment by b-g** [comment]
Hi Nash, as said many times ... this is IMO fine. Sorry about all the license mess. All the best, Benedikt
