### ISSUE TITLE
Gun emoji

### ISSUE THREAD

**Issue by Casper-969** [hfg-gmuend/openmoji#504]
Currently, the gun emoji on Openmoji displays as a real handgun, other platforms displays as a water gun.

**Comment by b-g** [comment]
We are following the Unicode standard ... where it is defined as a gun and not a water gun. Sorry! But happy to add an additional water gun if you provide a PR.

**Comment by b-g** [comment]
See also the old discussions https://github.com/search?q=repo%3Ahfg-gmuend%2Fopenmoji+gun&type=issues
