### ISSUE TITLE
How to download openmoji folder that contains sub-folders(categoris) with normal name(eg:smiling face) just like in openmoji website?

### ISSUE THREAD

**Issue by software-Explorer** [hfg-gmuend/openmoji#506]
I make 2d animated videos where Openmoji can help me a lot. Openmoji can be very useful for video editors, photo editors and animators. Presently downloading .png folder contains all emojis in one place without categories and proper name so, I feel very difficult to use it. I read this issue for answer https://github.com/hfg-gmuend/openmoji/issues/487#issuecomment-1925654345  .
I am not good at programming so I cannot solve this problem. If anyone who can do it. It will be a great help.

Presently I use Openmoji website for finding proper emoji but I prefer working offline So, I need help.

**Comment by dawidpolakowski** [comment]
Hello, I have a lot of non technical customers and I understand your pain. 
I don't think that change in folder structure is the right move.
You can just save this page  https://hfg-gmuend.github.io/openmoji/  on your computer 🖥️ and use as reference.

**Comment by b-g** [comment]
Sorry! This is out of scope. Please use the https://openmoji.org/ to pick your emojis or write a script which renames the OpenMojis according to the data in /data/openmoji.json.
