### ISSUE TITLE
Stickers, OpenMoji attribution and license question

### ISSUE THREAD

**Issue by 1moeses** [hfg-gmuend/openmoji#507]
Heyhey, thank you so much for this wonderful project! you really provide a great library of emojis, images, graphics and more!

i have a question regarding your license and attribution. we would like to use (and edit) OpenMojies to print them on stickers for a (maybe in the future) commercial, but potentially non-profit project. since the stickers offer little room for attribution and are mainly there to link to our website, we wanted to ask if it is sufficient to give attribution to OpenMoji in the imprint of our website, instead of referring to OpenMoji on each and every sticker?

Thanks in advance and best regards :wave:

**Comment by b-g** [comment]
https://openmoji.org/faq/
