### ISSUE TITLE
Change Gun Emoji

### ISSUE THREAD

**Issue by nataliakeniganti** [hfg-gmuend/openmoji#513]

**Comment by mesaprotector** [comment]
The project follows the Unicode standard, where it is defined as a gun, and not a water gun. This issue has been brought up many times if you look through closed issues. It won't be changed unless Unicode themselves change the description.

**Comment by nataliakeniganti** [comment]
> The project follows the Unicode standard, where it is defined as a gun, and not a water gun. This issue has been brought up many times if you look through closed issues. It won't be changed unless Unicode themselves change the description.

Redesign Pistol Emoji Source: https://github.com/hfg-gmuend/openmoji/blob/master/src/activities/game/1F52B.svg

**Comment by b-g** [comment]
+1 closing, as stated above.
