### ISSUE TITLE
Update the Martinique flag to the new official flag

### ISSUE THREAD

**Issue by pouale** [hfg-gmuend/openmoji#517]
In february of 2023, [Martinique adopted a new flag after a contest](https://en.wikipedia.org/wiki/Flag_of_Martinique). Apple, Google and Samsung have already updated their emoji sets to reflect the change.

**Comment by b-g** [comment]
Many thanks for the pointer, please provide a PR reflecting these changes.

**Comment by b-g** [comment]
![Flag-of-Martinique svg](https://github.com/user-attachments/assets/faea8f43-5001-403f-a9d0-cfffe09729f1)

**Comment by nataliakeniganti** [comment]
![1F1F2-1F1F6](https://github.com/user-attachments/assets/bbe18bdd-f450-439f-9a2a-8bf6befecbae)

**Comment by b-g** [comment]
Done. Thanks!
