### ISSUE TITLE
export svgs with descriptive names

### ISSUE THREAD

**Issue by andest01** [hfg-gmuend/openmoji#52]
## What I would like

I use a screenshot program called ShareX that lets you take screenshots and, among other things, put images on them. It's useful at work. I would like to add your emojis to my file system so ShareX can use them as "Stickers".

![image](https://user-images.githubusercontent.com/1424223/67147696-9dcece80-f25c-11e9-8ccb-a6339bb11d84.png)

## It would be rad to add OpenMoji to my ShareX install!

![image](https://user-images.githubusercontent.com/1424223/67147708-d078c700-f25c-11e9-8ac1-eb1143ce3dac.png)

However, since all the file names are Unicode (which is technically correct, `the best kind of correct`), it's too difficult to quickly search for that `💯` I'm looking for, or if I'm feeling salty, `💩`.

### I would like descriptive file names, like `interaction-page-move.png`.

Is this possible to do?

**Comment by b-g** [comment]
Hi @andest01, many thanks for the interest! I'm afraid this is a bit out of scope for us. We don't want to have to maintain another set of files for very little overall gain. Sorry, this is too niche!

But you could write a simple rename script with the infos of `data/openmoji.json` ... see also the `helpers` folder for inspiration.
