### ISSUE TITLE
New and full moon emoji's don't match

### ISSUE THREAD

**Issue by carlinmack** [hfg-gmuend/openmoji#55]
Looking at [full moon](https://emojipedia.org/full-moon-with-face/) and [new moon](https://emojipedia.org/new-moon-with-face/) we can see that each platform has matching moon emoji's, whereas our full moon has eyebrows and the new moon has a nose as well as eye and shadow differences. It would be good to consolidate these, I'll have a go

**Comment by b-g** [comment]
Done
