### ISSUE TITLE
Grimacing face is not consistent with other platforms

### ISSUE THREAD

**Issue by carlinmack** [hfg-gmuend/openmoji#61]
The [grimacing face](https://emojipedia.org/grimacing-face/) emoji is commonly displayed as gritted teeth, where as the openmoji equivalent is similar to the [zany face](https://emojipedia.org/grinning-face-with-one-large-and-one-small-eye/)

**Comment by b-g** [comment]
Thanks! Seem to be a bug! We will look into it. Thanks for reporting!

<img width="707" alt="Screen Shot 2019-10-28 at 13 53 29" src="https://user-images.githubusercontent.com/480224/67703779-619d1b80-f98a-11e9-8b7f-319e5191dbc1.png">

**Comment by dnlutz** [comment]
fixed it using components from 1F976 cold face.
[1F62C_new_svg.zip](https://github.com/hfg-gmuend/openmoji/files/3797284/1F62C_new_svg.zip)

**Comment by carlinmack** [comment]
looks good! I experimented with the teeth being a lighter grey, it looks nice but this would be the only emoji face with grey on it 
![image](https://user-images.githubusercontent.com/6676843/68037372-f57a2a80-fc9d-11e9-97a4-f38644b461de.png)

**Comment by dnlutz** [comment]
i also like the grey interdental spaces ; ) but due to consistency reasons (cold face) i would rather keep the black lines. is that ok for you @carlinmack?

**Comment by carlinmack** [comment]
Yeah I think it's fine as it is now, if we want to incorporate grey later we can see where it would fit in across all the faces :)

**Comment by b-g** [comment]
Done
