### ISSUE TITLE
Inconsistent design of 1F472 man with skullcap and 1F47C baby angel

### ISSUE THREAD

**Issue by sourgift** [hfg-gmuend/openmoji#65]
The characters (and skintone variants) show the face without shoulders unlike other OpenMoji person characters.

**Comment by b-g** [comment]
![1F47C](https://user-images.githubusercontent.com/480224/67797798-d3dc3180-fa58-11e9-8049-cb331e6917c4.png)
![1F472](https://user-images.githubusercontent.com/480224/67797799-d3dc3180-fa58-11e9-94e6-3ceed3138f27.png)

Added images to facilitate discussion ... IMO no problem, happy to your @dnlutz thoughts on it :)

**Comment by dnlutz** [comment]
I agree with @b-g. "Baby Angel" has no torso on all other platforms and one could argue that angels are incorporeal beings ; ) "Man with Skullcap" is not quite so uniform on the different platforms but I'd leave him as he is.

But what we absolutely have to change are the pointed corners of "Baby Angel" 😱That is contrary to our guidelines. I fixed it in this ZIP file.
[1F47C_new_svg.zip](https://github.com/hfg-gmuend/openmoji/files/3797239/1F47C_new_svg.zip)

**Comment by b-g** [comment]
Done
