### ISSUE TITLE
Tired and weary face is not consistent with other platforms

### ISSUE THREAD

**Issue by carlinmack** [hfg-gmuend/openmoji#67]
The [tired](https://emojipedia.org/tired-face/) and [weary face](https://emojipedia.org/weary-face/) emoji consistently has a wide, down turned, open mouth — whereas our emojis have a closed mouth. I would argue that our emoji's do seem more tired/exhausted and fit the unicode spec better, but we do want platform consistency and all the platforms have agreed on the open mouth version.

Fairly obvious implementation notes but we'd want a common mouth and then switch the eyes out for >< for the tired face

**Comment by b-g** [comment]
Thanks! Could you provide images to facilitate discussion. Happy to discuss things :)

**Comment by carlinmack** [comment]
The links are above if you want to see all the platforms, here's a selection 

![image](https://user-images.githubusercontent.com/6676843/68130585-9577c400-fee9-11e9-8bf9-0b4f60a4b5b4.png)

**Comment by b-g** [comment]
Thanks! This looks to me like a bug. cc @dnlutz, OK?

**Comment by dnlutz** [comment]
we'll try to fix it next week during our openmoji workshop!

**Comment by carlinmack** [comment]
@dnlutz I can provide a larger list of consistency issues for the workshop if that's still to happen? I don't have a list at the moment but there's quite few that could be improved

**Comment by dnlutz** [comment]
unfortunately our workshop is quite small this time so i don't think we have time to fix all the things we want. nevertheless we should list the most frequent and obvious inconsistentcies … but you can take your time ; )

**Comment by b-g** [comment]
@carlinmack this issue seems to be redundant with #72. Closed.
