### ISSUE TITLE
Improvements needed for many zodiac symbols

### ISSUE THREAD

**Issue by sourgift** [hfg-gmuend/openmoji#68]
- Aries: smaller than usual horns (but somewhat similar to Apple and Samsung)
- Gemini: asymmetrical/off-center
- Virgo, Scorpio, Capricorn: appear hand-drawn/non-geometric
- Libra: off-center
- Sagittarius: large arrow head/non-proportional

Some other symbols have diverged from traditional forms, but are fairly consistent with other vendors. It's probably fine to leave them as is.

https://en.wikipedia.org/wiki/Astrological_sign
https://www.unicode.org/charts/PDF/U2600.pdf#search=Zodiacal

**Comment by dnlutz** [comment]
we will look into that during our openmoji workshop next week

**Comment by carlinmack** [comment]
Should I do this?

**Comment by b-g** [comment]
@carlinmack I would rather bundle your energy into more urgent things :) Yes they are not super nice ... but still kind of ok-ish.

**Comment by b-g** [comment]
Fixed and closed with #140. Thanks!!
