### ISSUE TITLE
Red heart missing shadow

### ISSUE THREAD

**Issue by sourgift** [hfg-gmuend/openmoji#69]
2764 red heart does not have a shadow like other colored hearts (white, black, brown, orange etc.)

**Comment by carlinmack** [comment]
![image](https://user-images.githubusercontent.com/6676843/68264783-09b08580-0018-11ea-92e9-f54e18bec799.png)
example

**Comment by b-g** [comment]
@dnlutz I would rather vote to get rid of all shadow. No need for 3d here IMO.

**Comment by dnlutz** [comment]
i would rather add a shadow to 2764 red heart. but do the shadows really make sense for the playing card symbols?
<img width="917" alt="Bildschirmfoto 2019-11-09 um 08 16 26" src="https://user-images.githubusercontent.com/38292227/68524647-9afa5300-02c9-11ea-96f6-85ff91788eae.png">

**Comment by b-g** [comment]
What is the conclusion now?

- Remove the shadows of the four playing card symbols
- Keep the colored hearts as they are and add a shadow to 2764

**Comment by carlinmack** [comment]
I think so, I'm not sure about adding the shadow in regards to this project, but removing the suit shadows I think is very reasonable as cards are 2D and the existing shadows don't look very good on the club for example

**Comment by b-g** [comment]
OK + Thanks! My conclusion:

- Remove the shadows of the four playing card symbols
- Keep the colored hearts as they are 
- Don't add a shadow to 2764

cc @dnlutz, ok?

**Comment by MahdiBaghbani** [comment]
@b-g sorry to interfere, I'm not a designer at all, but if you keep the colored hearts as they are and don't add a shadow to 2764, isn't that a case of inconsistent design? if a heart has shadow, all should have, and vice versa.

Also in your participate guidelines in openmoji.org you have stated "All objects should be displayed 2-dimensionally in a frontal view. For better distinction, an orthographic projection can also be used in exceptional cases." I don't think if heart is an exception at all. better to remove all shadows IMO.

**Comment by dnlutz** [comment]
i agree with you @MahdiBaghbani when we can do it flat then we should do it flat. then we are also more consistent with the other platforms: https://emojipedia.org/green-heart/

@b-g is it ok for you when we remove the shadows from all the hearts?

**Comment by b-g** [comment]
> is it ok for you when we remove the shadows from all the hearts?

Please 👍

**Comment by b-g** [comment]
Hi @bohnacker! Mega!! Many thanks for all commits ❤️! Just could you add a few hints of the improvements and changes to the `changelog.txt`? Hard to keep track otherwise :)

**Comment by bohnacker** [comment]
OK, didn't have that in mind. I'll do it immediately :)

**Comment by bohnacker** [comment]
I forgot about the four playing card symbols. The shadow have to be removed there. I'll do that as soon as possible, but for now I'm just reopening this issue.

**Comment by sourgift** [comment]
There are still a few heart characters with shadows:
- 1F970 smiling face with hearts
- 1F48F kiss (and variations: woman, man; man, man; woman, woman)
- 1F491 couple with heart (and variations: woman, man; man, man; woman, woman)


Also 1F5A4 black heart looks more like a grey heart now that the shadow was removed.

**Comment by bohnacker** [comment]
Thanks @sourgift for spotting. I was aware that there are some smileys and faces with hearts. I'll reopen this issue until all of them are removed.
And you're completely right: the black heart wasn't really black before and now it is even less black...

**Comment by carlinmack** [comment]
closed in 1813811

**Comment by b-g** [comment]
@carlinmack `❤` thanks!
