### ISSUE TITLE
White/gray/black palette guidelines unclear

### ISSUE THREAD

**Issue by sourgift** [hfg-gmuend/openmoji#71]
The primary and secondary colors have clear light and dark descriptions. The white/gray/black descriptions aren't as clear. It might be helpful to be more explicit.

Most images seem to use something like the following list.

White: #FFFFFF/#D0CFCE
Gray: #D0CFCE/#9B9B9A
Black: #9B9B9A/#3F3F3F (or #3F3F3F/#000000)

**Comment by dnlutz** [comment]
what do you mean specifically with being more explicit?
we definitely need the medium gray … and there's also a light and dark tone as for the other colours. so i don't know what we could improve on here?

**Comment by sourgift** [comment]
White (#FFFFFF) and black (#000000) aren't listed on the palette and it is unclear whether it is recommended to use them. Handling of these shades should be clear, such as when they can be used and when they should be avoided. With a better description it would be easier to evaluate whether the existing character designs are following the guidelines.

**Comment by dnlutz** [comment]
that's a good point! we should also list #fff and #000 in our color palette.

**Comment by b-g** [comment]
Done with https://github.com/hfg-gmuend/openmoji/commit/884a884b3dfdd860f66454fc4e0edaf62c96b485 and https://github.com/hfg-gmuend/openmoji-website/commit/f1ba33bb2e4d55f44a13b5df00bb0a25869612ed
