### ISSUE TITLE
Inaccurate positioning of many emojis 

### ISSUE THREAD

**Issue by bohnacker** [hfg-gmuend/openmoji#73]
Watching this [video](https://vimeo.com/336126508) on the openmoji.org start page, it's obvious that a lot of the emojis are not positioned accurately. Especially the standard smileys seem to have very inconsistent positions (and sometimes even sizes).

Is there a reason not to touch that? Otherwise I would try to help on that issue and start cleaning up. 
![1F9F9](https://user-images.githubusercontent.com/2828139/69060195-42d4f680-0a17-11ea-9989-ef813d771eb8.png)

**Comment by b-g** [comment]
Hi Hartmut, Yes we are ware of it ... but simply never had the time to look into it, as we are very busy with all the other issues :) Sorry! Any help on this would be very welcome. I guess it could potentially even be automated (see [helpers/force-color-palette-svg.js](https://github.com/hfg-gmuend/openmoji/blob/master/helpers/force-color-palette-svg.js) on how we process the svg files). An approach could be to translate everything relative based on the shapes in the Grid layer or for instance for the emojis find the big smiley circle and center everything based on it etc. Happy to walk you through if you think this helps.

**Comment by bohnacker** [comment]
Hi Benedikt,
I thought that you are aware of it. And I also thought of ways to automate that task. For the smileys there might be the best approach to find the biggest circle, which might be a bit more complicated if the circle is broken like in [this one](https://github.com/hfg-gmuend/openmoji/blob/master/src/smileys-emotion/face-affection/1F970.svg).

Either way, this will not be a very general solution. I guess that a (simple) tool to combine some automation and manual interaction might be the best.

**Comment by b-g** [comment]
Hi Hartmut, 

Yes you are right: automation and some manual tweaking in the combination seems the way forward. 

I could offer to write a test to check whether the grid layer has (accidentally) been slightly offset-ed. I guess for the ones where the grid layer is off ... one could then try to move back the entire file (every shape) by the delta of the correct - the current position of the gird layer.

Let me know if this were of help. Also happy to have a call on this to walk you through the current tooling.

**Comment by bohnacker** [comment]
Closing this issue and creating a new one to keep track of the cleanup process.
