### ISSUE TITLE
Clean up emojis – Help appreciated!

### ISSUE THREAD

**Issue by bohnacker** [hfg-gmuend/openmoji#76]
Some of the emoji graphics are needing cleanup (or at least checking, which ones are already good). Especially positioning might be helpful because that will show the most if used in an animation or on the same baseline. So, emojis that have a clear center or baseline should be in place.

There might be cases where it's not completely possible (see below). So try to come to the best possible solution (here at least vertical centering of the smileys big circle).
<img width="184" alt="grafik" src="https://user-images.githubusercontent.com/2828139/69267032-a0f70a80-0bcc-11ea-83bf-211a93881edd.png">

Please check a whole folder (e.g. activities/arts-crafts) at once. If everything is ok, post a comment in this issue to let me know and I'll update the TODO list below. If you have cleaned up things, please mention this issue in your commit/pull request.
Something like: 
#76 Cleaned up smileys-emotion/face-smiling/

- [ ] activities 
  - [ ] arts-crafts 
  - [ ] award-medal 
  - [ ] event 
  - [ ] game 
  - [ ] sport 
- [ ] animals-nature 
  - [ ] animal-amphibian 
  - [ ] animal-bird 
  - [ ] animal-bug 
	- [ ] animal-mammal 
  - [ ] animal-marine 
  - [ ] animal-reptile 
  - [ ] plant-flower 
  - [ ] plant-other 
- [ ] component	 
  - [ ] hair-style 
  - [ ] skin-tone 
- [ ] extras-openmoji 
  - [ ] animals-nature 
  - [ ] brand 
  - [ ] emergency 
  - [ ] food-drink 
  - [ ] interaction 
  - [ ] objects 
  - [ ] people 
  - [ ] technology 
  - [ ] travel-places 
  - [ ] ui-element 
- [ ] extras-unicode 
  - [ ] symbol-other 
- [ ] flags 
  - [ ] country-flag 
  - [ ] flag 
  - [ ] subdivision-flag 
- [ ] food-drink 
  - [ ] dishware 
  - [ ] drink 
  - [ ] food-asian 
  - [ ] food-fruit 
  - [ ] food-marine 
  - [ ] food-prepared 
  - [ ] food-sweet 
  - [ ] food-vegetable 
- [ ] objects 
  - [ ] book-paper 
  - [ ] clothing 
  - [ ] computer 
  - [ ] household 
  - [ ] light-video 
  - [ ] lock 
  - [ ] mail 
  - [ ] medical 
  - [ ] money 
  - [ ] music 
  - [ ] musical-instrument 
  - [ ] office 
  - [ ] other-object 
  - [ ] phone 
  - [ ] science 
  - [ ] sound 
  - [ ] tool 
  - [ ] writing 
- [ ] people-body 
  - [ ] body-parts 
  - [x] family 
  - [ ] hand-fingers-closed 
  - [ ] hand-fingers-open 
  - [ ] hand-fingers-partial 
  - [ ] hand-prop 
  - [ ] hand-single-finger 
  - [ ] hands 
  - [x] person 
  - [ ] person-activity 
  - [x] person-fantasy 
  - [ ] person-gesture 
  - [ ] person-resting 
  - [ ] person-role 
  - [ ] person-sport 
  - [ ] person-symbol 
- [x] smileys-emotion 
  - [x] cat-face 
  - [x] emotion 
  - [x] face-affection 
  - [x] face-concerned 
  - [x] face-costume 
  - [x] face-glasses 
  - [x] face-hand 
  - [x] face-hat 
  - [x] face-negative 
  - [x] face-neutral-skeptical 
  - [x] face-sleepy 
  - [x] face-smiling 
  - [x] face-tongue 
  - [x] face-unwell 
  - [x] monkey-face 
- [ ] symbols 
  - [ ] alphanum 
  - [ ] arrow 
  - [ ] av-symbol 
  - [ ] gender 
  - [ ] geometric 
  - [ ] keycap 
  - [ ] other-symbol 
  - [ ] religion 
  - [ ] transport-sign 
  - [ ] warning 
  - [ ] zodiac 
- [ ] travel-places 
  - [ ] hotel 
  - [ ] place-building 
  - [ ] place-geographic 
  - [ ] place-map 
  - [ ] place-other 
  - [ ] place-religious 
  - [ ] sky-weather 
  - [ ] time 
  - [ ] transport-air 
  - [ ] transport-ground 
  - [ ] transport-water

**Comment by carlinmack** [comment]
It's very easy for me to centre these emoji with inkscape but it saves it in a horrible format, how are you saving these? There's an optimised format with inkscape that is similar but it adds tags like `enable-background=`

**Comment by bohnacker** [comment]
Thanks @carlinmack that you tried to help here. I know that there are problems to find a good workflow. I'm using Adobe Illustrator, but still there are some problems.

To avoid the translate I'm guessing that you should not move the group, but move the elements inside that group. Because with SVGs, groups can only be moved by adding transforms. Probably that's why Inkscape adds that translate.

**Comment by carlinmack** [comment]
It would be great if SVGO or something could transform the file into a format which is unique - like all transforms and styling are pushed down to the elements, the styles are in a certain order, the strings are in a certain format (you can see that inkscape capitalises letters in the d="..."). That we we could be truly agnostic to editor choice as each SVG has only one valid way of representing the code.

For now I'll experiment with selecting all the paths instead and see if that works better. Is it important to preserve the empty groups?

**Comment by bohnacker** [comment]
Don't know if it's important to preserve the empty groups. It would make things easier, because in some cases even Illustrator removes them. And I already found some that didn't have them (and corrected that.
@b-g: Can you give information on that?

**Comment by b-g** [comment]
Hi both!

> Don't know if it's important to preserve the empty groups.

It would be good to ensure that every OpenMoji src svg has the 3 mandatory layers: `color`, `line` and `grid`. Otherwise the tests in https://github.com/hfg-gmuend/openmoji/blob/master/test/layer.js would fail.

> It would be great if SVGO or something could transform the file into a format which is unique - like all transforms and styling are pushed down to the elements, the styles are in a certain order, the strings are in a certain format (you can see that inkscape capitalises letters in the d="..."). That we we could be truly agnostic to editor choice as each SVG has only one valid way of representing the code.

Same thinking here. Because of this we have `npm run pretty-src-svg`, which already does a lot of what you've mentioned above. It was the only way to get a good diff of all the different ways Illustrator exports svgs (and to get rid of some of the crap).

Currently we do the following (see svgo config file https://github.com/hfg-gmuend/openmoji/blob/master/helpers/beautify-svg.yml):

```yml
full: true
plugins:
  - cleanupAttrs
  - inlineStyles
  - cleanupNumericValues:
      floatPrecision: 4
      leadingZero: false
  - convertColors:
      names2hex: true
      rgb2hex: true
      shorthex: false
      shortname: false
  - removeXMLProcInst
  - removeComments
  - removeMetadata
  - removeTitle
  - removeDesc
  - removeUselessDefs
  - removeEmptyText
  - removeUnusedNS
  - sortAttrs
js2svg:
  pretty: true
  indent: '  '
```

You can run SVGO on individual file with this command:

```
cd openmoji
node_modules/.bin/svgo src/activities/arts-crafts/1F3A8.svg --config helpers/beautify-svg.yml
```

And is seems SVGO in meantime got new features e.g. `convertTransform` which might already to what we need.

@carlinmack Could you export a file from Inkscape and see whether you can get it normalized to what we currently have (or something close)?

PS: I've just update to the latest SVGO version. Please pull and npm install.

**Comment by carlinmack** [comment]
Hi I've created a repository at https://github.com/carlinmack/SVG with 2 of our emojis in four formats, OpenMoji and three that Inkscape exports as. If you are experimenting with changing the SVGO you can run it on those files and see if they create something similar to the openmoji format. I chose these emoji as they're the ones with extra layers that are mentioned on the website
