### ISSUE TITLE
Clarify styleguide on coloring at open lines

### ISSUE THREAD

**Issue by bohnacker** [hfg-gmuend/openmoji#78]
Which of the following solutions is better? Should the color area align to the outer border of the black line (A) or should it be centered (B)? Or even something inbetween (C)? 
<img width="265" alt="Bildschirmfoto 2019-11-22 um 16 37 38" src="https://user-images.githubusercontent.com/2828139/69439584-8f863d80-0d47-11ea-9ab4-2b36fc27f5d1.png"> <img width="264" alt="Bildschirmfoto 2019-11-22 um 16 38 07" src="https://user-images.githubusercontent.com/2828139/69439585-8f863d80-0d47-11ea-989b-e390d088b456.png">
A: ![A](https://user-images.githubusercontent.com/2828139/69440232-babd5c80-0d48-11ea-95f6-8a18448afaf6.png)   B: ![B](https://user-images.githubusercontent.com/2828139/69440233-babd5c80-0d48-11ea-9fc6-4e0cb0bacb7b.png)  C: ![C](https://user-images.githubusercontent.com/2828139/69441795-9fa01c00-0d4b-11ea-9a61-c12eb5c1c7d6.png)

The emojis are done quite differently on that. Clarification in the styleguide might help.

**Comment by bohnacker** [comment]
By the way: I'd vote for version B (centered)
But maybe this can't be unified completely ...

**Comment by dnlutz** [comment]
Yes, we should definitely cover this topic in the style guide ; )

The big advantage of version A is that you get a continuous outline. Especially with darker fillings version B tends to become very fidgety … And Version C will be too complicated to produce (compared to A and B). 
So I would suggest we continue with version A … o.k.? Most Emoji are already designed like that, for example the animals:
<img width="547" alt="Bildschirmfoto 2019-11-22 um 17 21 12" src="https://user-images.githubusercontent.com/38292227/69442275-92cff800-0d4c-11ea-8285-a2b5298f28e1.png">
BTW happy you joined the project, dear colleague ; )

**Comment by b-g** [comment]
+1 for version (A)

Yes should be better explained in the style guide! thanks for pointing it out!

**Comment by carlinmack** [comment]
When we come to consensus we should fix the full size emoji in the README

![image](https://user-images.githubusercontent.com/6676843/69499635-165f2580-0ec2-11ea-8bc3-1fc654034adc.png)

**Comment by carlinmack** [comment]
Another issue to think about. I think that having option A leads to a webbed finger effect on some emoji? maybe we should default to A but use B in some explicit cases?

![image](https://user-images.githubusercontent.com/6676843/69873172-93edb180-1285-11ea-9b16-d646bb41a6df.png)

**Comment by dnlutz** [comment]
openmoji on black background is another issue for which we have no concept let alone solution. but on light backgrounds version (a) works much better so i would stick with it.

**Comment by carlinmack** [comment]
Can we close this issue with consensus on version A?

**Comment by dnlutz** [comment]
yes please ; ) i'm aware of the "webbed finger effect" but i think that's part of the bigger "black background issue" which we haven't worked out yet.

**Comment by b-g** [comment]
Please leave it open until the styleguide is updated the clarification ... otherwise we might forget it.

@dnlutz can you take care of it in February?

**Comment by carlinmack** [comment]
![image](https://user-images.githubusercontent.com/6676843/77110825-96bf0e80-69fc-11ea-990b-434eb6f90e6d.png)
thoughts? I'm not sure what to say 

I improved both of the emojis so that they are the best examples possible :)

**Comment by b-g** [comment]
@carlinmack That's great! Merged! Will deploy it today.

I changed 
- title from "color" to "contour and fill"
- added it to the sub menu (fixed double/wrong id)

**Comment by b-g** [comment]
Will close the issue. Please re-open in case I've missed something.
