### ISSUE TITLE
Contributors portraits

### ISSUE THREAD

**Issue by b-g** [hfg-gmuend/openmoji#81]
Dearest contributors,

Slowly but surely we are getting towards the new release v12.1 (tentative Jan 2020). Currently the tradition is that everyone does his/her own "portrait" to be listed under https://openmoji.org/about/#team. Please follow this tradition! :)

If you are interested please submit either a portraits and your links to this issue, or a PR to [openmoji-website](https://github.com/hfg-gmuend/openmoji-website) repo. (Add your infos to https://github.com/hfg-gmuend/openmoji-website/blob/master/about/index.html).

Many thanks! ❤️ 🙏

cc @carlinmack @bohnacker @sourgift @gromain @pyfisch @gurmukhp

**Comment by bohnacker** [comment]
@b-g : I've added an SVG to the openmoji-website/img/team and added me to about/index.html

**Comment by carlinmack** [comment]
Me too

**Comment by felixhaeberle** [comment]
I have to do my character as well 😄

**Comment by felixhaeberle** [comment]
@b-g my avatar is ready :)
<img width="281" alt="Screenshot 2019-12-16 02 32 22" src="https://user-images.githubusercontent.com/34959078/70873279-4c696400-1fad-11ea-951c-35e8710fe7fb.png">

upload it to the website soon. 🚢

**Comment by felixhaeberle** [comment]
added my avatar to the website 👍

**Comment by b-g** [comment]
Many thanks for the contributors portraits 🙏  @felixhaeberle @bohnacker @carlinmack!

OpenMoji 12.1 will be released next week. Final call: @sourgift @gromain @pyfisch @gurmukhp

**Comment by pyfisch** [comment]
@b-g thanks for the offer but I don't want to include my portrait.

Keep up the great work!
