### ISSUE TITLE
"Grinning Face With Smiling Eyes" and "Beaming Face With Smiling Eyes" look extremely similar

### ISSUE THREAD

**Issue by adamkex** [hfg-gmuend/openmoji#82]
As it can be seen here [here](https://emojipedia.org/smiling-face-with-open-mouth-and-smiling-eyes/) and [here](https://emojipedia.org/grinning-face-with-smiling-eyes/) that the emojis look quite different in almost every style. Currently in openmoji it's difficult to distinguish the two.

The description on emojipedia for "Beaming Face With Smiling Eyes" (Grinning Face With Smiling Eyes) is as follows:

> A yellow face with smiling eyes and full-toothed grin, as if saying Cheese! for the camera. Teeth may be smoothed-over or crosshatched. Often expresses a radiant, gratified happiness. Tone varies, including warm, silly, amused, or proud.

**Comment by b-g** [comment]
@adamkex Thanks! Please post images to facilitate the conversation.

**Comment by bohnacker** [comment]
This seems to be a problem on the emojipedia web site. Looking at the source code of their site the OpenMoji image links to 1F601 (which would be correct) but shows 1F604.

1F601 (Beaming face): ![1F601](https://user-images.githubusercontent.com/2828139/69729127-14959c00-1126-11ea-9eb9-69cf41c98d1d.png) 
1F604 (Grinning face): ![1F604](https://user-images.githubusercontent.com/2828139/69729144-1c554080-1126-11ea-9474-9093b4de2b60.png)

Still, the "Beaming face" should be smiling while our emoji is not looking happy.

**Comment by b-g** [comment]
I think we fixed that already but haven't released it. Emojipedia shows simply the last official release of v12 (same goes for openmoji.org).

Fixed @carlinmack?

**Comment by carlinmack** [comment]
This wasn't something I picked up on I don't think, I would say that our emoji could do with fixing though, I would say this is better

![image](https://user-images.githubusercontent.com/6676843/69844120-c02f1100-1238-11ea-818a-98a4eb721da6.png)

**Comment by bohnacker** [comment]
I think so too @carlinmack. That was also my first thought because it matches a lot better with all the other emojis from Apple, WhatsApp, ...

**Comment by carlinmack** [comment]
I'll open a PR

**Comment by b-g** [comment]
Done! Thanks!
