### ISSUE TITLE
Add special interest/plant emoji: Poppy

### ISSUE THREAD

**Issue by inferno986return** [hfg-gmuend/openmoji#84]
I would like to request a poppy emoji specifically the _Papaver rhoeas_. These are a symbol used to symbolise war remembrance.

https://github.com/inferno986return/poppy-emoji-proposal
https://github.com/Crissov/unicode-proposals/issues/113

**Note:** Unicode's response was that the design needs to be differentiated from the hibiscus.

![image](https://user-images.githubusercontent.com/1838420/69712935-8c9a9c80-10fb-11ea-8b8d-dfcf2eb84bc4.png)

**Comment by b-g** [comment]
Hi @inferno986return, many thanks for suggestion! Good one! But this might take a while ... what about giving it a try yourself? :) See our style guide on how to https://openmoji.org/styleguide/

**Comment by carlinmack** [comment]
Here's an attempt in our style, I've never added new openmoji though so I'm not sure what hexcode we'd give it etc

![poppy](https://user-images.githubusercontent.com/6676843/69884836-3fa7f900-12a8-11ea-9881-c3a18dcf98c5.png)

**Comment by b-g** [comment]
Nice! 

Just I'm a bit unsure whether it would be better to put more emphasis on:
`Poppy = Remembrance Day` vs `Poppy = nice red flower`. Hmm ... other thoughts?

@inferno986return Any Feedback?

**Poppy Remembrance Day**
![_104205826_p06r18hp](https://user-images.githubusercontent.com/480224/69891919-22862100-12ce-11ea-901c-8586e918eb2a.jpg)

**Other OpenMoji Flowers**
<img width="950" alt="Screen Shot 2019-11-29 at 17 29 24" src="https://user-images.githubusercontent.com/480224/69891913-19954f80-12ce-11ea-926e-5f4f9a0b45f1.png">

**Comment by carlinmack** [comment]
I'm from the UK and it's exclusively a remembrance day symbol rather than a flower, I was mimicking the shape of the poppy in your picture rather than the real flower which is more wrinkly

**Comment by inferno986return** [comment]
This is an excellent start! It's unambiguously a remembrance poppy.

My concern though is that the two-petal design is protected by the British Legion, hence a more generalised design based off the flower itself would be the best option.

**Comment by carlinmack** [comment]
looking into it poppyscotland owns the trademark for the four leaf design, guess we need to wait for a British Legion or poppyscotland emoji font 🙄

The concern here is that as the licence of openmoji is CCBYSA4 it can be used for commercial purposes so theoretically someone could use our font to defraud the british legion.

I truly wish design was more free :(

**Comment by carlinmack** [comment]
One concession we could make is a white poppy, which is used for conscientious objectors and such to the war. I don't think anyone holds copyright for it and aligns with the open-* philosophy, @b-g  thoughts?

**Comment by b-g** [comment]
Hmm ... I would not be too much worried about a hypothetical legal issue. OpenMoji has also other "trademarked" things e.g. everything in [Brand](https://openmoji.org/library/#group=extras-openmoji%2Fbrand). Normally a trademark is extremly specific in terms of the formal representation and the domain. Hence I don't see a conflict ... even the BBC is using a two-petal design.

I would simply go ahead with a red and two-petal and a very "recognizable" remembrance poppy design. But I would scale up the flower and put less emphasis on the entire plant. Basically more like in the BBC screenshot and less like the rest of the OpenMoji plants.

> The concern here is that as the licence of openmoji is CCBYSA4 it can be used for commercial purposes so theoretically someone could use our font to defraud the british legion.

Yes ... but this applies to any other "tool" and is IMO not a strong case to not do it. I still belive people have a conscience! :)

**Comment by carlinmack** [comment]
Added in b2e8217

**Comment by b-g** [comment]
Hi @carlinmack, many thanks for it! Nice!

RE: 

> @b-g did you want stem/leaf in the emoji?

I really like the size of the poppy and as it is now. And yes, I personally would add a hint of green e.g. tiny stem/leaf to better bring across that it refers to a plant. 

![2019-12-21 at 09 03](https://user-images.githubusercontent.com/480224/71309006-fcd1d080-23d0-11ea-9c5f-0f9154a8aa9b.jpg)

But also think @carlinmack and @inferno986return (= people really familiar with the UK war remembrance symbol) should have the final word.

**Comment by carlinmack** [comment]
@inferno986return thoughts?

![image](https://user-images.githubusercontent.com/6676843/71316914-d3ec2280-2446-11ea-9524-702bc9fb52d9.png)

**Comment by b-g** [comment]
@carlinmack Super! Almost! Comments ... more in the sense of trial & error, to be checked whether it is an improvement?

- Leaf stroke weight down to 1.8 or 1.6 see [Daniel's comments](https://github.com/hfg-gmuend/openmoji/issues/95#issuecomment-566024834)
- Leaf stroke start/end points should better support the curvature of the blossom. Now left start point is IMO too far apart
- Would try to see if the leave looks better if the green fill of the leave goes "under" the blossom, see [palm tree](https://openmoji.org/library/#group=animals-nature%2Fplant-other&emoji=1F334) emoji
- Would maybe break with the rule and color the stem dark green (and add a black one in line-supplement layer) and then the leave light green
- Would extend the stem down to the guide circle

**Comment by carlinmack** [comment]
https://openmoji.org/library/#group=extras-openmoji&emoji=E002

**Comment by inferno986return** [comment]
Nice to see the poppy on the website. It's certainly recognisable on its own.

**Comment by carlinmack** [comment]
![image](https://user-images.githubusercontent.com/6676843/71860793-2f164a00-30c2-11ea-8ae4-c80db5ec90ad.png)

done all but your second bullet point, how does this look? I think there should only be one green shade, both dark green

**Comment by b-g** [comment]
@carlinmack Great! Now looking over it I have one last idea to improve it further (sorry!) ... if you were rotating the leaf below the blossom you could have the stem in black, avoid the green stem exception and probably make it more readable as a plant/flower in general ... especially for all the non UK/FR users. What do you think?

![2020-01-07 at 10 30](https://user-images.githubusercontent.com/480224/71884876-71c73900-3139-11ea-8e58-c556df682541.jpg)

**Comment by carlinmack** [comment]
![image](https://user-images.githubusercontent.com/6676843/71909049-2a42ac00-313d-11ea-90eb-3e41db357ae7.png)
There doesn't seem to be a consistent place for the leaf as it can rotate but it's generally above (but for example daniel radcliffs isn't in that photo)

![image](https://user-images.githubusercontent.com/6676843/71909497-282d1d00-313e-11ea-9470-a46b79b2b411.png)

this is what that looks like

![image](https://user-images.githubusercontent.com/6676843/71909625-6a565e80-313e-11ea-8ef7-df5fb8fc0a19.png)

and centered

**Comment by b-g** [comment]
@carlinmack Many thanks for this! I find it a great compromise in the best way and would be happy with it. However I feel you should decide it as we (Daniel and me) are simply not familiar enough with the remembrance day poppy. Sorry! 

Just post it to social media in you network and let people vote for it? :)

Or @inferno986return any comments on it?

**Comment by carlinmack** [comment]
![Screenshot_20200110-124214_Instagram](https://user-images.githubusercontent.com/6676843/72174021-c7544d80-33a6-11ea-8a80-6619dabac018.jpg)

Social media has spoken!

**Comment by b-g** [comment]
@carlinmack 

:) Nice process! Glad that you've put so much thought and effort into it! Happy to merge it.

**Comment by carlinmack** [comment]
I'll make a PR when this is resolved https://github.com/hfg-gmuend/openmoji/pull/109#issuecomment-573181707

**Comment by carlinmack** [comment]
Added in 791febc2

**Comment by inferno986return** [comment]
I will add a final word and say I am pleased with the final result. Thank you @carlinmack

**Comment by paulpatr6** [comment]
I'm working on a poppy emoji proposal again! This time it'll be based on the actual flower since remembrance poppies are trademarked.

**Comment by inferno986return** [comment]
Just got the notification and I'd love to see some progress on this. 

I don't see why you could intellectually protect a naturally occurring flower! 😄

**Comment by paulpatr6** [comment]
> Just got the notification and I'd love to see some progress on this.
> 
> I don't see why you could intellectually protect a naturally occurring flower! 😄

Great, I will send you a pdf on your DMs. I'd love to work with you if you'd like

**Comment by paulpatr6** [comment]
actually I'll send it right here 

[Proposal for Emoji.pdf](https://github.com/user-attachments/files/22991649/Proposal.for.Emoji.pdf)

**Comment by inferno986return** [comment]
Admittedly, it's weird to see a project of mine revived like this but I love the progress you've made on the proposal for the Unicode Consortium. 😀

**Comment by paulpatr6** [comment]
Thank you. A big thing for them has been citations and multiple meanings so I tried to find as many as I could, although your proposal was extremely helpful as well. Feel free to leave any feedback, no matter how harsh it is! At the end of the day, the goal is to make this proposal the best it can be
