### ISSUE TITLE
Optimal Sorting of Attributes

### ISSUE THREAD

**Issue by carlinmack** [hfg-gmuend/openmoji#87]
We process the emoji's currently with SVGO but we currently don't sort the attributes properly which makes diff'ing SVGs harder. This is the default sort from SVGO:

```
order: [
    'id',
    'width', 'height',
    'x', 'x1', 'x2',
    'y', 'y1', 'y2',
    'cx', 'cy', 'r',
    'fill', 'stroke', 'marker',
    'd', 'points'
]
```

Some attributes like `viewBox` and `xmlns` are missing though so I propose this order

```
order: [
    'id',
    'viewBox',
    'width', 'height',
    'x', 'x1', 'x2',
    'y', 'y1', 'y2',
    'cx', 'cy', 'r',
    'fill', 'stroke', 'marker',
    'd', 'points',
    'xmlns'
]
```

Any thoughts are appreciated as the commit processing this will touch almost every single emoji (1900+ files)

For example for anyone that isn't sure what I mean, before and after using the default processing:
![image](https://user-images.githubusercontent.com/6676843/69884540-edb2a380-12a6-11ea-9158-5f084816b6f3.png)

**Comment by b-g** [comment]
Great! 

What about attributes like `stroke-linecap`? Do we have to list every attribute or are the SVGO parameters more of a prefix e.g. `stroke-*` for sorting?

```html
<line stroke="#000000" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" stroke-miterlimit="10" x1="35.7073" y1="47.2173" x2="35.7073" y2="35.2785" fill="#000000"/>
```

**Comment by carlinmack** [comment]
hmmm I'll need to look into if we can use stroke-*, I'm going to guess they have to be specified. Looking at this https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute there seems to be hundreds but I think we use under 30

**Comment by b-g** [comment]
Ok. I think then I would vote to write a script to list every attribute which is currently in use, so that we can make an informed decision. (Can also take care of this script next week).

**Comment by carlinmack** [comment]
Wrote the script

```
import os
import re

elementSet = set()
attributeSet = set()

for subdir, dirs, files in os.walk('src'):
    for file in files:
        #print os.path.join(subdir, file)
        filepath = subdir + os.sep + file
        if filepath.endswith(".svg"):
            with open(filepath) as file:
                for line in file:
                    line = line.strip()
                    if line[1] != "/":
                        try:
                            element = re.match("<(\w+) ", line).groups()[0]
                            attributes = re.findall(" ([\w-]+)=", line)

                            elementSet.add(element)
                            attributeSet.update(attributes)
                        except: 
                            if line != "<g>":
                                print(line)

                    
print("Elements: ", elementSet, "\n")
print("Attributes: ", attributeSet, "\n")
```

Output is:

```
Elements:  {'polygon', 'use', 'g', 'line', 'circle', 'polyline', 'ellipse', 'svg', 'path', 'clipPath', 'rect', 'defs'}        

Attributes:  {'clip-rule', 'paint-order', 'ry', 'overflow', 'xmlns', 'r', 'y2', 'd', 'stroke-linejoin', 'opacity', 'fill-rule', 'x', 'viewBox', 'version', 'stroke-linecap', 'data-name', 'clip-path', 'stroke-width', 'stroke-miterlimit', 
'x2', 'height', 'fill-opacity', 'fill', 'stroke-dasharray', 'y1', 'y', 'points', 'stroke', 'rx', 'id', 'transform', 'cy', 'enable-background', 'cx', 'width', 'x1'}
```

**Comment by carlinmack** [comment]
In light of this I'd propose:

```
order: [
    'id',
    'viewBox',
    'width', 'height',
    'x', 'x1', 'x2',
    'y', 'y1', 'y2',
    'cx', 'cy', 
    'r', 'rx', 'ry',
    'fill', 'stroke', 'stroke-dasharray', 
    'stroke-linecap', 'stroke-linejoin', 
    'stroke-miterlimit', 'stroke-width','marker',
    'd', 'points',
    'xmlns', 
    'clip-path', 'clip-rule', 
    'data-name', 'enable-background', 
    'fill-opacity', 'fill-rule', 
    'opacity', 'overflow', 
    'paint-order',  'transform', 
    'version'
]
```

I used a simple process for that, added all the new attributes to the end in alphabetical order and then moved r* and stroke* up to where the other attributes are.

Any thoughts? Should we maybe have transform and stuff moved to the top to make it obvious when things are transformed?

**Comment by b-g** [comment]
Thanks! Here are my thought! @bohnacker what do you think?

Sorting:

```
'id'

'x'
'x1'
'x2'
'cx'
'cy'
'y'
'y1'
'y2'
'r'
'rx'
'ry'

'width'
'height'

'transform'

'fill'
'fill-opacity'
'fill-rule'
'stroke'
'stroke-dasharray'
'stroke-linecap'
'stroke-linejoin'
'stroke-miterlimit'
'stroke-width'
'opacity'

'points'
'd'

'viewBox'
'overflow'
'paint-order'

'version'
'xmlns'

```

Get rid of them now:
```
// should be removed via SVGO settings
'enable-background' 
'data-name' // Adobe Illustrator legacy
```

Get rid of them in the near future:
```
// we should avoid those attributes -> get rid of them if possible
// would currently simply ignore them, or sort them at the end
'clip-rule'
'clip-path'
```

**Comment by b-g** [comment]
@carlinmack  Many thanks for the quick counting script! 🙏 Great! Lets wait what Hartmut responds ... and then go ahead. Happy weekend!

**Comment by dnlutz** [comment]
although I don't fully understand what you're doing here i have two questions: 

the workflow from illustrator will hopefully not become more complicated?
should we also take a look into affinity designer svgs (it's also a quite popular and powerful tool)?

**Comment by bohnacker** [comment]
The order @b-g suggested looks ok to me. Although I can't think of really important reasons to do it this or another way. For diff'ing any fixed order is good.

**Comment by carlinmack** [comment]
I think we would bundle the "checking" part and this new "cleaning" part into one, ie when you make a new emoji you either run one command line script or run it through the website and download it. 

I think it would be good to check Affinity Designer however it shouldn't cause any new problems as the SVG format is standardised.

**Comment by b-g** [comment]
@carlinmack 

What about working on this in a structured way in feature branch? Happy to invite you to the openmoji repo. (Just please don't push to the master branch unless your are 100% sure). OK?

> I think we would bundle the "checking" part and this new "cleaning" part into one, ie when you make a new emoji you either run one command line script or run it through the website and download it.

Yes: first people should be able to "normalize/clean" the svg and then to "test" it. However I would separate the concerns technically into two steps. Also this would require to change the openmoji-tester app ...

> Edit: I've been looking for a new svg tool and decided to buy Affinity, it's so much more powerful! :D I'll figure out a workflow for exporting SVGs that's compatible with OpenMoji

Great! Yes keep us posted ... would be great to have in addition to Illustrator more possibilities

**Comment by b-g** [comment]
@carlinmack also are you happy with the order in https://github.com/hfg-gmuend/openmoji/issues/87#issuecomment-559844790? If so we could go ahead (in a feature branch) ...

**Comment by carlinmack** [comment]
Yep that order looks good, however I would like to phase out transform at some point - it makes it harder to tell what's actually going on.

I think the steps could happen at once? hopefully cleaning shouldn't actually affect the display of the emoji and can nullify some of the tests (i.e. no style attribute)

That would be nice :) would save me from making PRs for obvious fixes, but I'll still make PRs for redesigns

**Comment by b-g** [comment]
@carlinmack 

> Yep that order looks good, however I would like to phase out transform at some point - it makes it harder to tell what's actually going on.

Yes. There might be a SVGO option for this.

> I think the steps could happen at once? hopefully cleaning shouldn't actually affect the display of the emoji and can nullify some of the tests (i.e. no style attribute)

Not so sure about this. Currently the openmoji-tester does not return the tested svg files ... it simply generates a test report.

> That would be nice :) would save me from making PRs for obvious fixes, but I'll still make PRs for redesigns

Done! I've added you! Yes ... new things via PRs is better.

**Comment by b-g** [comment]
@carlinmack, started to implement our thoughts from above ... see branch https://github.com/hfg-gmuend/openmoji/tree/svg-attributes-sorting.

Couldn't figure out quickly the syntax to remove the SVG attribute `xml:space="preserve"`. Could you do your fancy regex tricks? :) See also https://github.com/svg/svgo/blob/master/plugins/removeAttrs.js.

Anything else missing? Also we have to carefully check everything before we merge ... this will change every file in the src folder. 😬

**Comment by b-g** [comment]
You can run the SVGO alos just an couple of files eg. 1F3A*.svg

`find src/ -type f -name '1F3A*.svg' -print0 | xargs -0 -n 1 -P 6 node_modules/.bin/svgo --quiet --config helpers/beautify-svg.yml`

**Comment by carlinmack** [comment]
A month of delay but just implemented your request in 94e77c4 :) 

I would prefer for code style sake that there is a subsequent commit that alphabetises all of the plugins to make it more legible.

```
full: true
plugins:
  - cleanupAttrs
  - cleanupNumericValues:
      floatPrecision: 4
      leadingZero: false
  - convertColors:
      names2hex: true
      rgb2hex: true
      shorthex: false
      shortname: false
  - convertStyleToAttrs
  - convertTransform
  - inlineStyles
  - removeAttrs:
      attrs:
        - 'data-name'
        - 'inkscape.*'
        - 'xml.*'
        - 'svg:enable-background'
  - removeComments
  - removeDesc
  - removeEmptyText
  - removeMetadata
  - removeTitle
  - removeUnusedNS
  - removeUselessDefs
  - removeXMLProcInst
  - sortAttrs: 
      order: [
        'id',
        'x', 'x1', 'x2', 'cx',
        'y', 'y1', 'y2', 'cy', 
        'r', 'rx', 'ry',
        'width', 'height',
        'transform',
        'fill', 'fill-opacity', 'fill-rule',
        'stroke', 'stroke-dasharray', 'stroke-linecap',
        'stroke-linejoin', 'stroke-miterlimit', 'stroke-width',
        'opacity',
        'points', 'd',
        'viewBox',
        'overflow',
        'paint-order',
        'version',
        'xmlns']
      xmlnsOrder: 'back'
js2svg:
  pretty: true
  indent: '  '
```

**Comment by carlinmack** [comment]
Running `npm run pretty-src-svg` on a subset of the svgs (all the ones that I've edited) works well however it exits with 

``` 
npm ERR! code ELIFECYCLE
npm ERR! errno 123
```
and I'm not sure why, could you try running on a

**Comment by b-g** [comment]
Many thanks! Try this command for debugging `npm run pretty-src-svg`:

```
find src/ -type f -name '1F3A*.svg' -print0 | xargs -0 -n 1 -P 6 node_modules/.bin/svgo --config helpers/beautify-svg.yml
```
Note the removed --quite flag. 

But it works fine on my end. Could it be that you've tried to format already broken svg files (xml attribute bug)?

I think it would be good then to separate the mega refactoring into several commits ... for maximum transparency e.g. 
- removed attribute 'svg:enable-background'
- removed attribute 'xml.space'
...
- sorted attributes

**Comment by carlinmack** [comment]
yeah it was a broken SVG file

that's a really good idea, am I okay to do this on the `svg-attributes-sorting` branch now?

**Comment by carlinmack** [comment]
It's very slow work, I think each commit takes around an hour, I'll have it running in the background through the day and make commits as they finish

**Comment by b-g** [comment]
Great + super! Yes please commit into svg-attributes-sorting branch ... but we should then merge with master really fast as this will create a lot of conflicts. Let me know if you need a hand or I should have a look. Thanks!

**Comment by carlinmack** [comment]
As of 53aa7eb it's all done! It also only took 20 mins to run each step in the end

**Comment by b-g** [comment]
@carlinmack Many thanks! Merged! Removed the `convertTransform` flag. Too risky without fully testing it as it might have unintended side effects with the colorfont. Super nice to have the source svg files consistent now. Yay!

@bohnacker Heads up! Please pull and update from Master (in all your branches) ... otherwise you will have a lot of conflicts.
