### ISSUE TITLE
Support all ZWJ sequences

### ISSUE THREAD

**Issue by carlinmack** [hfg-gmuend/openmoji#96]
Inspired by #95 we should aim to support all emoji "not listed as RGI (Recommended for General Interchange) by Unicode". https://emojipedia.org/emoji-zwj-sequences/

~~We should try display the emojis on that page and add the ones that display incorrectly to a list~~

Not sure how valid this is but using the black openmoji font and vscode, it shows ones we support as a single character and others as multiple characters

![image](https://user-images.githubusercontent.com/6676843/70368879-7c628a00-187e-11ea-9fd2-09b67a9cc82d.png)

However we do have a pirate flag emoji so maybe this is also an issue with the font that we haven't realised?

### Erroneous ZWJ from the VS Code test:

- 👯🏻‍♂️ Men With Bunny Ears Partying, Type-1-2
- 👯🏼‍♂️ Men With Bunny Ears Partying, Type-3
- 👯🏽‍♂️ Men With Bunny Ears Partying, Type-4
- 👯🏾‍♂️ Men With Bunny Ears Partying, Type-5
- 👯🏿‍♂️ Men With Bunny Ears Partying, Type-6
- 👯🏻‍♀️ Women With Bunny Ears Partying, Type-1-2
- 👯🏼‍♀️ Women With Bunny Ears Partying, Type-3
- 👯🏽‍♀️ Women With Bunny Ears Partying, Type-4
- 👯🏾‍♀️ Women With Bunny Ears Partying, Type-5
- 👯🏿‍♀️ Women With Bunny Ears Partying, Type-6
- 🤼🏻‍♂️ Men Wrestling, Type-1-2
- 🤼🏼‍♂️ Men Wrestling, Type-3
- 🤼🏽‍♂️ Men Wrestling, Type-4
- 🤼🏾‍♂️ Men Wrestling, Type-5
- 🤼🏿‍♂️ Men Wrestling, Type-6
- 🤼🏻‍♀️ Women Wrestling, Type-1-2
- 🤼🏼‍♀️ Women Wrestling, Type-3
- 🤼🏽‍♀️ Women Wrestling, Type-4
- 🤼🏾‍♀️ Women Wrestling, Type-5
- 🤼🏿‍♀️ Women Wrestling, Type-6
- 🏴‍☠️ Pirate Flag
- 👩‍👶‍👧 Family: Woman, Baby, Girl
- 👩‍👩‍👶‍👦 Family: Woman, Woman, Baby, Boy
- 👩‍👩‍👶 Family: Woman, Woman, Baby
- 👩‍👩‍👧‍👶 Family: Woman, Woman, Girl, Baby
- 👩‍👩‍👦‍👶 Family: Woman, Woman, Boy, Baby
- 👩‍👩‍👦‍👧 Family: Woman, Woman, Boy, Girl
- 👩‍👨‍👶‍👶 Family: Woman, Man, Baby, Baby
- 👩‍👨‍👶‍👧 Family: Woman, Man, Baby, Girl
- 👩‍👨‍👶‍👦 Family: Woman, Man, Baby, Boy
- 👩‍👨‍👶 Family: Woman, Man, Baby
- 👩‍👩‍👶‍👶 Family: Woman, Woman, Baby, Baby
- 👩‍👨‍👧‍👶 Family: Woman, Man, Girl, Baby
- 👩‍👨‍👧‍👧 Family: Woman, Man, Girl, Girl
- 👩‍👨‍👧‍👦 Family: Woman, Man, Girl, Boy
- 👩‍👨‍👧 Family: Woman, Man, Girl
- 👩‍👨‍👦‍👶 Family: Woman, Man, Boy, Baby
- 👩‍👨‍👦‍👧 Family: Woman, Man, Boy, Girl
- 👩‍👨‍👦‍👦 Family: Woman, Man, Boy, Boy
- 👩‍👨‍👦 Family: Woman, Man, Boy
- 👨‍👩‍👶‍👶 Family: Man, Woman, Baby, Baby
- 👨‍👩‍👶‍👧 Family: Man, Woman, Baby, Girl
- 👨‍👩‍👶‍👦 Family: Man, Woman, Baby, Boy
- 👨‍👩‍👶 Family: Man, Woman, Baby
- 👨‍👩‍👧‍👶 Family: Man, Woman, Girl, Baby
- 👨‍👩‍👦‍👶 Family: Man, Woman, Boy, Baby
- 👨‍👩‍👦‍👧 Family: Man, Woman, Boy, Girl
- 👨‍👨‍👶‍👶 Family: Man, Man, Baby, Baby
- 👨‍👨‍👶‍👧 Family: Man, Man, Baby, Girl
- 👨‍👨‍👶‍👦 Family: Man, Man, Baby, Boy
- 👨‍👨‍👶 Family: Man, Man, Baby
- 👨‍👨‍👧‍👶 Family: Man, Man, Girl, Baby
- 👨‍👨‍👦‍👶 Family: Man, Man, Boy, Baby
- 👨‍👨‍👦‍👧 Family: Man, Man, Boy, Girl
- 👩‍👶 Family: Woman, Baby
- 👩‍👶‍👶 Family: Woman, Baby, Baby
- 👩‍👩‍👶‍👧 Family: Woman, Woman, Baby, Girl
- 👩‍👶‍👦 Family: Woman, Baby, Boy
- 👩‍👦‍👶 Family: Woman, Boy, Baby
- 👩‍👧‍👶 Family: Woman, Girl, Baby
- 👨‍👶 Family: Man, Baby
- 👨‍👶‍👦 Family: Man, Baby, Boy
- 👨‍👶‍👧 Family: Man, Baby, Girl
- 👨‍👶‍👶 Family: Man, Baby, Baby
- 👨‍👦‍👶 Family: Man, Boy, Baby
- 👨‍👧‍👶 Family: Man, Girl, Baby
- 👩‍👦‍👧 Family: Woman, Boy, Girl
- 👨‍👦‍👧 Family: Man, Boy, Girl

### Erroneous ZWJ from the VS Code test that we don't have designs for:

- 🐱‍👓 Hipster Cat
- 🐱‍🐉 Dino Cat
- 🐱‍🚀 Astro Cat
- 🐱‍💻 Hacker Cat - #95 
- 🐱‍👤 Ninja Cat
- 🐱‍🏍 Stunt Cat
- ◯‍◯‍◯‍◯‍◯ Olympic Rings

**Comment by b-g** [comment]
Hi @carlinmack, many thanks for the investigation!

> Erroneous ZWJ from the VS Code test

I believe it is simply a unicode data definition problem. For all the unicode definitions we have a hard dependency to `"emojibase-data": "^4.1.0"`. We are using the latest version. I checked a few samples on your list e.g. "🤼🏻‍♂️ Men Wrestling Type-1-2" and we simply didn't generate skintones versions as [Men Wrestling](https://openmoji.org/library/#search=wrestling&emoji=1F93C-200D-2642-FE0F) is defined without a skintone (from emojibase-data). Long story short: We would have to file a bug report at emojibase-data to get it fixed on our end. Could you check what is actually missing in the emojibase-data so that we can file an issue?

> Erroneous ZWJ from the VS Code test that we don't have designs for

Yes these would be fun ... however I'm a bit hesitant to add even more new todos on our list, especially if they are outside of official unicode and no body has requested them. Happy to add them I you take care of them :)

**Comment by carlinmack** [comment]
If they're not displaying correctly, would it not be all emoji in the first list? Or is it possible that some of these are our fault, like the families?

**Comment by b-g** [comment]
To be honest I don't know:
- either we simply haven't generated them, then the issues is the emojibase-data
- or the way I have generated the fonts is fishy e.g. I get the pirate flag in color, but not in black

Let's debug it top down from the data coming.

<img width="755" alt="Screen Shot 2019-12-09 at 13 10 39" src="https://user-images.githubusercontent.com/480224/70460937-74c10200-1a85-11ea-85ac-4bb1b70a304c.png">
(openmoji/font/demo.html)

**Comment by carlinmack** [comment]
try copy and paste from above and see what emoji's show, 
![image](https://user-images.githubusercontent.com/6676843/70461176-11839f80-1a86-11ea-8b68-9b07abb5bce7.png)
microsoft handles it well

**Comment by b-g** [comment]
- We don't have Family emojis with "Baby" (we have to design it)
- Pirate flag is fine, just not working in the black font (we have to fix in the fonts)
- We don't have skintones for any Wrestling emoijs as of the emojibase-data issue

**Comment by carlinmack** [comment]
We have baby emoji already so is it just a case of placing the glyphs together?

**Comment by b-g** [comment]
Yes, but you might have to redesign the Baby emoji to reflect the small size of it in a Family combination and in addition get emojibase-data fixed to pull from it the related Unicode definitions. But I'm not sure whether emojibase-data would want to include it as it seems not to be part of the Unicode standard:

> This Emoji ZWJ Sequence has not been Recommended For General Interchange (RGI) by Unicode. Expect limited cross-platform support.

(https://emojipedia.org/family-woman-baby-boy/)

If emojibase-data doesn't want to include it ... then I would rather vote currently against it. Too much effort for little gain on the big picture of OpenMoji. IMO more important is the soon upcoming Emoji 13 ...

**Comment by carlinmack** [comment]
Yep Emoji 13 is on my radar but thought we'd deal with the font, consistency issues before I open an issue with 100 new unique glyphs haha

**Comment by carlinmack** [comment]
I didn't realise microsoft was the only vendor supporting those family combinations! It may be the case that only the sporting ones are "widely" supported and are actually worth implementing

**Comment by b-g** [comment]
@carlinmack Can we close this issue? It seems nobody is keen to support non-standard ZWJ variants. Plz :)

The only ones in doubt are the wrestlers, see discussion in the emojibase repo.
https://github.com/milesj/emojibase/issues/40

**Comment by carlinmack** [comment]
sure!
