### ISSUE TITLE
Rename "weight" of Black/Colorfont to avoid double

### ISSUE THREAD

**Issue by felixhaeberle** [hfg-gmuend/openmoji#99]
When installing the font on MacOSX, the OpenMoji black font and color font having the same name and font "weight" (OpenMoji - Regular) causing trouble for example in InDesign. 

Steps to reproduce: Download both fonts and install them, now you see both styles are registered under Regular in the Font application in MacOSX causing for example InDesign to only have one "Regular" style available.

Maybe we can change the name or the font "weight" to be different.

**Comment by b-g** [comment]
@felixhaeberle thanks for the report! We are on it! cc @bohnacker
